In [1]:
# ── Cài đặt thư viện cần thiết ────────────────────────────────────────────────
# tree-sitter / tree-sitter-python : parse cây cú pháp (AST) cho Python
# gitpython                        : checkout commit của repo
# rank_bm25                        : tìm kiếm lexical (BM25)
# sentence-transformers            : sinh embedding (vector ngữ nghĩa)
# unidiff                          : đọc patch (unified diff) để lấy đáp án vàng
# datasets                         : tải benchmark SWE-bench
# orjson                           : đọc graph JSON nhanh hơn json chuẩn nhiều lần
!pip install tree-sitter tree-sitter-python gitpython igraph tqdm rank_bm25 sentence-transformers unidiff datasets tiktoken orjson -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 668.1/668.1 kB 10.3 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.1/108.1 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.5/231.5 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.5 MB/s eta 0:00:00

## 1. Constants & Function Definitions
All constants and function/class definitions. Run this section once — no I/O, no side effects.

In [2]:
# ╔══════════════════════════════════════════════════════════════════════════╗
# ║ CẤU HÌNH CHẠY — đổi các hằng số ở đây rồi Run All để chạy lại             ║
# ╚══════════════════════════════════════════════════════════════════════════╝

import os

# ── Thư mục làm việc: repo, graph, kết quả và file của judge đều nằm ở đây ─────────
# Kaggle chỉ hiển thị và lưu (khi Save Version) thư mục /kaggle/working; Colab dùng /content.
WORK_DIR = "/kaggle/working" if os.path.isdir("/kaggle/working") else "/content"
# Repo clone ra ngoài /kaggle/working (không được lưu, không tốn dung lượng output); graph và kết quả vẫn ở WORK_DIR
REPO_DIR = "/tmp/repos" if WORK_DIR == "/kaggle/working" else WORK_DIR
os.makedirs(REPO_DIR, exist_ok=True)

# ── Repositories ─────────────────────────────────────────────────────────────
# REPOS: các repo GitHub đưa vào thí nghiệm | repo_path_of(): nơi clone (trong REPO_DIR)
# Số instance trong SWE-bench Lite: flask 3, pytest 17, astropy 6, sphinx 16,
# scikit-learn 23, matplotlib 23, django 114 → tổng 202. Django có doc viết tay phong phú (file .txt,
# directive .. class:: / .. method::), khác kiểu autodoc của các repo còn lại; build lâu nhất.
# Còn có thể thêm: pydata/xarray 5, pylint-dev/pylint 6, psf/requests 6, mwaskom/seaborn 4.
# Lần chạy này so 3 kiểu doc: Django (viết tay), sphinx (pha trộn), sympy (autodoc) → 114 + 16 + 77 = 207.
REPOS = [
    # "pallets/flask",
    # "pytest-dev/pytest",
    # "astropy/astropy",
    # "scikit-learn/scikit-learn",
    # "matplotlib/matplotlib",
    "django/django",
    "sphinx-doc/sphinx",
    "sympy/sympy",
]
def repo_path_of(repo):
    return f"{REPO_DIR}/{repo.split('/')[1]}"

# Số instance tối đa mỗi repo; lấy mẫu cố định theo sha1(instance_id) → mỗi lần chạy ra cùng một tập.
# None = lấy hết; repo không có trong MAX_PER_REPO lấy tối đa MAX_PER_REPO_DEFAULT.
MAX_PER_REPO         = {"django/django": None, "sphinx-doc/sphinx": None, "sympy/sympy": None}
MAX_PER_REPO_DEFAULT = 10

# ── Section 5 (SWE-bench đầy đủ) ──────────────────────────────────────────────────────
# Section 5: SWE-bench đầy đủ, 1 graph cho mỗi khoảng SNAPSHOT_BIN_DAYS ngày trong mỗi version
# Toàn bộ 12 repo của SWE-bench đầy đủ: 2.294 instance (kết quả lượt trước: scale_rows_v2.jsonl, nhãn judge ở judge/)
SCALE_REPOS_ALL   = ["django/django", "sympy/sympy", "scikit-learn/scikit-learn", "sphinx-doc/sphinx",
                     "matplotlib/matplotlib", "pytest-dev/pytest", "pydata/xarray", "astropy/astropy",
                     "pylint-dev/pylint", "psf/requests", "mwaskom/seaborn", "pallets/flask"]
# Thực nghiệm v3: git history + judge chấm cả chunk doc và commit, trên django và sympy (1.186 instance dùng được)
SCALE_REPOS       = ["django/django", "sympy/sympy"]
SNAPSHOT_BIN_DAYS = 60
SCALE_RESULTS     = f"{WORK_DIR}/scale_rows_v3.jsonl"    # ghi dần mỗi instance 1 dòng; chạy lại thì tiếp tục
                                                         # (v3: cạnh Documents mới, lưu chunk doc, commit, nguồn history)

# ── Chặn các cell chỉ phục vụ v3 ─────────────────────────────────────────────
# RUN_V3 = False: cell có dòng đầu %%v3 (chạy lại truy hồi v3, phân tích v3, gửi batch judge v3) chỉ in 1 dòng rồi bỏ qua,
# để Run All hoặc Save Version của thực nghiệm v4 không chạy lại v3. Đặt True để chạy lại v3.
RUN_V3 = False
try:
    from IPython.core.magic import register_cell_magic

    def _v3_cell(line, cell):
        if RUN_V3:
            get_ipython().run_cell(cell)
        else:
            print("Bỏ qua cell của v3 (RUN_V3 = False)")

    register_cell_magic("v3")(_v3_cell)
except (ImportError, AttributeError, NameError):   # chạy ngoài IPython (vd harness trên máy)
    pass

# Tương thích ngược cho code dùng 1 repo (mặc định = repo đầu danh sách)
REPO      = REPOS[0]
REPO_PATH = repo_path_of(REPO)

# ── Embedding model ───────────────────────────────────────────────────────────
# Model embedding nhỏ, nhanh; dùng để vector hóa node code và doc-chunk
_EMBED_MODEL_ID = "BAAI/bge-small-en-v1.5"

# Cross-encoder reranker: chấm trực tiếp cặp (query, node) — thay RRF ở tầng
# xếp hạng hop (graph = sinh ứng viên, CE = xếp hạng)
_CE_MODEL_ID = "BAAI/bge-reranker-base"

# ── SWE-bench instance selector ───────────────────────────────────────────────
# Thay đổi INSTANCE_IDX rồi Run All để chạy lại cho instance khác.
# None → dùng HEAD hiện tại (không checkout).
INSTANCE_IDX = 0

# ── Embedding: tốc độ build graph ─────────────────────────────────────────────
# EMBED_FP16: trên GPU, embed bằng float16 (nhanh ~2 lần). Embedding lệch rất nhỏ so với
# float32, nên thứ hạng có thể đổi nhẹ. Đặt False để tái lập embedding float32 như trước.
EMBED_FP16  = True
EMBED_BATCH = 128   # batch lớn hơn tận dụng GPU tốt hơn; giảm về 64 nếu thiếu bộ nhớ

# Số graph giữ index trong RAM cùng lúc. Mỗi graph lớn chiếm vài trăm MB khi đã dựng index;
# không giới hạn thì chạy hết các instance sẽ làm Colab hết RAM.
INDEX_CACHE_MAX = 3

# In lại cấu hình để kiểm tra nhanh trước khi chạy phần sau
print(f"WORK_DIR       : {WORK_DIR}")
print(f"REPOS          : {', '.join(REPOS)}")
print(f"MAX_PER_REPO   : {MAX_PER_REPO} | mặc định: {MAX_PER_REPO_DEFAULT}")
print(f"EMBED_MODEL    : {_EMBED_MODEL_ID}")
print(f"CE_RERANKER    : {_CE_MODEL_ID}")
print(f"INSTANCE_IDX   : {INSTANCE_IDX}")
print(f"EMBED_FP16     : {EMBED_FP16} | EMBED_BATCH: {EMBED_BATCH}")
print(f"Section 5      : {', '.join(SCALE_REPOS)}, "
      f"snapshot {SNAPSHOT_BIN_DAYS} ngày → {SCALE_RESULTS}")
print(f"RUN_V3         : {RUN_V3}  (False = bỏ qua các cell có dòng đầu %%v3)")

WORK_DIR       : /kaggle/working
REPOS          : django/django, sphinx-doc/sphinx, sympy/sympy
MAX_PER_REPO   : {'django/django': None, 'sphinx-doc/sphinx': None, 'sympy/sympy': None} | mặc định: 10
EMBED_MODEL    : BAAI/bge-small-en-v1.5
CE_RERANKER    : BAAI/bge-reranker-base
INSTANCE_IDX   : 0
EMBED_FP16     : True | EMBED_BATCH: 128
Section 5      : django/django, sympy/sympy, snapshot 60 ngày → /kaggle/working/scale_rows_v3.jsonl
RUN_V3         : False  (False = bỏ qua các cell có dòng đầu %%v3)

### 1.1 Source File Discovery
List Python files using `git ls-files`, respecting `.gitignore`.

In [3]:
import subprocess

# ── Bộ lọc: bỏ test/example/docs và file cấu hình → graph chỉ chứa code "thật" ──
_SKIP_DIRS = {"tests", "test", "examples", "example", "benchmarks", "docs"}
_SKIP_FILES = {"conftest.py", "setup.py"}

def get_python_files(repo_path: str) -> list[str]:
    """List tracked .py files, excluding test/example directories and config files."""
    # Ưu tiên hỏi git (nhanh, đúng tập file được quản lý). Lỗi thì fallback rglob.
    try:
        out = subprocess.check_output(
            ["git", "ls-files", "--cached", "--others", "--exclude-standard"],
            cwd=repo_path, text=True, stderr=subprocess.DEVNULL,
        )
        paths = [l for l in out.splitlines() if l.endswith(".py")]
    except Exception:
        # Fallback: quét tay toàn bộ .py, bỏ thư mục .git
        paths = [
            str(p.relative_to(repo_path)).replace("\\", "/")
            for p in Path(repo_path).rglob("*.py")
            if ".git" not in p.parts
        ]

    # ── Áp bộ lọc thư mục/file lên danh sách thu được ──────────────────────────
    result = []
    for p in paths:
        parts = p.replace("\\", "/").split("/")
        # skip if any directory component is in _SKIP_DIRS
        if any(part in _SKIP_DIRS for part in parts[:-1]):
            continue
        # skip specific root-level filenames
        if parts[-1] in _SKIP_FILES:
            continue
        result.append(p)
    return result

### 1.2 Graph Schema & Data Model
Defines `ParseContext`, `SchemaPlugin`, and `SimpleSchema` — the data model for Modules, Classes, Functions and their relationships (Defines / Calls / Imports / Inherits).

In [4]:
from __future__ import annotations
import os
from abc import ABC, abstractmethod
from dataclasses import dataclass, field, replace as dc_replace
from typing import Callable


# ── ParseContext: "túi" trạng thái khi parse 1 file ──────────────────────────
# Giữ id module/scope cha, metadata commit/file, và các list output:
# nodes_out/edges_out (kết quả chắc chắn) + *_refs_out (ref chờ resolve cross-file).
@dataclass
class ParseContext:
    module_id:    str
    parent_id:    str
    commit:       str
    file_:        str
    directory:    str
    is_module_scope: bool
    current_class_id: str | None
    nodes_out:    list = field(default_factory=list)
    edges_out:    list = field(default_factory=list)
    call_refs_out:     list = field(default_factory=list)
    inherit_refs_out:  list = field(default_factory=list)
    instance_attr_types_out: list = field(default_factory=list)
    text_of: Callable = field(default=None, repr=False)

    @property
    def in_class(self) -> bool:
        return self.current_class_id is not None

    # Gom 1 node vào output (label + id + properties)
    def emit_node(self, label, nid, props):
        self.nodes_out.append({"labels": [label], "id": nid, "properties": props})

    # Gom 1 cạnh vào output (type + source→target, kèm field phụ tùy ý)
    def emit_edge(self, etype, src, tgt, **extra):
        entry = {"type": etype, "source": src, "target": tgt}
        entry.update(extra)
        self.edges_out.append(entry)


# ── SchemaPlugin: interface trừu tượng cho schema graph ──────────────────────
# Cho phép thay schema khác (định nghĩa node/edge nào) mà không sửa AST engine.
class SchemaPlugin(ABC):
    @abstractmethod
    def on_class(self, node, ctx): ...
    @abstractmethod
    def on_function(self, node, ctx): ...
    def on_import(self, target_module_id, ctx): pass
    @property
    @abstractmethod
    def call_edge_type(self): ...
    @property
    @abstractmethod
    def inherit_edge_type(self): ...


# ── SimpleSchema: schema thực dùng trong notebook ─────────────────────────────
# Node: Module / Class / Function | Edge: Defines / Calls / Imports / Inherits
class SimpleSchema(SchemaPlugin):
    """Module / Class / Function  +  Defines / Calls / Imports / Inherits"""

    @property
    def call_edge_type(self): return "Calls"
    @property
    def inherit_edge_type(self): return "Inherits"

    # Bắt gặp 1 định nghĩa class → tạo node Class + cạnh Defines (cha → class)
    def on_class(self, node, ctx):
        name = ctx.text_of(node.child_by_field_name("name"))
        if not name:
            return None
        cid = f"{ctx.parent_id}:{name}"   # parent_id, not module_id → correct nesting
        ctx.emit_node("Class", cid, {
            "name":       name,
            "commit":     ctx.commit,
            "file":       ctx.file_,
            "directory":  ctx.directory,
            "start_line": node.start_point[0] + 1,
            "end_line":   node.end_point[0] + 1,
            "source":     ctx.text_of(node)[:8000],   # cắt source để JSON không phình
        })
        ctx.emit_edge("Defines", ctx.parent_id, cid)
        return cid

    # Bắt gặp 1 định nghĩa function/method → tạo node Function + cạnh Defines
    def on_function(self, node, ctx):
        name = ctx.text_of(node.child_by_field_name("name"))
        if not name:
            return None
        fid = f"{ctx.parent_id}:{name}"
        ctx.emit_node("Function", fid, {
            "name":       name,
            "commit":     ctx.commit,
            "file":       ctx.file_,
            "directory":  ctx.directory,
            "start_line": node.start_point[0] + 1,
            "end_line":   node.end_point[0] + 1,
            "source":     ctx.text_of(node)[:8000],
        })
        ctx.emit_edge("Defines", ctx.parent_id, fid)
        return fid

    # Bắt gặp import đã resolve được → tạo cạnh Imports (module hiện tại → module đích)
    def on_import(self, target_module_id, ctx):
        ctx.emit_edge("Imports", ctx.module_id, target_module_id)


SCHEMA = SimpleSchema()

### 1.3 Language Extractor
Configures `LanguageExtractor` for tree-sitter-python — node type mappings and field names for Python AST traversal.

In [5]:
from dataclasses import dataclass as _dc
from tree_sitter import Language, Parser
import tree_sitter_python as tspython

# ── Khởi tạo parser tree-sitter cho Python ───────────────────────────────────
# try/except để tương thích cả API tree-sitter mới (>=0.22) lẫn cũ
try:
    _PY_LANG = Language(tspython.language())
    _parser  = Parser(_PY_LANG)
except TypeError:
    _PY_LANG = Language(tspython.language(), "python")
    _parser  = Parser()
    _parser.set_language(_PY_LANG)


# ── LanguageExtractor: "bảng tra" tên node-type/field của grammar Python ──────
# Trừu tượng hóa toàn bộ chi tiết grammar vào 1 chỗ → muốn hỗ trợ ngôn ngữ khác
# chỉ cần tạo extractor mới, không sửa ASTEngine.
@_dc(frozen=True)
class LanguageExtractor:
    parser: object
    language: object
    builtins: frozenset
    function_types: tuple
    class_types: tuple
    call_type: str
    import_type: str
    from_import_type: str
    assignment_types: tuple
    import_name_types: tuple
    aliased_import_type: str
    import_as_names_type: str
    wildcard_import_type: str
    import_keyword_type: str
    identifier_type: str
    name_field: str
    params_field: str
    superclasses_field: str
    module_name_field: str
    alias_name_field: str
    alias_alias_field: str
    call_function_field: str
    attribute_type: str
    attribute_object_field: str
    attribute_attr_field: str
    attr_name_subfield: str
    self_keywords: frozenset
    source_extensions: tuple = (".py",)
    index_file_name: str = "__init__"


# ── Cấu hình cụ thể cho Python ───────────────────────────────────────────────
EXTRACTOR = LanguageExtractor(
    parser=_parser,
    language=_PY_LANG,
    # builtins: bỏ qua khi tạo cạnh Calls (print/len/super... không phải hàm của repo)
    builtins=frozenset({
        "print", "len", "range", "str", "int", "float", "bool", "list", "dict",
        "tuple", "set", "type", "isinstance", "issubclass", "hasattr", "getattr",
        "setattr", "delattr", "super", "object", "enumerate", "zip", "map",
        "filter", "sorted", "reversed", "min", "max", "sum", "abs", "round",
        "open", "repr", "iter", "next", "any", "all", "vars", "dir", "id",
        "hash", "callable", "staticmethod", "classmethod", "property",
    }),
    # In tree-sitter-python 0.25+, `async def` is function_definition (no separate node type)
    function_types=("function_definition",),
    class_types=("class_definition",),
    call_type="call",
    import_type="import_statement",
    from_import_type="import_from_statement",
    assignment_types=("assignment", "annotated_assignment", "expression_statement"),
    import_name_types=("dotted_name", "aliased_import"),
    aliased_import_type="aliased_import",
    import_as_names_type="import_as_names",
    wildcard_import_type="wildcard_import",
    import_keyword_type="import",
    identifier_type="identifier",
    name_field="name",
    params_field="parameters",
    superclasses_field="superclasses",
    module_name_field="module_name",
    alias_name_field="name",
    alias_alias_field="alias",
    call_function_field="function",
    attribute_type="attribute",
    attribute_object_field="object",
    attribute_attr_field="attribute",
    attr_name_subfield="",
    # self_keywords: nhận diện gọi method trên chính object (self.x()/cls.x())
    self_keywords=frozenset({"self", "cls"}),
)

### 1.4 Doc Extractor
`DocExtractor` parses `.rst` / `.md` documentation files — creates `Document` + `DocChunk` nodes with `HasChunk` edges, and collects pending `Documents` links (via `.. autofunction::` / `:func:` / `:meth:` / `:class:`) and `References` links (via `:doc:`) for resolution after code parsing.

In [6]:
import re
from pathlib import Path

# ── Tham số bóc tách doc ──────────────────────────────────────────────────────
MAX_CHUNK_CHARS = 1600   # ~400 tokens × 4 chars
_RST_ADORN = set("=-~^*+#<>")          # ký tự gạch chân heading RST (===, ---, ~~~)

_DOC_DIR_CANDIDATES = ("docs", "doc", "documentation", "Documentation")
_DOC_SKIP = {"_build", "_static", "_templates", "_themes", "generated", "auto_examples"}


# ── Liệt kê file tài liệu (.rst/.md/.txt), bỏ thư mục build/generated ────────
def get_doc_files(repo_path):
    repo = Path(repo_path)
    # Lấy thư mục doc đầu tiên tồn tại trong danh sách ứng viên
    docs_dir = next(
        (repo / d for d in _DOC_DIR_CANDIDATES if (repo / d).is_dir()),
        None,
    )
    if docs_dir is None:
        return []
    out = []
    for ext in ("*.rst", "*.md", "*.txt"):      # Django viết doc RST trong file .txt
        for p in sorted(docs_dir.rglob(ext)):
            if any(part in _DOC_SKIP for part in p.parts):
                continue
            if p.suffix == ".txt" and p.name.lower().startswith(("requirements", "robots")):
                continue                            # file .txt không phải doc
            out.append(str(p.relative_to(repo)).replace("\\", "/"))
    return out


# ── DocExtractor: 1 file doc → node Document + nhiều DocChunk + link chờ resolve
class DocExtractor:
    # Regex bắt các directive RST trỏ tới code/doc khác:
    _ROLE_RE = re.compile(r":(?:func|meth|class|attr|exc|obj):`([^`]+)`")   # :func:`x`
    # .. autoclass:: x và directive Python domain viết tay .. class:: x / .. py:method:: x (vd Django).
    # Tên dừng ở "(" → bỏ chữ ký: ".. class:: Model(**kwargs)" → "Model"
    _DIR_RE  = re.compile(r"\.\.\s+(?:py:)?(?:auto)?(function|class|method|exception|attribute|decorator)::\s+([~\w.]+)")
    _DOC_RE  = re.compile(r":doc:`([^`]+)`")                                # :doc:`x` (doc→doc)
    _MOD_RE  = re.compile(r"\.\.\s+(?:current)?module::\s+(\S+)")           # .. module:: (ngữ cảnh module)

    def __init__(self, rel_path, repo_path):
        self.rel_path = rel_path
        self.abs_path = Path(repo_path) / rel_path

    # Đọc file → chia chunk theo heading → bắt link → trả nodes/edges + link chờ resolve
    def extract(self):
        try:
            text = self.abs_path.read_text(encoding="utf-8", errors="replace")
        except Exception:
            return None

        lines  = text.splitlines()
        doc_id = f"doc:{self.rel_path}"
        ext    = Path(self.rel_path).suffix.lstrip(".")

        # Node Document đại diện cho cả file
        doc_node = {
            "id": doc_id, "label": "Document",
            "file": self.rel_path, "type": ext,
            "title": self._first_heading(lines) or Path(self.rel_path).stem,
        }

        nodes, edges = [doc_node], []
        pending_links, pending_refs = [], []   # link doc→code / doc→doc, resolve ở bước sau
        current_module = None                  # ngữ cảnh .. module:: hiện hành
        current_class  = None                  # class gần nhất (cho .. method:: không có tiền tố class)

        # Duyệt từng (heading, body) → tạo node DocChunk + cạnh HasChunk + bắt link
        for i, (heading, body) in enumerate(self._split(lines)):
            cid = f"chunk:{self.rel_path}:{i}"
            nodes.append({
                "id": cid, "label": "DocChunk",
                "file": self.rel_path, "heading": heading,
                "index": i, "text": body, "embedding": None,
            })
            edges.append({"type": "HasChunk", "source": doc_id, "target": cid})

            combined = f"{heading}\n{body}"
            # Cập nhật module ngữ cảnh nếu gặp directive .. module::
            for m in self._MOD_RE.finditer(combined):
                v = m.group(1)
                current_module = None if v == "None" else v
                current_class = None

            # Gom các link để resolve sau (kèm module ngữ cảnh để định danh đầy đủ)
            # Directive định nghĩa đối tượng; method/attribute không có tiền tố class → gán class gần nhất
            for m in self._DIR_RE.finditer(combined):
                kind, name = m.group(1), m.group(2)
                if kind == "class":
                    current_class = name.lstrip("~.").split(".")[-1]
                elif kind in ("method", "attribute") and "." not in name and current_class:
                    name = f"{current_class}.{name}"
                pending_links.append((cid, name, current_module))
            for m in self._ROLE_RE.finditer(combined):
                pending_links.append((cid, m.group(1), current_module))
            for m in self._DOC_RE.finditer(combined):
                pending_refs.append((cid, m.group(1)))

        return {
            "doc_id": doc_id, "nodes": nodes, "edges": edges,
            "pending_links": pending_links, "pending_refs": pending_refs,
        }

    # Tìm heading đầu tiên của file (dòng có gạch chân RST ngay dưới) làm title
    def _first_heading(self, lines):
        for i in range(1, len(lines)):
            ul = lines[i].strip()
            if ul and all(c == ul[0] for c in ul) and ul[0] in _RST_ADORN:
                prev = lines[i - 1].strip()
                if prev and len(ul) >= len(prev):
                    return prev
        return None

    # Chia file thành các (heading, body) theo ranh giới heading RST
    def _split(self, lines):
        boundaries = []
        for i in range(1, len(lines)):
            ul = lines[i].strip()
            if ul and all(c == ul[0] for c in ul) and ul[0] in _RST_ADORN:
                prev = lines[i - 1].strip()
                if prev and len(ul) >= len(prev):
                    boundaries.append((i - 1, prev))

        # Không có heading nào → cả file là 1 chunk
        if not boundaries:
            body = "\n".join(lines).strip()
            return [("", body)] if body else []

        # Mỗi heading → body từ sau gạch chân tới heading kế tiếp
        chunks = []
        for idx, (pos, heading) in enumerate(boundaries):
            start = pos + 2
            end   = boundaries[idx + 1][0] if idx + 1 < len(boundaries) else len(lines)
            body  = "\n".join(lines[start:end]).strip()
            if not body:
                continue
            for chunk in self._maybe_split(heading, body):
                chunks.append(chunk)
        return chunks

    # Chunk dài quá MAX_CHUNK_CHARS → cắt nhỏ theo đoạn (giữ nguyên heading)
    def _maybe_split(self, heading, body):
        if len(body) <= MAX_CHUNK_CHARS:
            return [(heading, body)]
        parts, cur, cur_len = [], [], 0
        for para in re.split(r"\n\n+", body):
            plen = len(para)
            if cur and cur_len + plen > MAX_CHUNK_CHARS:
                parts.append((heading, "\n\n".join(cur)))
                cur, cur_len = [para], plen
            else:
                cur.append(para)
                cur_len += plen
        if cur:
            parts.append((heading, "\n\n".join(cur)))
        return parts or [(heading, body)]


# ── Bảng tên → các node code có tên đó, để resolve link RST ─────────────────────────────────
# Mỗi khóa giữ MỌI node khớp (tên trùng nhau không bị ghi đè); resolve_doc_links quyết định khi nhiều node khớp.
from collections import defaultdict

def _file_module(file):
    """Đường dẫn file → tên module dạng chấm, bỏ tiền tố src. và đuôi .__init__ (docs không viết src.)."""
    m = file.replace("/", ".").removesuffix(".py").removesuffix(".__init__")
    return m[4:] if m.startswith("src.") else m

def build_name_index(code_nodes):
    """Build name key -> {node_id} for RST role resolution (multiple keys per node, multiple nodes per key)."""
    idx = defaultdict(set)
    for n in code_nodes:
        if n["label"] not in ("Function", "Class"):
            continue
        nid  = n.get("id", "")
        name = n.get("name", "")
        file = n.get("file", "")
        if not name:
            continue
        # Docs không document test — chặn test file khỏi index kẻo tên bị "cướp"
        # (vd pytest: Config resolve vào testing/test_assertion.py thay vì src)
        _parts = file.split("/")
        if any(p in ("test", "tests", "testing") for p in _parts) or _parts[-1].startswith("test_"):
            continue
        # Đăng ký nhiều khóa: module.name, pkg.name (dạng re-export: flask.url_for), name thuần, Class.name, pkg.Class.name
        file_mod = _file_module(file)
        keys = {f"{file_mod}.{name}", f"{file_mod.split('.')[0]}.{name}", name}
        try:
            parts = nid.split(f":{file}:", 1)[1].split(":")
            if len(parts) >= 2:
                keys |= {f"{parts[-2]}.{name}", f"{file_mod.split('.')[0]}.{parts[-2]}.{name}"}
        except (IndexError, ValueError):
            pass
        for k in keys:
            idx[k].add(nid)
    return idx


# ── Resolve link chờ → cạnh Documents (doc→code) và References (doc→doc) ──────
def resolve_doc_links(doc_results, name_index):
    """Resolve pending RST links -> Documents + References edges (deduped).
    Documents: thử lần lượt tên kèm module ngữ cảnh (.. module::), tên như doc viết, Class.method, tên cuối.
    Khóa đầu tiên có ứng viên quyết định: 1 node → nối; nhiều node → chỉ giữ node nằm trong module ngữ cảnh;
    vẫn mơ hồ → không nối (không chọn bừa một node trùng tên)."""
    doc_ids = {r["doc_id"] for r in doc_results}
    edges, seen = [], set()

    for r in doc_results:
        # pending_links → cạnh Documents (module ngữ cảnh trước; nhiều node khớp thì lọc theo module, mơ hồ thì bỏ)
        for cid, raw, cur_mod in r["pending_links"]:
            name = raw.strip()
            m = re.search(r"<([^<>]+)>$", name)          # role có tiêu đề riêng: `text <target>`
            if m:
                name = m.group(1)
            name = name.lstrip("~.").removesuffix("()")
            tries = ([f"{cur_mod}.{name}"] if cur_mod else []) + [
                name, ".".join(name.split(".")[-2:]), name.split(".")[-1]]   # Class.method, tên cuối
            target = None
            for k in dict.fromkeys(tries):
                cand = name_index.get(k)
                if not cand:
                    continue
                if len(cand) == 1:
                    target = next(iter(cand))
                elif cur_mod:
                    narrow = [t for t in cand if _file_module(t.split(":", 2)[1]).startswith(cur_mod)]
                    target = narrow[0] if len(narrow) == 1 else None
                break
            if target:
                key = ("Documents", cid, target)
                if key not in seen:
                    edges.append({"type": "Documents", "source": cid, "target": target})
                    seen.add(key)

        # pending_refs → cạnh References (thử đuôi .rst/.txt/.md, kèm và không kèm tiền tố thư mục doc)
        for cid, ref in r["pending_refs"]:
            m = re.search(r"<([^<>]+)>$", ref.strip())   # :doc:`text <target>`
            ref = (m.group(1) if m else ref).strip().lstrip("/")
            base = re.sub(r"\.(rst|txt|md)$", "", ref)
            tgt_candidates = []
            for e in (".rst", ".txt", ".md"):
                tgt_candidates.append(f"doc:{base}{e}")
                for doc_dir in _DOC_DIR_CANDIDATES:
                    if not base.startswith(f"{doc_dir}/"):
                        tgt_candidates.append(f"doc:{doc_dir}/{base}{e}")
            for tgt in tgt_candidates:
                if tgt in doc_ids:
                    key = ("References", cid, tgt)
                    if key not in seen:
                        edges.append({"type": "References", "source": cid, "target": tgt})
                        seen.add(key)
                    break

    return edges

### 1.5 AST Engine
`ASTEngine` parses one `.py` file in 4 passes (definitions → imports → calls → self-assigns) and maps imports for cross-file resolution.

In [7]:
import logging
import os
from dataclasses import replace as dc_replace
from tree_sitter import Query, QueryCursor

logger = logging.getLogger(__name__)


# ── Helper: chạy 1 Query và trả {tên_capture: [Node]} (chuẩn hóa API tree-sitter)
def _caps(query, node):
    """Execute a Query and return {capture_name: [Node]} (tree-sitter 0.24+ API)."""
    result = QueryCursor(query).captures(node)
    if isinstance(result, dict):
        return result
    # Pre-0.24 fallback: list of (Node, str) tuples
    d = {}
    for n, name in result:
        d.setdefault(name, []).append(n)
    return d


class ASTEngine:
    """Parse một file .py → nodes + refs cho cross-file resolve."""

    # Khởi tạo: tính id module, chuẩn bị sẵn 4 Query (defs/imports/calls/assigns)
    def __init__(self, file_path, repo_path, base_commit, schema, extractor):
        self.extractor   = extractor
        self.file_path   = file_path
        self.repo_path   = repo_path
        self.base_commit = base_commit
        self.schema      = schema
        try:
            self.rel_path = os.path.relpath(file_path, repo_path).replace("\\", "/")
        except ValueError:
            self.rel_path = file_path.replace("\\", "/")
        self.module_id   = f"{self.base_commit}:{self.rel_path}"
        self._source: bytes = b""
        self.import_map: dict[str, str] = {}            # alias → module/symbol id
        self.from_import_map: dict[str, str | None] = {} # tên local → "module_id:tên_gốc"

        ext  = extractor
        lang = extractor.language
        self._q_defs = Query(lang,
            "\n".join(f"({t}) @def" for t in (*ext.class_types, *ext.function_types))
        )
        self._q_imports = Query(lang,
            f"({ext.import_type}) @stmt\n({ext.from_import_type}) @stmt"
        )
        self._q_calls   = Query(lang, f"({ext.call_type}) @call")
        self._q_assigns = Query(lang, "(assignment) @assign")

    # ── Public ─────────────────────────────────────────────────────────────────

    # Điểm vào: đọc file → parse → chạy 4 pass → trả dict kết quả cho resolve sau
    def parse(self):
        try:
            with open(self.file_path, "rb") as f:
                self._source = f.read()
        except Exception:
            return None
        try:
            tree = self.extractor.parser.parse(self._source)
        except Exception:
            return None

        commit, _, file_ = self.module_id.partition(":")
        ctx = ParseContext(
            module_id=self.module_id, parent_id=self.module_id,
            commit=commit, file_=file_,
            directory=os.path.dirname(file_) or ".",
            is_module_scope=True, current_class_id=None,
            text_of=self._text,
        )
        ctx.emit_node("Module", self.module_id, {"name": self.rel_path, "commit": self.base_commit})

        # 4 pass bóc tách trên cùng cây cú pháp
        self._extract_definitions(tree, ctx)
        self._extract_imports(tree, ctx)
        self._extract_calls(tree, ctx)
        self._extract_self_assigns(tree, ctx)

        # local_scope/class_scopes phục vụ resolve call cross-file
        local_scope, class_scopes = self._build_scopes(ctx.nodes_out)
        return {
            "module_id":    self.module_id,
            "nodes":        ctx.nodes_out,
            "definite_edges":      ctx.edges_out,
            "call_refs":           ctx.call_refs_out,
            "inherit_refs":        ctx.inherit_refs_out,
            "instance_attr_types": ctx.instance_attr_types_out,
            "import_map":          self.import_map,
            "from_import_map":     self.from_import_map,
            "local_scope":         local_scope,
            "class_scopes":        class_scopes,
        }

    # ── Scope helpers ──────────────────────────────────────────────────────────

    # Leo node.parent → id scope CHỨA node (vd "commit:file:Class:method")
    def _scope_of(self, node):
        """ID of the scope that CONTAINS node (walks up node.parent chain)."""
        ext, parts, cur = self.extractor, [], node.parent
        while cur is not None:
            if cur.type in (*ext.class_types, *ext.function_types):
                n = cur.child_by_field_name(ext.name_field)
                if n:
                    parts.append(self._text(n))
            cur = cur.parent
        return ":".join([self.module_id] + list(reversed(parts))) if parts else self.module_id

    # Leo node.parent → id class bao quanh gần nhất (hoặc None)
    def _class_of(self, node):
        """ID of the innermost class enclosing node, or None."""
        ext, cur = self.extractor, node.parent
        while cur is not None:
            if cur.type in ext.class_types:
                n = cur.child_by_field_name(ext.name_field)
                if n:
                    return f"{self._scope_of(cur)}:{self._text(n)}"
            cur = cur.parent
        return None

    # ── Pass 1: class + function definitions ──────────────────────────────────

    # Tìm mọi class/function (sắp theo vị trí) → tạo node; với class còn lấy superclass
    def _extract_definitions(self, tree, ctx):
        ext = self.extractor
        def_nodes = sorted(_caps(self._q_defs, tree.root_node).get("def", []),
                           key=lambda n: n.start_byte)
        for node in def_nodes:
            tmp = dc_replace(ctx, parent_id=self._scope_of(node),
                             current_class_id=self._class_of(node))
            if node.type in ext.class_types:
                cid = self.schema.on_class(node, tmp)
                if cid:
                    # Bóc danh sách lớp cha → inherit_refs (chờ resolve thành cạnh Inherits)
                    supers = node.child_by_field_name(ext.superclasses_field)
                    if supers:
                        for arg in supers.children:
                            base = self._extract_base_name(arg)
                            if base:
                                ctx.inherit_refs_out.append({"class_id": cid, "base_name": base})
            else:
                self.schema.on_function(node, tmp)

    # ── Pass 2: imports ────────────────────────────────────────────────────────

    # Xử lý `import x` và `from a import b` → build import_map/from_import_map + cạnh Imports
    def _extract_imports(self, tree, ctx):
        ext = self.extractor
        for node in _caps(self._q_imports, tree.root_node).get("stmt", []):
            if node.type == ext.import_type:
                # import a.b as c → tách module + alias, resolve sang file thật
                for sub in node.children:
                    if sub.type in ext.import_name_types:
                        raw = self._text(sub)
                        mod_str, _, alias = raw.partition(" as ")
                        mod_str = mod_str.strip()
                        alias   = alias.strip() if alias.strip() else mod_str.split(".")[-1]
                        tid = self._resolve_module(mod_str)
                        if tid:
                            self.schema.on_import(tid, ctx)
                            self.import_map[alias] = tid
                            if "." in mod_str:
                                self.import_map[mod_str] = tid
            elif node.type == ext.from_import_type:
                # from mod import a, b → cố resolve từng symbol; không được thì ghi nhớ để resolve sau
                mod_node = node.child_by_field_name(ext.module_name_field)
                if not mod_node:
                    continue
                mod_str    = self._text(mod_node)
                module_tid = self._resolve_module(mod_str)
                if module_tid:
                    self.schema.on_import(module_tid, ctx)
                for local_name, orig_name in self._get_from_imports(node):
                    sub_tid = self._resolve_module(f"{mod_str}.{orig_name}")
                    if sub_tid:
                        self.import_map[local_name] = sub_tid
                    elif module_tid:
                        self.from_import_map[local_name] = f"{module_tid}:{orig_name}"
                    else:
                        self.from_import_map[local_name] = None

    # Lấy danh sách (tên_local, tên_gốc) trong mệnh đề `from ... import ...`
    def _get_from_imports(self, from_stmt):
        ext, results, past_import = self.extractor, [], False
        for child in from_stmt.children:
            if child.type == ext.import_keyword_type:
                past_import = True; continue
            if not past_import:
                continue
            if child.type == ext.wildcard_import_type:   # from x import *  → bỏ qua
                break
            if child.type == ext.identifier_type:
                n = self._text(child); results.append((n, n))
            elif child.type == ext.import_as_names_type:
                for sub in child.children:
                    if sub.type == ext.identifier_type:
                        n = self._text(sub); results.append((n, n))
                    elif sub.type == ext.aliased_import_type:
                        r = self._resolve_aliased(sub)
                        if r: results.append(r)
            elif child.type == ext.aliased_import_type:
                r = self._resolve_aliased(child)
                if r: results.append(r)
        return results

    # `orig as alias` → (alias, orig)
    def _resolve_aliased(self, node):
        ext   = self.extractor
        orig  = node.child_by_field_name(ext.alias_name_field)
        alias = node.child_by_field_name(ext.alias_alias_field)
        if orig:
            o = self._text(orig)
            return (self._text(alias) if alias else o, o)
        return None

    # ── Pass 3: call references ────────────────────────────────────────────────

    # Phân loại mọi lời gọi thành kind (simple/attr/self_method/self_attr_method) → call_refs
    def _extract_calls(self, tree, ctx):
        ext = self.extractor
        for call_node in _caps(self._q_calls, tree.root_node).get("call", []):
            func = call_node.child_by_field_name(ext.call_function_field)
            if func is None:
                continue
            base = {
                "caller_id": self._scope_of(call_node),   # ai gọi
                "line":      call_node.start_point[0] + 1,
                "file":      self.rel_path,
            }
            if func.type == ext.identifier_type:
                # foo()  → simple (bỏ qua builtins)
                name = self._text(func)
                if name not in ext.builtins:
                    ctx.call_refs_out.append({**base, "kind": "simple", "name": name})

            elif func.type == ext.attribute_type:
                # obj.attr() → phân biệt self.x() / self.attr.x() / obj.x()
                obj  = func.child_by_field_name(ext.attribute_object_field)
                attr = func.child_by_field_name(ext.attribute_attr_field)
                if not (obj and attr):
                    continue
                attr_name = self._text(attr)
                if attr_name in ext.builtins:
                    continue
                obj_text = self._text(obj)
                if obj_text in ext.self_keywords:
                    # self.method() → resolve trong class hiện tại
                    ctx.call_refs_out.append({
                        **base, "kind": "self_method", "name": attr_name,
                        "class_id": self._class_of(call_node),
                    })
                elif obj.type == ext.attribute_type:
                    inner_obj  = obj.child_by_field_name(ext.attribute_object_field)
                    inner_attr = obj.child_by_field_name(ext.attribute_attr_field)
                    if inner_obj and inner_attr and self._text(inner_obj) in ext.self_keywords:
                        # self.attr.method() → cần biết kiểu của self.attr (xem Pass 4)
                        ctx.call_refs_out.append({
                            **base, "kind": "self_attr_method", "name": attr_name,
                            "attr": self._text(inner_attr),
                            "class_id": self._class_of(call_node),
                        })
                    else:
                        ctx.call_refs_out.append({**base, "kind": "attr", "name": attr_name, "obj": obj_text})
                else:
                    # obj.method() → resolve qua import_map của obj
                    ctx.call_refs_out.append({**base, "kind": "attr", "name": attr_name, "obj": obj_text})

    # ── Pass 4: self.attr = Type() assignments ────────────────────────────────

    # Bắt `self.attr = Type()` → ghi kiểu của thuộc tính, để resolve self.attr.method()
    def _extract_self_assigns(self, tree, ctx):
        ext = self.extractor
        for node in _caps(self._q_assigns, tree.root_node).get("assign", []):
            left  = node.child_by_field_name("left")
            right = node.child_by_field_name("right")
            if not (left and right and left.type == ext.attribute_type and right.type == ext.call_type):
                continue
            obj_node  = left.child_by_field_name(ext.attribute_object_field)
            attr_node = left.child_by_field_name(ext.attribute_attr_field)
            if not (obj_node and attr_node):
                continue
            if self._text(obj_node) not in ext.self_keywords:
                continue
            # Lấy tên kiểu ở vế phải (Type() hoặc mod.Type())
            func = right.child_by_field_name(ext.call_function_field)
            if not func:
                continue
            if func.type == ext.identifier_type:
                type_name = self._text(func)
            elif func.type == ext.attribute_type:
                a = func.child_by_field_name(ext.attribute_attr_field)
                type_name = self._text(a) if a else None
            else:
                continue
            if not type_name or type_name in ext.builtins:
                continue
            class_id = self._class_of(obj_node)
            if class_id:
                ctx.instance_attr_types_out.append({
                    "class_id": class_id,
                    "attr":     self._text(attr_node),
                    "type_name": type_name,
                })

    # ── Module path resolver ───────────────────────────────────────────────────

    # Tên module (kể cả relative `..pkg`) → đường dẫn file thật trong repo, hoặc None
    def _resolve_module(self, module):
        if module.startswith("."):
            # relative import: số dấu chấm = số cấp đi lên
            dots     = len(module) - len(module.lstrip("."))
            rel_part = module.lstrip(".")
            base_dir = os.path.dirname(self.rel_path)
            for _ in range(dots - 1):
                base_dir = os.path.dirname(base_dir)
            parts = (
                os.path.join(base_dir, rel_part.replace(".", os.sep)).replace("\\", "/")
                if rel_part else base_dir
            )
        else:
            parts = module.replace(".", "/")
        # Thử cả file.py lẫn package/__init__.py
        init_name = self.extractor.index_file_name
        for src_ext in self.extractor.source_extensions:
            for candidate in (f"{parts}{src_ext}", f"{parts}/{init_name}{src_ext}"):
                if os.path.exists(os.path.join(self.repo_path, candidate)):
                    return f"{self.base_commit}:{os.path.relpath(os.path.join(self.repo_path, candidate), self.repo_path).replace(chr(92), '/')}"
        return None

    # ── Scope builder ──────────────────────────────────────────────────────────

    # Từ node của file → 2 bảng: local_scope (tên top-level) & class_scopes (method theo class)
    def _build_scopes(self, nodes):
        local_scope, class_scopes = {}, {}
        for node in nodes:
            label   = node["labels"][0]
            if label == "Module":
                continue
            node_id = node["id"]
            name    = node["properties"].get("name", "")
            parts   = node_id[len(self.module_id):].lstrip(":").split(":")
            if len(parts) == 1:
                local_scope[name] = node_id
            elif len(parts) == 2 and label == "Function":
                class_id = f"{self.module_id}:{parts[0]}"
                class_scopes.setdefault(class_id, {})[name] = node_id
        return local_scope, class_scopes

    # ── Helpers ────────────────────────────────────────────────────────────────

    # Lấy text gốc của 1 node từ byte buffer
    def _text(self, node):
        return self._source[node.start_byte:node.end_byte].decode("utf-8", errors="replace")

    # Lấy tên lớp cơ sở từ node superclass (xử lý identifier / attribute / subscript)
    def _extract_base_name(self, node):
        ext = self.extractor
        if node.type == ext.identifier_type:
            return self._text(node)
        if node.type == ext.attribute_type:
            a = node.child_by_field_name(ext.attribute_attr_field)
            return self._text(a) if a else ""
        if node.type in ("subscript", "type"):
            child = node.child_by_field_name("value") or (node.children[0] if node.child_count else None)
            return self._extract_base_name(child) if child else ""
        return ""

    # ── Cross-file resolution — returns ONLY semantic (Calls, Inherits) edges ──

    # Sau khi parse hết file: gộp scope/import toàn repo → resolve thành cạnh Calls/Inherits
    @staticmethod
    def resolve_cross_file(all_results, schema):
        from collections import defaultdict
        # Tập id node toàn cục + các bảng tra theo module
        all_node_ids = set()
        all_node_ids.update(n["id"] for r in all_results for n in r["nodes"])
        fmap   = {r["module_id"]: r["from_import_map"] for r in all_results}
        lscope = {r["module_id"]: r["local_scope"]     for r in all_results}
        cscope = {r["module_id"]: r["class_scopes"]    for r in all_results}
        imap   = {r["module_id"]: r["import_map"]      for r in all_results}
        iat    = {r["module_id"]: r["instance_attr_types"] for r in all_results}

        # Build global method map: lowercase_method_name -> list of candidate node IDs
        global_method_map = defaultdict(list)
        for r in all_results:
            for node in r["nodes"]:
                if node["labels"][0] in ("Function", "Class"):
                    name = node["properties"].get("name", "")
                    if name:
                        global_method_map[name.lower()].append(node["id"])

        semantic_edges = []   # Calls + Inherits only

        # Inherit refs → cạnh Inherits (thử local scope → import → from-import)
        for r in all_results:
            mid   = r["module_id"]
            ls, im, fim = lscope.get(mid, {}), imap.get(mid, {}), fmap.get(mid, {})
            for ref in r["inherit_refs"]:
                cid, base = ref["class_id"], ref["base_name"]
                target = (
                    ls.get(base)
                    or im.get(base)
                    or (fim.get(base) if fim.get(base) in all_node_ids else None)
                )
                if target and target in all_node_ids:
                    semantic_edges.append({"type": schema.inherit_edge_type, "source": cid, "target": target})

        # Call refs → cạnh Calls (mỗi ref gọi _resolve_call; target có thể là list)
        for r in all_results:
            mid  = r["module_id"]
            ls   = lscope.get(mid, {})
            im   = imap.get(mid, {})
            fim  = fmap.get(mid, {})
            cs   = cscope.get(mid, {})
            iat_ = {e["class_id"]: e for e in iat.get(mid, [])}

            for ref in r["call_refs"]:
                target = ASTEngine._resolve_call(
                    ref, all_node_ids, ls, im, fim, cs, iat_, cs, lscope, imap, global_method_map
                )
                if target:
                    if isinstance(target, list):
                        for t in target:
                            semantic_edges.append({
                                "type": schema.call_edge_type,
                                "source": ref["caller_id"],
                                "target": t,
                                "line": ref.get("line"),
                            })
                    else:
                        semantic_edges.append({
                            "type": schema.call_edge_type,
                            "source": ref["caller_id"],
                            "target": target,
                            "line": ref.get("line"),
                        })
        return semantic_edges

    # Resolve 1 lời gọi → id node đích, theo từng kind; cuối cùng có fallback heuristic
    @staticmethod
    def _resolve_call(ref, all_ids, ls, im, fim, cs, iat, cscope, lscope, imap, global_method_map=None):
        kind = ref.get("kind", "simple")
        name = ref.get("name", "")

        if kind == "simple":
            # foo() → local scope / import / from-import
            resolved = ASTEngine._find_first(name, all_ids, ls, im, fim)
            if resolved:
                return resolved

        if kind == "self_method":
            # self.foo() → method cùng class
            class_id = ref.get("class_id")
            if class_id:
                target = cs.get(class_id, {}).get(name)
                if target and target in all_ids:
                    return target

        if kind == "self_attr_method":
            # self.attr.foo() → tra kiểu của self.attr (Pass 4) rồi tìm method trong class kiểu đó
            class_id = ref.get("class_id")
            attr     = ref.get("attr", "")
            if class_id and attr in iat:
                type_name    = iat[attr]["type_name"]
                target_class = ASTEngine._find_first(type_name, all_ids, ls, im, fim)
                if target_class:
                    t = cscope.get(target_class, {}).get(name)
                    if t and t in all_ids:
                        return t

        if kind == "attr":
            # obj.foo() → obj là module đã import → tìm trong scope module đó
            obj = ref.get("obj", "")
            module_tid = im.get(obj) or fim.get(obj)
            if module_tid:
                remote_ls = lscope.get(module_tid, {})
                t = remote_ls.get(name)
                if t and t in all_ids:
                    return t
                candidate = imap.get(module_tid, {}).get(name)
                if candidate and candidate in all_ids:
                    return candidate

        # Heuristic-based fallback: tên method hiếm (≤3 ứng viên, không phổ biến) → nối luôn
        if global_method_map and name:
            common_methods = {
                "get", "set", "run", "update", "delete", "clear", "close", "save", "load",
                "__init__", "__str__", "__repr__", "__call__", "setup", "teardown", "execute",
                "pop", "append", "extend", "insert", "remove", "add", "format", "keys", "values", "items"
            }
            if name not in common_methods:
                candidates = global_method_map.get(name.lower(), [])
                if 0 < len(candidates) <= 3:
                    valid_candidates = [c for c in candidates if c in all_ids]
                    if valid_candidates:
                        return valid_candidates

        return None

    # Tra tên lần lượt qua (local scope, import_map, from_import_map) → id hợp lệ đầu tiên
    @staticmethod
    def _find_first(name, all_ids, ls, im, fim):
        for source in (ls, im, fim):
            t = source.get(name)
            if t and t in all_ids:
                return t
        return None

### 1.6 Build & Search Pipeline
Three functions that form the core pipeline:
- `build_graph(commit)` — checkout, parse, embed (BGE-small), export JSON (disk-cached)
- `load_graph_indices(path)` — load JSON, build BM25 + vector + call-graph indices (memory-cached)
- `get_oracle(patch, nodes)` — map changed lines of the gold patch to the innermost Function/Class (ground truth)

In [8]:
import json
import numpy as np
from collections import deque, defaultdict
from pathlib import Path
from datetime import datetime, timezone
from git import Repo as _Repo
from rank_bm25 import BM25Okapi
import hashlib

# Đọc/ghi graph JSON: orjson nhanh hơn json chuẩn nhiều lần với file lớn; thiếu orjson thì dùng json.
# Không dùng json.dump khi ghi: json.dump chạy bộ mã hóa Python thuần, chậm với hàng triệu số embedding.
try:
    import orjson
    def read_graph_json(path):
        with open(path, "rb") as f:
            return orjson.loads(f.read())
    def write_graph_json(path, obj):
        with open(path, "wb") as f:
            f.write(orjson.dumps(obj))
except ImportError:
    def read_graph_json(path):
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    def write_graph_json(path, obj):
        with open(path, "w", encoding="utf-8") as f:
            f.write(json.dumps(obj, ensure_ascii=False))   # json.dumps dùng bộ mã hóa C

# ── Cache trong phiên: model / index đã build / embedding theo nội dung ───────
_MODEL_CACHE = {}
_INDEX_CACHE = {}
_EMB_CACHE   = {}

# Load model embedding 1 lần duy nhất cho mỗi model_id
def _get_model(model_id=_EMBED_MODEL_ID):
    if model_id not in _MODEL_CACHE:
        import torch
        from sentence_transformers import SentenceTransformer
        m = SentenceTransformer(model_id)
        if EMBED_FP16 and torch.cuda.is_available():
            m = m.half()                                  # float16 trên GPU: nhanh ~2 lần
        if not torch.cuda.is_available():
            print("⚠ Không có GPU: bước embed khi build graph sẽ chậm hơn nhiều (đổi runtime sang GPU)")
        _MODEL_CACHE[model_id] = m
    return _MODEL_CACHE[model_id]

# Load cross-encoder reranker 1 lần (tự chọn GPU nếu có; max 512 token/cặp)
def _get_ce(model_id=_CE_MODEL_ID):
    if model_id not in _MODEL_CACHE:
        from sentence_transformers import CrossEncoder
        _MODEL_CACHE[model_id] = CrossEncoder(model_id, max_length=512)
    return _MODEL_CACHE[model_id]

# Text dùng để embed 1 node code: 2000 ký tự đầu của source (fallback: label+name)
def _sig_doc_fn(node):
    src = node.get("source", "")
    return src[:2000] if src else f"{node.get('label','')} {node.get('name','')}"

# Embed có cache theo sha1(text): source giống nhau giữa các commit chỉ encode 1 lần
def encode_cached(texts, model, batch_size=64):
    """Embed texts with an in-session cache keyed by sha1(text).
    Source giống hệt giữa các commit chỉ encode 1 lần (~80-90% reuse trên cùng repo)."""
    if not texts:
        return np.zeros((0, model.get_sentence_embedding_dimension()), dtype=np.float32)
    keys = [hashlib.sha1(t.encode("utf-8")).hexdigest() for t in texts]
    # Tách phần đã có trong cache (out) và phần thiếu (miss) cần encode
    out, miss_i, miss_t = [None] * len(texts), [], []
    for i, k in enumerate(keys):
        v = _EMB_CACHE.get(k)
        if v is None:
            miss_i.append(i); miss_t.append(texts[i])
        else:
            out[i] = v
    # Chỉ encode phần thiếu rồi nạp ngược vào cache + vị trí tương ứng
    if miss_t:
        vecs = model.encode(miss_t, batch_size=batch_size,
                            normalize_embeddings=True, convert_to_numpy=True, show_progress_bar=True)
        for j, i in enumerate(miss_i):
            _EMB_CACHE[keys[i]] = vecs[j]
            out[i] = vecs[j]
    return np.vstack(out)

In [9]:
# ── build_graph(): orchestrator — build full graph cho 1 commit ──────────────
# Luồng 7 bước: cache → checkout → parse AST → resolve → flatten → doc → embed → export
import re
import time
from tqdm.auto import tqdm

def build_graph(commit, repo_path=REPO_PATH, output_dir=WORK_DIR, force=False,
                embed_model_id=_EMBED_MODEL_ID):
    """
    Checkout commit → parse AST + docs → embed → export JSON.
    Always builds the full graph (code nodes + Document/DocChunk nodes).
    """
    repo_name   = Path(repo_path).name
    short       = commit[:8]
    output_file = f"{output_dir}/{repo_name}_graph_{short}.json"

    # 0. Disk cache: đã có JSON đúng schema "simple+doc2" thì trả luôn, khỏi build lại
    #    (simple+doc2: lớp doc đọc thêm .txt và directive Python domain viết tay)
    if not force and Path(output_file).exists():
        try:
            # "meta" là khóa đầu tiên của JSON → chỉ đọc 4 KB đầu, không parse cả file
            with open(output_file, encoding="utf-8") as _f:
                _m = re.search(r'"schema":\s*"([^"]*)"', _f.read(4096))
            _schema = _m.group(1) if _m else ""
            if _schema == "simple+doc2":
                print(f"[{short}] disk cache hit → {output_file}", flush=True)
                return output_file
            print(f"[{short}] cached schema={_schema!r} — rebuilding with doc layer", flush=True)
        except Exception:
            pass

    # 1. Checkout
    _t0 = time.perf_counter()
    _repo = _Repo(repo_path)
    _repo.git.checkout(commit, force=True)   # force: /kaggle/working không giữ quyền file, git coi là thay đổi
    _t1 = time.perf_counter()

    # 2. Source files
    src_files = get_python_files(repo_path)

    # 3. AST parse — File-level Cache (Bỏ qua Tree-sitter cho 99% file không đổi)
    global _FILE_AST_CACHE
    if "_FILE_AST_CACHE" not in globals():
        _FILE_AST_CACHE = {}
    import hashlib

    results, n_cache, n_parse, n_fail = [], 0, 0, 0
    for rel in tqdm(src_files, desc=f"[{short}] AST", unit="file", leave=False):
        try:
            fpath = Path(repo_path) / rel
            content = fpath.read_bytes()
            fhash = (rel, hashlib.sha1(content).hexdigest())   # khóa có đường dẫn: file trùng nội dung ở chỗ khác không nhận nhầm đường dẫn

            if fhash in _FILE_AST_CACHE:
                old_short, cached_r = _FILE_AST_CACHE[fhash]
                if old_short == short:
                    results.append(cached_r)
                else:
                    # Đổi tên commit trên ID node bằng cách serialize siêu tốc
                    # (không import json tại đây — import trong hàm biến 'json'
                    #  thành local toàn hàm → UnboundLocalError ở chỗ dùng khác)
                    r_str = json.dumps(cached_r)
                    r_str = r_str.replace(f"{old_short}:", f"{short}:").replace(f'"{old_short}"', f'"{short}"')
                    results.append(json.loads(r_str))
                n_cache += 1
                continue

            eng = ASTEngine(str(fpath), repo_path, short, SCHEMA, EXTRACTOR)
            r = eng.parse()
            if r:
                _FILE_AST_CACHE[fhash] = (short, r)
                results.append(r)
                n_parse += 1
        except Exception:
            n_fail += 1
    # failed > 0 → file bị bỏ khỏi graph → oracle/recall thiếu mà không có dấu vết
    print(f"[{short}] AST: {len(results)}/{len(src_files)} files "
          f"(cache={n_cache} parsed={n_parse} failed={n_fail})", flush=True)

    # 4. Resolve cross-file edges (sem = Calls/Inherits, def = Defines/Imports)
    sem_edges = ASTEngine.resolve_cross_file(results, SCHEMA)
    def_edges = [e for r in results for e in r["definite_edges"]]

    # 5. Flatten code nodes / edges (dedupe node theo id)
    all_nodes = list({
        node["id"]: {
            "id":         node["id"],
            "label":      node["labels"][0],
            "name":       node["properties"].get("name", ""),
            "file":       node["properties"].get("file", ""),
            "start_line": node["properties"].get("start_line"),
            "end_line":   node["properties"].get("end_line"),
            "source":     node["properties"].get("source", ""),
            "community":  node["properties"].get("community"),
        }
        for r in results for node in r["nodes"]
    }.values())
    all_edges = [
        {"type": e["type"], "source": e["source"], "target": e["target"], "line": e.get("line")}
        for e in (def_edges + sem_edges)
    ]

    _t2 = time.perf_counter()

    # 5b. Doc parse → thêm node Document/DocChunk + File-level Cache
    global _FILE_DOC_CACHE
    if "_FILE_DOC_CACHE" not in globals():
        _FILE_DOC_CACHE = {}

    doc_files = get_doc_files(repo_path)
    doc_results = []
    for rel in tqdm(doc_files, desc=f"[{short}] docs", unit="file", leave=False):
        try:
            fpath = Path(repo_path) / rel
            content = fpath.read_bytes()
            fhash = (rel, hashlib.sha1(content).hexdigest())   # khóa có đường dẫn: file trùng nội dung ở chỗ khác không nhận nhầm đường dẫn
            if fhash in _FILE_DOC_CACHE:
                doc_results.append(_FILE_DOC_CACHE[fhash])
                continue

            r = DocExtractor(rel, repo_path).extract()
            if r:
                _FILE_DOC_CACHE[fhash] = r
                doc_results.append(r)
        except Exception:
            pass
    doc_nodes   = [n for r in doc_results for n in r["nodes"]]
    doc_edges   = [e for r in doc_results for e in r["edges"]]
    cross_edges = resolve_doc_links(doc_results, build_name_index(all_nodes))
    n_has_chunk = sum(1 for e in doc_edges   if e["type"] == "HasChunk")
    n_documents = sum(1 for e in cross_edges if e["type"] == "Documents")
    n_refs      = sum(1 for e in cross_edges if e["type"] == "References")
    n_pending   = sum(len(r["pending_links"]) for r in doc_results)
    # % resolved = sức khỏe cầu doc→code (đo trực tiếp hiệu quả build_name_index)
    print(f"[{short}] docs: {len(doc_nodes)} nodes | HasChunk={n_has_chunk}  "
          f"Documents={n_documents}/{n_pending} ({n_documents/max(1, n_pending):.0%} resolved)  "
          f"References={n_refs}", flush=True)
    all_nodes += doc_nodes
    all_edges += doc_edges + cross_edges

    _t3 = time.perf_counter()

    # 6. Embeddings — Function/Class: sig+docstring; DocChunk: heading+text
    _model    = _get_model(embed_model_id)
    vec_cands = [n for n in all_nodes if n["label"] in ("Function", "Class", "DocChunk")]
    embed_texts = [
        _sig_doc_fn(n) if n["label"] in ("Function", "Class")
        else (f"{n['heading']}\n{n['text']}" if n.get('heading') else n.get('text', ""))
        for n in vec_cands
    ]
    vecs = encode_cached(embed_texts, _model, batch_size=EMBED_BATCH)  # in-session cache
    # Làm tròn 5 chữ số: JSON nhỏ đi nhiều → ghi/đọc nhanh hơn; sai lệch cosine ~1e-5
    vecs_r = np.round(vecs.astype(np.float64), 5)   # float64: tolist() ra số ngắn (0.01235)
    id2emb = {vec_cands[i]["id"]: vecs_r[i].tolist() for i in range(len(vec_cands))}
    for node in all_nodes:
        node["embedding"] = id2emb.get(node["id"])

    _t4 = time.perf_counter()

    # 7. Export ra JSON (meta + nodes + edges) + dọn index cache cũ
    try:
        remote_url = _repo.remotes.origin.url
    except Exception:
        remote_url = repo_path

    graph = {
        "meta": {
            "repo": remote_url, "commit": short, "schema": "simple+doc2", "lang": "python",
            "doc_links": "v2",                   # cạnh Documents nối theo cách mới (xem resolve_doc_links)
            "built_at": datetime.now(timezone.utc).isoformat(),
            "node_count": len(all_nodes), "edge_count": len(all_edges),
            "embed_model": embed_model_id, "embed_dim": int(vecs.shape[1]),
        },
        "nodes": all_nodes, "edges": all_edges,
    }
    write_graph_json(output_file, graph)
    write_graph_summary(output_file, all_nodes, all_edges)   # file nhỏ cho oracle/thống kê

    _INDEX_CACHE.pop(output_file, None)

    size_mb = Path(output_file).stat().st_size / 1024 / 1024
    print(f"[{short}] → {output_file}  ({len(all_nodes)} nodes, {len(all_edges)} edges, {size_mb:.1f} MB) | "
          f"checkout={_t1-_t0:.1f}s parse={_t2-_t1:.1f}s doc={_t3-_t2:.1f}s "
          f"embed={_t4-_t3:.1f}s export={time.perf_counter()-_t4:.1f}s", flush=True)
    return output_file

In [10]:
import re
import time
from collections import Counter
from tqdm.auto import tqdm
_CAMEL_RE = re.compile(r'([A-Z])')
_ALPHANUM_RE = re.compile(r'[a-zA-Z0-9]+')
def _tokenize_code(txt):
    # Dùng regex đã pre-compile để tăng tốc tối đa
    return _ALPHANUM_RE.findall(_CAMEL_RE.sub(r' \1', txt).lower())

# ── _embed_query(): làm sạch query trước khi encode ──────────────────────────
# bge-small cắt input ở 512 token; issue dài kèm code block chiếm hết cửa sổ →
# bỏ code block, giữ ~2000 chars đầu (≈512 token) phần mô tả tự nhiên.
_MD_CODEBLOCK_RE = re.compile(r"```.*?```", re.S)
def _embed_query(q):
    return _MD_CODEBLOCK_RE.sub(" ", q)[:2000]

# ── File tóm tắt cạnh mỗi graph: node rút gọn (không embedding, không source) + thống kê ──
# Oracle và cell thống kê chỉ cần vài trường của node → đọc file nhỏ này thay vì parse cả graph JSON.
_LITE_KEYS = ("id", "label", "name", "file", "start_line", "end_line")

def graph_summary_path(output_file):
    return output_file.removesuffix(".json") + ".summary.json"

def write_graph_summary(output_file, nodes, edges):
    fl = [n["end_line"] - n["start_line"] + 1 for n in nodes
          if n["label"] == "Function" and n.get("start_line") and n.get("end_line")]
    summary = {
        "nodes": [{k: n[k] for k in _LITE_KEYS if k in n} for n in nodes],
        "stats": {"nodes": len(nodes), "edges": len(edges),
                  "labels": dict(Counter(n["label"] for n in nodes)),
                  "edge_types": dict(Counter(e["type"] for e in edges)),
                  "avg_func_loc": round(sum(fl) / len(fl), 1) if fl else 0},
    }
    write_graph_json(graph_summary_path(output_file), summary)

def load_graph_summary(output_file):
    """Đọc file tóm tắt; graph build trước khi có tính năng này thì tạo file tóm tắt 1 lần."""
    p = graph_summary_path(output_file)
    if not Path(p).exists():
        g = read_graph_json(output_file)
        write_graph_summary(output_file, g["nodes"], g["edges"])
    return read_graph_json(p)

# ── load_graph_nodes(): loader nhẹ — chỉ nodes rút gọn + map id, không build index ───
# Dùng để trích oracle mà không tốn chi phí parse cả graph và dựng index tìm kiếm.
def load_graph_nodes(output_file):
    """Lightweight loader — summary nodes + node_by_id only, no index built."""
    nodes = load_graph_summary(output_file)["nodes"]
    return {"nodes": nodes, "node_by_id": {n["id"]: n for n in nodes}}


# ── load_graph_indices(): nạp graph + dựng toàn bộ index truy hồi ────────────
def load_graph_indices(output_file):
    """
    Load graph JSON, build retrieval indices.

    Two search indices:
      search()      — BM25 + vector on AST nodes only (Function/Class/Module)
      search_full() — BM25 + vector on AST nodes + DocChunk nodes

    Two coverage traversals (pure BFS, no decay, no rerank, return ALL reachable nodes):
      hop_coverage_ast()  — seeds via search()      + BFS via AST edges only
      hop_coverage_full() — coverage AST ∪ node có doc_votes() (doc-as-signal)
    """
    # Memory cache: đã dựng index cho file này thì trả luôn (im lặng — bị gọi lặp)
    if output_file in _INDEX_CACHE:
        return _INDEX_CACHE[output_file]

    _stem = Path(output_file).stem
    _t0 = time.perf_counter()
    gdata = read_graph_json(output_file)
    _t_load = time.perf_counter()

    nodes          = gdata["nodes"]
    embed_model_id = gdata["meta"].get("embed_model", _EMBED_MODEL_ID)
    node_by_id     = {n["id"]: n for n in nodes}
    _model         = _get_model(embed_model_id)

    # ── AST-only search index ──────────────────────────────────────────────────
    # Corpus BM25 chỉ trên node code; thiếu source thì dùng label+name+file
    bm25_nodes = [n for n in nodes if n["label"] not in ("Document", "DocChunk")]
    corpus_ast = []
    for n in tqdm(bm25_nodes, desc=f"[{_stem}] tokenize AST", unit="node", leave=False):
        text = n.get("source", "")
        if not text or len(text.strip()) < 5:
            text = f"{n.get('label','')} {n.get('name','')} {n.get('file','')}"
        corpus_ast.append(_tokenize_code(text))
    _t_tok_ast = time.perf_counter()
    bm25_ast = BM25Okapi(corpus_ast)
    _t_bm25_ast = time.perf_counter()

    # Ma trận vector + map id→hàng cho cả index BM25 và vector
    vec_nodes  = [n for n in bm25_nodes if n.get("embedding") is not None]
    vec_matrix = np.array([n["embedding"] for n in vec_nodes])
    vi_of      = {nd["id"]: i for i, nd in enumerate(vec_nodes)}
    bi_of      = {nd["id"]: i for i, nd in enumerate(bm25_nodes)}
    _t_vec = time.perf_counter()

    # ── Full search index (AST nodes + DocChunk) ───────────────────────────────
    # Thay vì tách từ lại toàn bộ AST (rất chậm), ta tận dụng lại corpus_ast
    doc_nodes = [n for n in nodes if n["label"] == "DocChunk"]
    corpus_doc = []
    for n in tqdm(doc_nodes, desc=f"[{_stem}] tokenize doc", unit="chunk", leave=False):
        text = f"{n.get('heading', '')} {n.get('text', '')}".strip()
        if not text or len(text.strip()) < 5:
            text = f"{n.get('label','')} {n.get('name','')}"
        corpus_doc.append(_tokenize_code(text))

    full_nodes = bm25_nodes + doc_nodes
    corpus_full = corpus_ast + corpus_doc
    _t_tok_doc = time.perf_counter()
    bm25_full = BM25Okapi(corpus_full)
    _t_bm25_full = time.perf_counter()

    full_vec_nodes  = [n for n in full_nodes if n.get("embedding") is not None]
    full_vec_matrix = np.array([n["embedding"] for n in full_vec_nodes])
    fvi_of          = {nd["id"]: i for i, nd in enumerate(full_vec_nodes)}
    fbi_of          = {nd["id"]: i for i, nd in enumerate(full_nodes)}
    _t_fvec = time.perf_counter()

    # ── Adjacency lists (danh sách kề có trọng số) ─────────────────────────────
    _AST_TYPES     = {"Calls", "Inherits", "Defines", "Imports"}
    _BRIDGE_LABELS = {"DocChunk"}
    # Trọng số theo loại cạnh: ngữ nghĩa code cao, cấu trúc/hub thấp, cầu doc trung bình.
    # _hop_coverage bỏ qua trọng số (giữ tương thích); _hop_ranked dùng để cho điểm.
    _EDGE_W = {"Calls": 1.0, "Inherits": 0.9, "Defines": 0.5, "Imports": 0.4,
               "Documents": 0.8, "HasChunk": 0.5, "References": 0.5}
    # fwd = xuôi (source→target), bwd = ngược — BFS chỉ đi cạnh code (AST);
    # cạnh Documents gom vào doc2code làm bảng chỉ đường chunk → code node.
    fwd_ast,  bwd_ast  = defaultdict(list), defaultdict(list)
    doc2code = defaultdict(list)
    for edge in gdata["edges"]:
        w = _EDGE_W.get(edge["type"], 0.5)
        if edge["type"] in _AST_TYPES:
            fwd_ast[edge["source"]].append((edge["target"], w))
            bwd_ast[edge["target"]].append((edge["source"], w))
        elif edge["type"] == "Documents":
            doc2code[edge["source"]].append(edge["target"])
    _t_adj = time.perf_counter()

    # Tên hiển thị của node (Function/Class dùng name, DocChunk dùng heading)
    def _node_name(nd):
        return nd.get("name") or nd.get("heading", "")

    # Lấy chỉ số top-k điểm cao nhất (argpartition cho nhanh khi k nhỏ)
    def _topn(scores, k):
        k = min(k, len(scores))
        if k == len(scores): return np.argsort(scores)[::-1]
        idx = np.argpartition(scores, -k)[-k:]
        return idx[np.argsort(scores[idx])[::-1]]

    # ── _rrf(): Reciprocal Rank Fusion — gộp 2 bảng xếp hạng BM25 + Vector ──────
    # Node có mặt ở CẢ HAI list được cộng dồn hai số hạng → ưu tiên node vừa khớp
    # lexical (BM25) vừa liên quan ngữ nghĩa (Vector). Bất biến theo thang điểm.
    RRF_C = 60
    def _rrf(bm_order, bm_id, v_order, v_id, keep_label=None):
        bm_rank = {bm_id(i): r for r, i in enumerate(bm_order)}
        v_rank  = {v_id(i):  r for r, i in enumerate(v_order)}
        cand = set(bm_rank) | set(v_rank)
        if keep_label is not None:
            cand = {nid for nid in cand if node_by_id.get(nid, {}).get("label") == keep_label}
        scored = []
        for nid in cand:
            s = 0.0
            if nid in bm_rank: s += 1.0 / (RRF_C + bm_rank[nid])
            if nid in v_rank:  s += 1.0 / (RRF_C + v_rank[nid])
            scored.append((nid, s))
        scored.sort(key=lambda x: -x[1])
        return scored

    # ── search(): hybrid trên node code (BM25 + vector) ────────────────────────
    def search(query, n=5, method="hybrid", pool=50):
        """Hybrid search on AST nodes only."""
        q_emb, bm_sc, _ = _q_sig(query)          # encode + BM25 chỉ 1 lần / query (memo)
        v_sim = vec_matrix @ q_emb

        # method="bm25"/"vector": chỉ 1 tín hiệu
        if method == "bm25":
            return [
                {"id": bm25_nodes[i]["id"], "name": _node_name(bm25_nodes[i]),
                 "label": bm25_nodes[i]["label"], "score": round(float(bm_sc[i]), 4)}
                for i in _topn(bm_sc, n) if bm_sc[i] > 0
            ]
        if method == "vector":
            return [
                {"id": vec_nodes[i]["id"], "name": _node_name(vec_nodes[i]),
                 "label": vec_nodes[i]["label"], "score": round(float(v_sim[i]), 4)}
                for i in _topn(v_sim, n)
            ]

        # hybrid: gộp 2 bảng xếp hạng BM25 + Vector bằng RRF (ưu tiên node vào cả hai)
        k = min(pool, len(bm25_nodes))
        bm25_top_idx = _topn(bm_sc, k)
        vec_top_idx  = _topn(v_sim, min(k, len(vec_nodes)))
        ranked = _rrf(bm25_top_idx, lambda i: bm25_nodes[i]["id"],
                      vec_top_idx,  lambda i: vec_nodes[i]["id"])
        return [
            {"id": nid, "name": _node_name(node_by_id[nid]),
             "label": node_by_id[nid]["label"], "score": round(sc, 4)}
            for nid, sc in ranked[:n] if nid in node_by_id
        ]

    # ── search_full(): hybrid trên node code + DocChunk ────────────────────────
    def search_full(query, n=5):
        """Hybrid search on AST nodes + DocChunk nodes."""
        q_emb, _, bm_sc = _q_sig(query)          # dùng chung memo với search()/search_doc()
        v_sim = full_vec_matrix @ q_emb

        k = min(50, len(full_nodes))
        bm25_top_idx = _topn(bm_sc, k)
        vec_top_idx  = _topn(v_sim, min(k, len(full_vec_nodes)))
        ranked = _rrf(bm25_top_idx, lambda i: full_nodes[i]["id"],
                      vec_top_idx,  lambda i: full_vec_nodes[i]["id"])
        return [
            {"id": nid, "name": _node_name(node_by_id[nid]),
             "label": node_by_id[nid]["label"], "score": round(sc, 4)}
            for nid, sc in ranked[:n] if nid in node_by_id
        ]

    # ── search_doc(): xếp hạng TRỰC TIẾP trong tập DocChunk có cầu Documents ──
    # Chunk cạnh tranh với nhau (không với code) — hết nghẽn top-50 làm đói seed.
    _chunk_ids     = [n["id"] for n in doc_nodes if n["id"] in doc2code]
    _all_chunk_ids = [n["id"] for n in doc_nodes]
    _chunk_bi  = {n["id"]: len(bm25_nodes) + i for i, n in enumerate(doc_nodes)}

    def _search_chunks(query, ids, n):
        """Hybrid RRF (BM25 + vector) xếp hạng nội bộ trong tập chunk ids."""
        if not ids:
            return []
        q_emb, _, bm_full = _q_sig(query)
        bm = [float(bm_full[_chunk_bi[cid]]) for cid in ids]
        vs = [float(full_vec_matrix[fvi_of[cid]] @ q_emb) if cid in fvi_of else 0.0
              for cid in ids]
        idxs = range(len(ids))
        r_bm = {i: r for r, i in enumerate(sorted(idxs, key=lambda i: -bm[i]))}
        r_vs = {i: r for r, i in enumerate(sorted(idxs, key=lambda i: -vs[i]))}
        scored = sorted(
            ((cid, 1.0 / (RRF_C + r_bm[i]) + 1.0 / (RRF_C + r_vs[i]))
             for i, cid in enumerate(ids)),
            key=lambda x: -x[1])
        return [{"id": cid, "name": _node_name(node_by_id[cid]),
                 "label": "DocChunk", "score": round(sc, 4)}
                for cid, sc in scored[:n]]

    def search_doc(query, n=5):
        """Hybrid RRF xếp hạng nội bộ các DocChunk có cạnh Documents."""
        return _search_chunks(query, _chunk_ids, n)

    def search_doc_all(query, n=10):
        """Như search_doc nhưng trên MỌI DocChunk, kể cả chunk không có cạnh Documents."""
        return _search_chunks(query, _all_chunk_ids, n)

    # ── doc_votes(): chunk liên quan BỎ PHIẾU cho code node nó document ───────
    # Doc evidence vào RANKING (bảng doc-rank của RRF) thay vì lái traversal →
    # hub API không kéo cả vùng lân cận vào coverage như cơ chế doc-seed cũ.
    def doc_votes(query, n_doc=5, spill=0.5, max_fanout=20):
        votes = {}
        for ch in search_doc(query, n=n_doc):
            for tgt in doc2code.get(ch["id"], []):
                nd = node_by_id.get(tgt)
                if not nd or nd["label"] not in ("Function", "Class"):
                    continue
                v = ch["score"] * _EDGE_W["Documents"]
                if v > votes.get(tgt, 0.0):
                    votes[tgt] = v
                # lan 1 bước Calls (API được document → helper nó gọi), né hub
                nbrs = fwd_ast.get(tgt, [])
                if len(nbrs) <= max_fanout:
                    for nxt, _w in nbrs:
                        nd2 = node_by_id.get(nxt)
                        if nd2 and nd2["label"] in ("Function", "Class"):
                            nv = v * spill
                            if nv > votes.get(nxt, 0.0):
                                votes[nxt] = nv
        return votes

    # ── _hop_coverage(): BFS thuần từ seed, trả MỌI node Function/Class chạm tới ─
    def _hop_coverage(seeds_fn, fwd, bwd, n_seeds, depth):
        """Pure BFS from seeds — no decay, no rerank, returns ALL reachable Function/Class nodes."""
        seeds = seeds_fn(n_seeds)
        if not seeds: return []
        visited = {s["id"]: 0 for s in seeds}
        queue = deque((s["id"], 0) for s in seeds)
        # Lan tỏa theo cả cạnh xuôi và ngược tới độ sâu `depth`
        while queue:
            nid, d = queue.popleft()
            if d >= depth: continue
            for nxt, _ in fwd.get(nid, []) + bwd.get(nid, []):
                if nxt not in visited:
                    visited[nxt] = d + 1
                    queue.append((nxt, d + 1))
        # Bỏ Module/Document/DocChunk, chỉ trả Function/Class kèm số hop
        out = []
        for nid, hop in visited.items():
            nd = node_by_id.get(nid)
            if not nd or nd["label"] in ("Module", "Document", "DocChunk"): continue
            out.append({"id": nid, "name": _node_name(nd), "label": nd["label"],
                        "file": nd.get("file", ""), "hop": hop, "score": 0.0})
        return out

    # Coverage chỉ qua cạnh code (seed = search hybrid)
    def hop_coverage_ast_fn(query, n_seeds=5, depth=2):
        return _hop_coverage(lambda n: search(query, n=n, method="hybrid"),
                             fwd_ast, bwd_ast, n_seeds, depth)

    # Coverage Full = coverage AST ∪ node có doc-vote (vote KHÔNG kéo hàng xóm);
    # node chỉ-có-vote gán hop=0 (mức seed, không qua traversal).
    def hop_coverage_full_fn(query, n_seeds=5, depth=2, n_doc=5):
        cov = _hop_coverage(lambda n: search(query, n=n, method="hybrid"),
                            fwd_ast, bwd_ast, n_seeds, depth)
        seen = {r["id"] for r in cov}
        for nid in doc_votes(query, n_doc=n_doc):
            if nid not in seen:
                nd = node_by_id[nid]
                cov.append({"id": nid, "name": _node_name(nd), "label": nd["label"],
                            "file": nd.get("file", ""), "hop": 0, "score": 0.0})
        return cov

    # ── _q_sig(): memo tín hiệu query — encode + BM25 scan chỉ 1 lần / query ──
    _q_cache = {}
    def _q_sig(query):
        sig = _q_cache.get(query)
        if sig is None:
            q_emb = _model.encode([_embed_query(query)], normalize_embeddings=True,
                                  convert_to_numpy=True)[0]
            toks = _tokenize_code(query)
            sig = (q_emb, bm25_ast.get_scores(toks), bm25_full.get_scores(toks))
            _q_cache[query] = sig
        return sig

    # ── _ce_scores(): cross-encoder chấm (query, node) — memo theo query+node ─
    # Coverage giữa các config (depth/n_seeds) trùng nhau nhiều → mỗi node chỉ
    # chấm 1 lần/query dù matrix gọi hop ranking 12 lần/instance.
    _ce_q_cache = {}
    def _ce_scores(query, cand):
        cache = _ce_q_cache.setdefault(query, {})
        todo = [nid for nid in cand if nid not in cache]
        if todo:
            q = _embed_query(query)
            pairs = []
            for nid in todo:
                nd = node_by_id.get(nid, {})
                text = (nd.get("source")
                        or f"{nd.get('label','')} {nd.get('name','')} {nd.get('file','')}")[:4000]
                pairs.append((q, text))
            scores = _get_ce().predict(pairs, batch_size=64, show_progress_bar=False)
            for nid, s in zip(todo, scores):
                cache[nid] = float(s)
        return {nid: cache[nid] for nid in cand}

    # ── _hop_ranked(): graph SINH ứng viên, cross-encoder XẾP HẠNG ─────────────
    # CE chấm trực tiếp từng cặp trên MỘT thang điểm nên không còn gì để RRF
    # trộn — RRF chỉ còn trong baseline Hybrid và search_doc (sinh ứng viên doc).
    def _hop_ranked(seeds_fn, fwd, bwd, n_seeds, depth, query, votes=None):
        seeds = seeds_fn(n_seeds)
        if not seeds:
            return []
        # BFS 2 chiều thuần — chỉ để xác định tập reachable + số hop
        hopd = {s["id"]: 0 for s in seeds}
        queue = deque((s["id"], 0) for s in seeds)
        while queue:
            nid, d = queue.popleft()
            if d >= depth:
                continue
            for nxt, _w in fwd.get(nid, []) + bwd.get(nid, []):
                if nxt not in hopd:
                    hopd[nxt] = d + 1
                    queue.append((nxt, d + 1))
        # Candidates = Function/Class trong coverage ∪ node có doc-vote
        # (vote đi vào một mình, không kéo hàng xóm như seed BFS)
        votes = votes or {}
        cand = {nid for nid in hopd
                if node_by_id.get(nid, {}).get("label") in ("Function", "Class")}
        cand |= set(votes)
        cand = list(cand)
        if not cand:
            return []
        ce = _ce_scores(query, cand)
        out = [{"id": nid, "name": _node_name(node_by_id[nid]),
                "label": node_by_id[nid]["label"],
                "file": node_by_id[nid].get("file", ""),
                "hop": hopd.get(nid, 0), "score": round(ce[nid], 4)}
               for nid in cand]
        out.sort(key=lambda r: -r["score"])
        return out

    # AST-hop có xếp hạng: seed = search hybrid, đi qua cạnh code
    def hop_ast_ranked_fn(query, n_seeds=5, depth=2):
        return _hop_ranked(lambda n: search(query, n=n, method="hybrid"),
                           fwd_ast, bwd_ast, n_seeds, depth, query)

    # Full-hop = AST-hop (cùng seed, cùng BFS) + doc_votes MỞ RỘNG tập ứng viên —
    # chênh lệch recall so với AST-hop = đóng góp của lớp doc ở khâu sinh ứng viên.
    def hop_full_ranked_fn(query, n_seeds=5, depth=2, n_doc=5):
        return _hop_ranked(lambda n: search(query, n=n, method="hybrid"),
                           fwd_ast, bwd_ast, n_seeds, depth, query,
                           votes=doc_votes(query, n_doc=n_doc))

    # BFS đơn giản trả khoảng cách hop từ tập seed (dùng cho callers/callees)
    def _bfs(seeds, adj, depth):
        dist = {s: 0 for s in seeds}
        q = deque((s, 0) for s in seeds)
        while q:
            cur, d = q.popleft()
            if d >= depth: continue
            for nxt, _ in adj.get(cur, []):
                if nxt not in dist:
                    dist[nxt] = d + 1
                    q.append((nxt, d + 1))
        return dist

    # Người gọi (đi ngược) / bị gọi (đi xuôi) của 1 node trong đồ thị code
    def callers_fn(node_id, depth=2):
        return _bfs([node_id], bwd_ast, depth)

    def callees_fn(node_id, depth=2):
        return _bfs([node_id], fwd_ast, depth)

    # bridged=0 → Full-hop ≡ AST-hop, biết trước khi nhìn bảng matrix
    n_bridged = sum(1 for n in doc_nodes if n["id"] in doc2code)
    print(f"[{_stem}] indices: ast={len(bm25_nodes)} chunks={len(doc_nodes)} "
          f"(bridged={n_bridged}) vec={vec_matrix.shape} | {time.perf_counter()-_t0:.1f}s", flush=True)
    print(f"[{_stem}] index timing: load={_t_load-_t0:.1f}s "
          f"tok_ast={_t_tok_ast-_t_load:.1f}s bm25_ast={_t_bm25_ast-_t_tok_ast:.1f}s "
          f"vec={_t_vec-_t_bm25_ast:.1f}s tok_doc={_t_tok_doc-_t_vec:.1f}s "
          f"bm25_full={_t_bm25_full-_t_tok_doc:.1f}s vec_full={_t_fvec-_t_bm25_full:.1f}s "
          f"adj={_t_adj-_t_fvec:.1f}s", flush=True)

    # Gói toàn bộ hàm + dữ liệu vào dict kết quả, cache lại rồi trả về
    result = {
        "nodes": nodes, "node_by_id": node_by_id,
        "search": search, "search_full": search_full, "search_doc": search_doc, "search_doc_all": search_doc_all,
        "doc_votes": doc_votes,
        "doc2code": doc2code, "fwd_ast": fwd_ast,    # cạnh đã dựng sẵn, graph_edges() dùng lại
        "documented": {t for ts in doc2code.values() for t in ts},
                "hop_coverage_ast": hop_coverage_ast_fn,
        "hop_coverage_full": hop_coverage_full_fn,
        "hop_ast_ranked": hop_ast_ranked_fn,
        "hop_full_ranked": hop_full_ranked_fn,
        "callers": callers_fn, "callees": callees_fn,
    }
    while len(_INDEX_CACHE) >= INDEX_CACHE_MAX:          # giữ RAM ổn định khi chạy nhiều instance
        _INDEX_CACHE.pop(next(iter(_INDEX_CACHE)))
    _INDEX_CACHE[output_file] = result
    return result

In [11]:
import unidiff
from collections import defaultdict

# ── _changed_lines(): dòng ở bản GỐC bị đổi, theo full path, bỏ dòng context ─────────
# Dòng xóa → lấy đúng số dòng gốc. Dòng thêm → neo vào dòng gốc ngay trước vị trí chèn.
# File mới tạo không có ở commit gốc → tách riêng, không tính là gold.
# File đổi tên: unidiff `path` trả tên MỚI, nhưng dòng gốc thuộc file ở tên CŨ → dùng tên cũ (_src_path).
def _src_path(pf):
    s = pf.source_file or ""
    if s.startswith("a/"):
        s = s[2:]
    return pf.path if (pf.is_added_file or s in ("", "/dev/null")) else s

def _changed_lines(patch_text):
    out, added_files = {}, set()
    for pf in unidiff.PatchSet(patch_text):
        if pf.is_added_file:
            added_files.add(pf.path)
            continue
        lines = out.setdefault(_src_path(pf), set())
        for h in pf:
            last = None
            for ln in h:
                if ln.is_removed:
                    lines.add(ln.source_line_no)
                    last = ln.source_line_no
                elif ln.is_context:
                    last = ln.source_line_no
                elif ln.is_added:
                    lines.add(last if last is not None else h.source_start)
    return out, added_files

# ── _patch_changes(): như _changed_lines nhưng giữ riêng dòng xóa và các khối dòng thêm ─────────
# Khối = các dòng thêm liền nhau, cùng điểm chèn (dòng gốc ngay trước, dòng gốc ngay sau).
# Mỗi dòng trong khối = (độ thụt lề, nội dung); dòng trống có độ thụt lề None.
# Hunk chèn thuần "-L,0" nghĩa là chèn sau dòng L. renames = {tên cũ: tên mới} của file đổi tên.
def _patch_changes(patch_text):
    out, renames, added_files = {}, {}, set()
    for pf in unidiff.PatchSet(patch_text):
        if pf.is_added_file:
            added_files.add(pf.path)
            continue
        src = _src_path(pf)
        if src != pf.path:
            renames[src] = pf.path
        rec = out.setdefault(src, {"removed": set(), "inserts": []})
        for h in pf:
            hl, last, blk = list(h), None, None
            for i, ln in enumerate(hl):
                if not ln.is_added:
                    blk = None
                if ln.is_removed:
                    rec["removed"].add(ln.source_line_no)
                    last = ln.source_line_no
                elif ln.is_context:
                    last = ln.source_line_no
                elif ln.is_added:
                    if blk is None:
                        nxt = next((x.source_line_no for x in hl[i + 1:] if not x.is_added), None)
                        if h.source_length == 0:
                            prev = last if last is not None else h.source_start
                        else:
                            prev = last if last is not None else h.source_start - 1
                        blk = (prev, nxt if nxt is not None else prev + 1, [])
                        rec["inserts"].append(blk)
                    text = ln.value.rstrip("\n")
                    blk[2].append((len(text) - len(text.lstrip(" \t")) if text.strip() else None, text))
    return out, renames, added_files

# ── get_oracle(): mỗi dòng đổi → node Function/Class HẸP NHẤT chứa nó ───────────────
# Class chỉ là gold khi có dòng đổi nằm trong class nhưng ngoài mọi method.
# File chỉ đổi ở cấp module (import, hằng số), không dòng nào nằm trong Function/Class
# → gold là node Module của file đó (vd pytest-5227 chỉ sửa hằng số DEFAULT_LOG_FORMAT).
# Khoảng dòng của node tính từ decorator đầu tiên (deco_start, do _file_nodes_at gắn).
# Dòng thêm gán theo điểm chèn của khối: (1) khối nằm giữa thân node; (2) khối nối vào cuối thân node và mọi dòng
# từ đầu khối tới dòng đó đều thụt sâu hơn dòng def (gặp dòng thụt nông hơn = bắt đầu code mới); (3) decorator mới
# ngay trên dòng def, khi mọi dòng sau nó trong khối cũng là decorator. Dòng trống chỉ tính khi nằm trong thân một
# Function. Node không có thông tin thụt lề (graph cũ) → gán theo dòng trước như cũ.
# Kết quả có thêm "renames" = {tên cũ: tên mới} để nơi cần (cạnh history) đổi id sang tên mới.
def get_oracle(patch_text, graph_nodes):
    changed, renames, added_files = _patch_changes(patch_text)
    by_file = defaultdict(list)
    module_of = {n["name"]: n["id"] for n in graph_nodes if n["label"] == "Module"}   # name = path file
    for n in graph_nodes:
        if n["label"] in ("Function", "Class") and n.get("start_line") and n.get("end_line"):
            by_file[n["file"]].append(n)
    start = lambda n: n.get("deco_start") or n["start_line"]
    narrow = lambda c: min(c, key=lambda n: (n["end_line"] - start(n), n["id"]))
    gold, module_only = set(), set()
    for f, rec in changed.items():
        if not f.endswith(".py"):
            continue
        nodes, hit = by_file[f], False
        for L in rec["removed"]:
            inner = [n for n in nodes if start(n) <= L <= n["end_line"]]
            if inner:
                gold.add(narrow(inner)["id"])
                hit = True
        for a, b, blk in rec["inserts"]:
            if not (nodes and all("indent" in n for n in nodes)):
                cand = [n for n in nodes if start(n) <= a <= n["end_line"]] or \
                       [n for n in nodes if start(n) <= b <= n["end_line"]]
                if cand:
                    gold.add(narrow(cand)["id"])
                    hit = True
                continue
            inside = [n for n in nodes if start(n) <= a and b <= n["end_line"]]
            tail = [n for n in nodes if n["end_line"] == a]
            head = [n for n in nodes if start(n) == b]
            low = None                                   # thụt lề nhỏ nhất từ đầu khối tới dòng đang xét
            for i, (d, text) in enumerate(blk):
                if d is None:
                    cand = [n for n in inside if n["label"] == "Function"]
                else:
                    low = d if low is None else min(low, d)
                    cand = inside + [n for n in tail if low > n["indent"]]
                    if text.lstrip().startswith("@") and all(t.lstrip().startswith("@") for x, t in blk[i:] if x is not None):
                        cand += [n for n in head if d == n["indent"]]
                if cand:
                    gold.add(narrow(cand)["id"])
                    hit = True
        if (rec["removed"] or rec["inserts"]) and not hit:
            module_only.add(f)
            if f in module_of:
                gold.add(module_of[f])
    files_code  = {f for f in changed if f.endswith(".py")}
    graph_files = {n["file"] for n in graph_nodes if n.get("file")}
    return {"nodes": gold,
            "files_code": files_code,
            "added_files": {f for f in added_files if f.endswith(".py")},
            "unreachable": files_code - graph_files,
            "module_only": module_only,
            "renames": renames}

# File của 1 node: node Module không có trường "file", đường dẫn nằm ở "name"
def node_file(nd):
    return nd.get("file") or (nd.get("name", "") if nd.get("label") == "Module" else "")

def get_oracle_nodes(patch_text, graph_nodes):
    return get_oracle(patch_text, graph_nodes)["nodes"]

def get_oracle_files(patch_text):
    changed, _ = _changed_lines(patch_text)
    return {f for f in changed if f.endswith(".py")}

print("get_oracle() / get_oracle_nodes() / get_oracle_files() ready: line-level oracle")

get_oracle() / get_oracle_nodes() / get_oracle_files() ready: line-level oracle

In [12]:
# ── Xóa cache index để dùng ĐÚNG code search/index hiện tại ─────────────────────
# load_graph_indices() cache kết quả KÈM closure (search, doc_votes, ...) theo _INDEX_CACHE.
# Sau khi sửa cell load_graph_indices, chạy cell này để index được dựng lại từ code mới.
# (Không đụng _EMB_CACHE/_MODEL_CACHE → embedding không phải tính lại.)
_INDEX_CACHE.clear()
print(f"_INDEX_CACHE cleared ({len(_INDEX_CACHE)} entries) — indices sẽ build lại từ code hiện tại.")

_INDEX_CACHE cleared (0 entries) — indices sẽ build lại từ code hiện tại.

## 2. Build Test Data (SWE-bench)
Load SWE-bench Lite, keep the instances of the repos in `REPOS` (at most `MAX_PER_REPO` per repo), and clone each repo.

In [13]:
from datasets import load_dataset

# ── Nạp SWE-bench Lite, lọc các instance thuộc REPO đang xét ──────────────────
_swe_lite = load_dataset("princeton-nlp/SWE-bench_lite", split="test")
SWE_INSTANCES = [
    {
        "id":     row["instance_id"],
        "repo":   row["repo"],
        "commit": row["base_commit"],                    # commit để checkout
        "title":  row["instance_id"].split("__", 1)[-1],
        "text":   row["problem_statement"],              # dùng làm query truy hồi
        "patch":  row["patch"],                          # dùng để trích đáp án vàng
    }
    for row in _swe_lite
    if row["repo"] in REPOS
]

# Giới hạn số instance mỗi repo (MAX_PER_REPO): sắp theo sha1(instance_id) rồi lấy k đầu → mẫu cố định
import hashlib
_keep = set()
for _repo in REPOS:
    _ids = sorted((i["id"] for i in SWE_INSTANCES if i["repo"] == _repo),
                  key=lambda x: hashlib.sha1(x.encode()).hexdigest())
    _cap = MAX_PER_REPO.get(_repo, MAX_PER_REPO_DEFAULT)
    _keep.update(_ids if _cap is None else _ids[:_cap])
SWE_INSTANCES = [i for i in SWE_INSTANCES if i["id"] in _keep]      # giữ thứ tự của SWE-bench

# Chọn 1 instance theo INSTANCE_IDX (None → dùng HEAD, không checkout)
TARGET_COMMIT = SWE_INSTANCES[INSTANCE_IDX]["commit"] if INSTANCE_IDX is not None else None
TARGET_ID     = SWE_INSTANCES[INSTANCE_IDX]["id"]     if INSTANCE_IDX is not None else "HEAD"

from collections import Counter as _Counter
_by_repo = _Counter(i["repo"] for i in SWE_INSTANCES)
print(f"Total instances : {len(SWE_INSTANCES)}  ({dict(_by_repo)})")
print(f"Instance        : {TARGET_ID}")
print(f"Commit          : {TARGET_COMMIT[:8] if TARGET_COMMIT else 'HEAD'}")

README.md:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data/dev-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  120kB

data/dev-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.12MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating dev split:   0%|          | 0/23 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/300 [00:00<?, ? examples/s]

Total instances : 207  ({'django/django': 114, 'sphinx-doc/sphinx': 16, 'sympy/sympy': 77})
Instance        : django__django-10914
Commit          : e7fd69d0

In [14]:
import os
from pathlib import Path
from git import Repo, RemoteProgress
from tqdm.auto import tqdm

# Thanh tiến độ cho git clone (mỗi pha: counting → compressing → receiving → resolving)
class _CloneProgress(RemoteProgress):
    def __init__(self, name):
        super().__init__()
        self.bar = tqdm(desc=f"clone {name}", unit="obj")
    def update(self, op_code, cur_count, max_count=None, message=""):
        self.bar.total = int(max_count) if max_count else self.bar.total
        self.bar.n = int(cur_count)
        self.bar.refresh()

# ── Clone tất cả repo trong REPOS nếu chưa có trong WORK_DIR ──────────────────
for _r in REPOS:
    _p = repo_path_of(_r)
    if not Path(_p).exists():
        _prog = _CloneProgress(_r)
        Repo.clone_from(f"https://github.com/{_r}.git", _p, progress=_prog)
        _prog.bar.close()
print(f"{len(REPOS)} repo sẵn sàng: " + ", ".join(repo_path_of(r) for r in REPOS))

# Checkout commit của instance đã chọn (trên đúng repo của nó)
if INSTANCE_IDX is not None:
    _inst = SWE_INSTANCES[INSTANCE_IDX]
    repo = Repo(repo_path_of(_inst["repo"]))
    repo.git.checkout(_inst["commit"], force=True)   # force: thư mục làm việc không giữ quyền file
    BASE_COMMIT = repo.head.commit.hexsha[:8]
    OUTPUT_FILE = f"{_inst['repo'].split('/')[1]}_graph_{BASE_COMMIT}.json"
    print(f"Checked out : {BASE_COMMIT}  ({_inst['id']})")
    print(f"Output      : {OUTPUT_FILE}")

clone django/django: 0obj [00:00, ?obj/s]

clone sphinx-doc/sphinx: 0obj [00:00, ?obj/s]

clone sympy/sympy: 0obj [00:00, ?obj/s]

3 repo sẵn sàng: /tmp/repos/django, /tmp/repos/sphinx, /tmp/repos/sympy
Checked out : e7fd69d0  (django__django-10914)
Output      : django_graph_e7fd69d0.json

## 3. GPU check
Confirm the runtime has a GPU before building graphs. Graphs are built inside the single loop of cell `exp-run` (Section 4), which also prints graph statistics per repo.

In [15]:
# GPU / CUDA check - run before Build Graphs to confirm embeddings use the GPU
import torch

# ── In trạng thái CUDA và thông tin GPU (nếu có) ──────────────────────────────
print("CUDA available :", torch.cuda.is_available())
if torch.cuda.is_available():
    print("Device name    :", torch.cuda.get_device_name(0))
    print("CUDA version   :", torch.version.cuda)
    print("Total VRAM (GB):", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))
else:
    print("No GPU detected - embeddings run on CPU (slow).")
    print("Colab: Runtime -> Change runtime type -> Hardware accelerator -> GPU")

# ── Xác nhận model embedding thực sự đang nằm trên thiết bị nào ───────────────
# Which device will the embedding model actually use?
try:
    _m = _get_model()
    print("Embed model on :", next(_m.parameters()).device)
except NameError:
    print("(_get_model not defined yet - run the Globals cell first)")
except Exception as e:
    print("Model not loaded yet:", e)

CUDA available : True
Device name    : Tesla T4
CUDA version   : 12.8
Total VRAM (GB): 15.64

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  133MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Embed model on : cuda:0

## 4. Truy xuất có doc: các hàm dùng chung

Section này chỉ định nghĩa hàm, không chạy thí nghiệm. `doc_set()` tạo tập node do doc đưa vào theo từng nguồn: `vote` dùng `doc_votes`, `random` dùng chunk ngẫu nhiên làm đối chứng, `chunkvec` lấy node code có embedding gần các chunk doc đầu, `randvec` là đối chứng của `chunkvec`. Hậu tố `_ast` giữ cùng tập node nhưng sắp theo hạng AST sâu. `candidates()` dựng tập N ứng viên với m suất cho doc. `funnel_setup()` tính thông tin nêu tên gold cho từng instance. Section 5 dùng lại các hàm này. Phân tích nguyên nhân trên SWE-bench Lite đã chạy xong và được thay bằng Section 5 ở quy mô lớn.

In [16]:
# ── Hàm dùng chung cho truy xuất có doc: nguồn doc, tập ứng viên, đơn vị mức class, thông tin gold ──
import hashlib
import json
import random
import numpy as np
import pandas as pd
from collections import defaultdict

# Nguồn doc của doc_set(): vote (doc_votes), random (chunk ngẫu nhiên, đối chứng của vote), chunkvec (top chunk doc →
# node code có embedding gần nhất), randvec (như chunkvec với chunk ngẫu nhiên). Hậu tố _ast: sắp theo hạng AST sâu.
EXP_POOL     = 50                # nâng lên 100 nếu kiểm thử báo thiếu ứng viên
EXP_N_DOC    = 5                 # số chunk doc, giống doc_votes(n_doc=5)
EXP_DEEP     = 500               # độ sâu xếp hạng AST dùng để sắp node doc cho nguồn *_ast
SPILL_FANOUT = 20                # = max_fanout mặc định của doc_votes (cell load_graph_indices)
VEC_N_CHUNK   = 20               # chunkvec: số chunk doc đầu theo search_full (mọi chunk, không cần cạnh Documents)
VEC_PER_CHUNK = 5                # chunkvec: số node code gần nhất lấy cho mỗi chunk
_FC = ("Function", "Class")

# Cạnh lấy từ index đã dựng (không đọc lại JSON): d2c = chunk → [code] (cạnh Documents),
# fwd = node → [node] theo cạnh AST (fwd_ast bỏ trọng số). Trả bản sao để không sửa index.
def graph_edges(output_file):
    idx = load_graph_indices(output_file)
    d2c = defaultdict(list, idx["doc2code"])
    fwd = defaultdict(list, {s: [t for t, _w in lst] for s, lst in idx["fwd_ast"].items()})
    return d2c, fwd

# Lan 1 bước theo fwd, đúng quy tắc của doc_votes: bỏ node có hơn SPILL_FANOUT hàng xóm,
# chỉ giữ Function/Class. Giữ thứ tự: đích trực tiếp trước, node lan sau.
def spill_1hop(targets, fwd, nbi):
    out, seen = list(targets), set(targets)
    for t in targets:
        nbrs = fwd.get(t, [])
        if len(nbrs) > SPILL_FANOUT:
            continue
        for x in nbrs:
            if x not in seen and nbi.get(x, {}).get("label") in _FC:
                out.append(x)
                seen.add(x)
    return out

# Đối chứng của vote: EXP_N_DOC chunk chọn ngẫu nhiên (chỉ chunk có cạnh Documents,
# giống tập chunk mà search_doc xếp hạng)
def random_doc_chunks(d2c, seed):
    rng = random.Random(seed)
    chunks = sorted(d2c)
    return rng.sample(chunks, min(EXP_N_DOC, len(chunks)))

# Đích Function/Class của các chunk qua cạnh Documents, rồi lan 1 bước như doc_votes
def chunk_targets(chunks, nbi, d2c, fwd):
    direct = []
    for c in chunks:
        for t in d2c[c]:
            if nbi.get(t, {}).get("label") in _FC and t not in direct:
                direct.append(t)
    return spill_1hop(direct, fwd, nbi)

def top_doc_chunks(idx, q, n):
    """Top chunk doc theo search_full (mọi chunk, kể cả chunk không có cạnh Documents)."""
    return [r["id"] for r in idx["search_full"](q, n=200) if r["label"] == "DocChunk"][:n]

# Ma trận embedding của node Function/Class, dựng 1 lần cho graph đang xét (chỉ giữ 1 graph trong RAM)
_VEC_CACHE = {}
def _code_matrix(nbi):
    if _VEC_CACHE.get("nbi") is not nbi:
        code = [n for n, nd in nbi.items() if nd["label"] in _FC and nd.get("embedding") is not None]
        _VEC_CACHE.update(nbi=nbi, code=code,
                          M=np.asarray([nbi[n]["embedding"] for n in code], dtype=np.float32))
    return _VEC_CACHE["code"], _VEC_CACHE["M"]

def chunk_vec_reach(nbi, chunk_ids):
    """Mỗi chunk → VEC_PER_CHUNK node code có embedding gần nhất (không cần cạnh Documents)."""
    code, M = _code_matrix(nbi)
    out, seen = [], set()
    for c in chunk_ids:
        e = nbi[c].get("embedding")
        if e is None:
            continue
        sims = M @ np.asarray(e, dtype=np.float32)
        for i in np.argsort(-sims)[:VEC_PER_CHUNK]:
            if code[i] not in seen:
                out.append(code[i])
                seen.add(code[i])
    return out

# Đối chứng của chunkvec: VEC_N_CHUNK chunk chọn ngẫu nhiên trong mọi chunk có embedding
def random_vec_chunks(nbi, seed):
    rng = random.Random(seed + 1)
    chunks = sorted(n for n, nd in nbi.items() if nd["label"] == "DocChunk" and nd.get("embedding") is not None)
    return rng.sample(chunks, min(VEC_N_CHUNK, len(chunks)))

# Tập node doc đầy đủ của 1 nguồn (trước khi cắt m suất) + các chunk nó đã dùng.
# Không phụ thuộc N, m → nhớ theo (graph, nguồn, issue); scale_row xóa bộ nhớ đầu mỗi instance.
_DOC_MEMO = {}
def doc_set(idx, q, d2c, fwd, src, seed):
    key = (id(idx), src, q, seed)
    if key not in _DOC_MEMO:
        if len(_DOC_MEMO) > 64:
            _DOC_MEMO.clear()
        nbi, base = idx["node_by_id"], src.removesuffix("_ast")
        if base == "vote":
            chunks = [r["id"] for r in idx["search_doc"](q, n=EXP_N_DOC)]       # = các chunk doc_votes dùng
            votes = idx["doc_votes"](q, n_doc=EXP_N_DOC)                        # {node_id: điểm}
            doc = [nid for nid, _ in sorted(votes.items(), key=lambda x: (-x[1], x[0]))]
        elif base == "random":
            chunks = random_doc_chunks(d2c, seed)
            doc = chunk_targets(chunks, nbi, d2c, fwd)
        elif base == "chunkvec":
            chunks = top_doc_chunks(idx, q, VEC_N_CHUNK)
            doc = chunk_vec_reach(nbi, chunks)
        elif base == "randvec":
            chunks = random_vec_chunks(nbi, seed)
            doc = chunk_vec_reach(nbi, chunks)
        else:
            raise ValueError(src)
        if src.endswith("_ast"):
            deep = {r["id"]: i for i, r in enumerate(idx["search"](q, n=EXP_DEEP, method="hybrid", pool=EXP_DEEP))}
            doc = sorted(doc, key=lambda nid: deep.get(nid, len(deep)))   # ổn định: ngoài bảng giữ thứ tự cũ
        _DOC_MEMO[key] = (chunks, doc)
    return _DOC_MEMO[key]

# Đơn vị mức class (như LocAgent): method (kể cả hàm lồng trong method) → class chứa nó;
# hàm cấp module → chính nó; Class và Module → chính nó.
def unit_of(nid, nbi):
    if nbi[nid]["label"] != "Function":
        return nid
    cur = nid
    while True:
        p = cur.rsplit(":", 1)[0]
        lab = nbi.get(p, {}).get("label")
        if lab == "Class":
            return p
        if lab != "Function":
            return cur
        cur = p

# Tập ứng viên N node: N - m node AST đầu + tối đa m node mới từ doc; thiếu thì bù AST.
# Nguồn doc: xem EXP_SRCS và doc_set(). Hậu tố _ast: tập node doc sắp theo hạng trong xếp hạng AST sâu
# (EXP_DEEP) → doc chỉ làm bộ lọc, thứ tự do issue quyết định.
# Trả (cand, added); added là node doc thực sự chiếm suất. info (dict, tùy chọn) nhận thêm
# ast (xếp hạng AST), chunks (chunk doc đã dùng), doc (tập node doc đầy đủ) cho phễu thất bại.
def candidates(idx, q, N, m, d2c, fwd, doc_source="vote", seed=0, info=None):
    ast = [r["id"] for r in idx["search"](q, n=N + 50, method="hybrid", pool=EXP_POOL)
           if r["label"] in _FC]
    if info is not None:
        info["ast"] = ast
    if m == 0:
        return ast[:N], []
    chunks, doc = doc_set(idx, q, d2c, fwd, doc_source, seed)
    if info is not None:
        info.update(chunks=chunks, doc=doc)
    head = ast[:N - m]
    added = []
    for nid in doc:
        if len(added) == m:
            break
        if nid not in head and nid not in added:
            added.append(nid)
    cand = head + added
    for nid in ast[N - m:]:
        if len(cand) >= N:
            break
        if nid not in cand:
            cand.append(nid)
    return cand, added

def instance_seed(iid):
    return int(hashlib.sha1(iid.encode()).hexdigest()[:8], 16)

# ── funnel_setup(): thông tin nêu tên gold của 1 instance (scale_row dùng cho cột B0, B1, B2) ──
# B0 = doc (bất kỳ chunk nào) nêu tên gold: có cạnh Documents tới gold hoặc text chứa tên đầy đủ.
# B1 = chunk mà nguồn doc đã dùng nêu tên gold. B2 = tập node doc chứa gold.
# Chỉ xét gold Function/Class (tập ứng viên không chứa Module). Quy tắc nêu tên ở cell exp-docgroup-setup.
def funnel_setup(c):
    """Thông tin cấp instance: gold Function/Class, chunk nêu tên gold, nhóm doc tốt nhất, hạng gold trong AST sâu."""
    idx, nbi, gold, d2c = c["idx"], c["nbi"], c["gold"], c["d2c"]
    gfc = {g for g in gold if nbi[g]["label"] in _FC}
    documented = idx["documented"]
    ctext = {n["id"]: f"{n.get('heading', '')}\n{n.get('text') or ''}"
             for n in idx["nodes"] if n["label"] == "DocChunk"}
    names_gold, groups = set(), []
    for g in sorted(gfc):
        qual, pid = _gold_keys(g, nbi)
        rx = _mention_re(qual)
        named = {cid for cid, t in ctext.items() if rx.search(t)} | {cid for cid, ts in d2c.items() if g in ts}
        names_gold |= named
        if g in documented:
            groups.append("a")
        elif named:
            groups.append("b")
        elif pid and (pid in documented or any(_mention_re(nbi[pid]["name"]).search(t) for t in ctext.values())):
            groups.append("b-cls")
        else:
            groups.append("c")
    deep = [r["id"] for r in idx["search"](c["q"], n=EXP_DEEP, method="hybrid", pool=EXP_DEEP)
            if r["label"] in _FC]
    return {"gfc": gfc, "names_gold": names_gold,
            "group": min(groups, key=_GROUP_ORDER.index) if groups else None,
            "rank_deep": next((i + 1 for i, x in enumerate(deep) if x in gfc), None)}

print(f"Hàm truy xuất có doc sẵn sàng | pool={EXP_POOL} deep={EXP_DEEP} n_doc={EXP_N_DOC}")

Hàm truy xuất có doc sẵn sàng | pool=50 deep=500 n_doc=5

In [17]:
# ── Quy tắc nêu tên gold (funnel_setup và scale_row dùng) ─────────────────────────────────
# Nhóm của 1 gold: a = có cạnh Documents trỏ tới; b = không có cạnh nhưng tên đầy đủ có trong text doc;
# b-cls = method chỉ có class cha được doc trỏ tới hoặc nhắc tên; c = doc không nhắc tới.
# Tên đầy đủ = Class.method cho method, tên trần cho hàm/class cấp module, đường dẫn dạng chấm cho Module.
# Khớp theo ranh giới từ. Tên trần ngắn hoặc phổ biến có thể khớp nhầm.
import re

_GROUP_ORDER = ["a", "b", "b-cls", "c"]

def _mod_dotted(path):
    m = path.replace("/", ".").removesuffix(".py").removesuffix(".__init__")
    return m[4:] if m.startswith("src.") else m

def _gold_keys(g, nbi):
    """(tên đầy đủ, id class cha hoặc None) của 1 gold node. Id có dạng commit:file:Class:method."""
    nd = nbi[g]
    if nd["label"] == "Module":
        return _mod_dotted(nd["name"]), None
    pid = g.rsplit(":", 1)[0]
    if nbi.get(pid, {}).get("label") == "Class":
        return f"{nbi[pid]['name']}.{nd['name']}", pid
    return nd["name"], None

def _mention_re(key):
    return re.compile(r"(?<!\w)" + re.escape(key) + r"(?!\w)")

print("Quy tắc nêu tên gold sẵn sàng")

Quy tắc nêu tên gold sẵn sàng

## 5. Mở rộng lên SWE-bench đầy đủ (graph theo snapshot)

Section 4 chạy trên SWE-bench Lite. Ở quy mô đó, mỗi phép so chỉ có khoảng 15 cặp bất đồng, nên không đủ để kiểm định doc so với AST. Section này chạy trên SWE-bench đầy đủ cho các repo trong `SCALE_REPOS` (Django 850, sympy 386 instance).

Build một graph cho mỗi commit là quá tốn kém. Vì vậy, instance được chia theo version, rồi theo các khoảng `SNAPSHOT_BIN_DAYS` ngày. Mỗi khoảng dùng chung một graph, dựng tại base commit sớm nhất của khoảng. Do đó, graph không bao giờ chứa bản sửa của instance dùng nó. Gold được tính trên đúng base commit của instance, rồi đối chiếu sang graph của snapshot theo đường dẫn file và tên đầy đủ. Kiểm chứng trên máy cho thấy 99% gold đối chiếu được, và trên 114 instance Django Lite, kết quả xếp hạng BM25 trùng với graph theo commit ở 113/113 instance.

Doc được dùng theo hai cách. Cách thứ nhất là thiết kế m suất của Section 4 (`vote_ast`, `random_ast`, m = 10), dùng để lặp lại kết quả H1 ở quy mô lớn. Cách thứ hai là trộn xếp hạng: điểm của node bằng 1/(k + hạng AST) cộng w/(k + hạng trong tập doc). Cách trộn cho ra một xếp hạng đầy đủ, nên đo được hạng của gold trên mọi instance. Trọng số w được chọn trên các instance thuộc SWE-bench Lite (tập dev). Mọi kiểm định dùng các instance còn lại (tập test).

Cell `scale-fusion` chọn cách trộn doc trên tập dev (gồm bảo vệ phần đầu AST và lọc liên kết doc), rồi kiểm định một lần trên tập test ở ba mức hàm, class và file, kèm URisk và TRisk. Kết quả được ghi dần vào `SCALE_RESULTS` trong `WORK_DIR` (`/kaggle/working` trên Kaggle, `/content` trên Colab). Chạy lại cell `scale-run` sẽ tiếp tục từ chỗ dừng. Thực nghiệm v3 chỉ chạy trên django và sympy, xem mục 5b. Trên Kaggle, file chỉ được giữ lại sau khi session kết thúc nếu bạn Save Version.

In [18]:
# ── Section 5: nạp SWE-bench đầy đủ, clone repo, gán snapshot cho từng instance ───────────
import subprocess
from datasets import load_dataset
from git import Repo

_lite_ids = {row["instance_id"] for row in load_dataset("princeton-nlp/SWE-bench_Lite", split="test")}
SCALE_INSTANCES = [
    {"id": row["instance_id"], "repo": row["repo"], "commit": row["base_commit"], "version": row["version"],
     "text": row["problem_statement"], "patch": row["patch"], "lite": row["instance_id"] in _lite_ids}
    for row in load_dataset("princeton-nlp/SWE-bench", split="test") if row["repo"] in SCALE_REPOS
]

# Clone repo còn thiếu (cần đủ lịch sử: gold được tính trên base commit bằng git show)
for _r in SCALE_REPOS:
    _p = repo_path_of(_r)
    if not Path(_p).exists():
        _prog = _CloneProgress(_r)
        Repo.clone_from(f"https://github.com/{_r}.git", _p, progress=_prog)
        _prog.bar.close()

def _commit_times(repo_path, commits):
    """Thời điểm commit (Unix time) của nhiều commit; chia đợt để lệnh git không quá dài."""
    out = {}
    for i in range(0, len(commits), 200):
        res = subprocess.run(["git", "-C", repo_path, "show", "-s", "--format=%H %ct", *commits[i:i + 200]],
                             capture_output=True, text=True, check=True).stdout
        for line in res.splitlines():
            h, t = line.split()
            out[h] = int(t)
    return out

# Snapshot: trong mỗi (repo, version), chia instance theo thời gian thành các khoảng SNAPSHOT_BIN_DAYS ngày.
# Snapshot của một khoảng = base commit sớm nhất trong khoảng → không chứa bản sửa của instance nào dùng nó.
for _r in SCALE_REPOS:
    _insts = [i for i in SCALE_INSTANCES if i["repo"] == _r]
    _ct = _commit_times(repo_path_of(_r), sorted({i["commit"] for i in _insts}))
    for i in _insts:
        i["ct"] = _ct[i["commit"]]
    for v in {i["version"] for i in _insts}:
        start = snap = None
        for i in sorted((i for i in _insts if i["version"] == v), key=lambda i: (i["ct"], i["id"])):
            if start is None or i["ct"] - start > SNAPSHOT_BIN_DAYS * 86400:
                start, snap = i["ct"], i["commit"]
            i["snapshot"], i["snap_ct"] = snap, start

# Chạy theo thứ tự snapshot → mỗi graph chỉ build và dựng index 1 lần
SCALE_INSTANCES.sort(key=lambda i: (i["repo"], i["snap_ct"], i["snapshot"], i["id"]))
_sum = pd.DataFrame([{"Repo": i["repo"], "lite": i["lite"], "snapshot": i["snapshot"],
                      "Cách snapshot (ngày)": (i["ct"] - i["snap_ct"]) / 86400} for i in SCALE_INSTANCES])
display(_sum.groupby("Repo").agg(**{"Instance": ("lite", "size"), "Thuộc Lite (dev)": ("lite", "sum"),
                                     "Số graph": ("snapshot", "nunique"),
                                     "Cách snapshot trung vị": ("Cách snapshot (ngày)", "median"),
                                     "Cách snapshot tối đa": ("Cách snapshot (ngày)", "max")}).round(1))

README.md:   0%|          | 0.00/3.67k [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.89k [00:00<?, ?B/s]

data/dev-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 1.38MB

data/dev-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 12.1MB

data/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

data/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  107MB

data/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating dev split:   0%|          | 0/225 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2294 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/19008 [00:00<?, ? examples/s]

,Instance,Thuộc Lite (dev),Số graph,Cách snapshot trung vị,Cách snapshot tối đa
Repo,,,,,
django/django,850,114,40,27.7,60.0
sympy/sympy,386,77,46,19.9,60.0

### 5b. Thực nghiệm v3 (django, sympy): cạnh Documents mới và lớp history

Thực nghiệm này chỉ chạy trên django và sympy (`SCALE_REPOS`), và ghi kết quả vào file mới (`SCALE_RESULTS` bản v3). Kết quả của 12 repo ở lượt trước vẫn nằm trong `scale_rows_v2.jsonl`.

Cell `doc-links-v2` cập nhật cạnh `Documents` của các graph đã build theo cách nối mới. Cách nối mới thử tên kèm module của đoạn doc trước. Khi nhiều node cùng khớp, nó chỉ giữ node nằm trong module đó. Nếu vẫn mơ hồ, nó không nối. Cell chỉ thay cạnh, không parse lại code và không embed lại. Chunk doc trích lại phải trùng với graph cũ, nếu không cell sẽ dừng.

Cell `hist-build` thêm lớp history vào graph. Mỗi node `Commit` là một commit trên nhánh chính (`git log --first-parent`), so với cha thứ nhất. Cạnh `Modifies` nối commit với các hàm và lớp mà nó sửa, tính bằng đúng hàm tính gold. Dòng nằm ngoài mọi hàm và lớp được ghi thành cạnh tới `Module`; cạnh này chỉ được lưu, không bỏ phiếu. Graph của một snapshot chỉ nhận commit là tổ tiên của snapshot, nằm trong `HIST_YEARS` năm trước snapshot, và sửa từ 1 tới `HIST_MAX_TOUCH` hàm hoặc lớp có trong graph.

Issue truy vấn commit bằng BM25 và embedding của message, gộp bằng RRF. Top k commit bỏ phiếu cho các hàm và lớp mà chúng đã sửa (nguồn HIST). RAND_HIST dùng k commit chọn ngẫu nhiên trong cùng tập, làm đối chứng. Số commit k được chọn trên tập dev ở cell `scale-fusion`.

In [19]:
# ── Section 5b: cập nhật cạnh Documents của graph đã build theo cách nối mới (không build lại graph) ──────────
# Graph build trước khi có cách nối mới vẫn mang cạnh cũ. Cell này trích lại doc tại commit snapshot, nối lại cạnh
# bằng resolve_doc_links (cell PqDgRg_1mNuK), rồi chỉ thay cạnh Documents và References trong file graph.
# Node (kể cả chunk doc và embedding) giữ nguyên; chunk trích lại phải trùng id và text với graph cũ. Nếu không trùng
# (graph build bằng bộ nhớ đệm cũ, khóa chỉ là nội dung file, nên file doc đổi chỗ giữa các snapshot mang đường dẫn cũ),
# graph đó được build lại với force=True.
from tqdm.auto import tqdm

DOC_LINKS_VERSION = "v2"

def update_doc_links(snapshot, repo):
    rp = repo_path_of(repo)
    of = build_graph(snapshot, repo_path=rp)                  # graph đã có thì chỉ trả đường dẫn
    g = read_graph_json(of)
    if g["meta"].get("doc_links") == DOC_LINKS_VERSION:
        return of, None
    _Repo(rp).git.checkout(snapshot, force=True)
    docs = [r for r in (DocExtractor(rel, rp).extract() for rel in get_doc_files(rp)) if r]
    old_ch = {n["id"]: (n.get("heading"), n.get("text")) for n in g["nodes"] if n["label"] == "DocChunk"}
    new_ch = {n["id"]: (n.get("heading"), n.get("text")) for r in docs for n in r["nodes"] if n["label"] == "DocChunk"}
    if old_ch != new_ch:
        return build_graph(snapshot, repo_path=rp, force=True), "build lại"
    new_edges = resolve_doc_links(docs, build_name_index([n for n in g["nodes"] if n["label"] in ("Function", "Class")]))
    n_old = sum(e["type"] == "Documents" for e in g["edges"])
    g["edges"] = [e for e in g["edges"] if e["type"] not in ("Documents", "References")] + new_edges
    g["meta"]["doc_links"] = DOC_LINKS_VERSION
    g["meta"]["edge_count"] = len(g["edges"])
    write_graph_json(of, g)
    write_graph_summary(of, g["nodes"], g["edges"])
    _INDEX_CACHE.pop(of, None)
    return of, (n_old, sum(e["type"] == "Documents" for e in new_edges))

_dl = []
for _repo, _snap in tqdm(sorted({(i["repo"], i["snapshot"]) for i in SCALE_INSTANCES}), desc="cạnh Documents v2",
                         unit="graph"):
    _of, _st = update_doc_links(_snap, _repo)
    _up = isinstance(_st, tuple)
    _dl.append({"Repo": _repo, "Snapshot": _snap[:8], "Cập nhật": _up, "Build lại": _st == "build lại",
                "Cạnh Documents cũ": _st[0] if _up else None, "Cạnh Documents mới": _st[1] if _up else None})
_dl = pd.DataFrame(_dl)
print(f"{len(_dl)} graph: thay cạnh {_dl['Cập nhật'].sum()} | build lại {_dl['Build lại'].sum()} "
      f"(chunk cũ mang sai đường dẫn) | đã là {DOC_LINKS_VERSION} từ trước {(~_dl['Cập nhật'] & ~_dl['Build lại']).sum()}")
if _dl["Build lại"].any():
    print("Build lại:", ", ".join(f"{r.Repo} {r.Snapshot}" for r in _dl[_dl["Build lại"]].itertuples()))
if _dl["Cập nhật"].any():
    display(_dl[_dl["Cập nhật"]].groupby("Repo")[["Cạnh Documents cũ", "Cạnh Documents mới"]].sum())

cạnh Documents v2:   0%|          | 0/86 [00:00<?, ?graph/s]

[02cd16a7] disk cache hit → /kaggle/working/django_graph_02cd16a7.json
[0368d63a] disk cache hit → /kaggle/working/django_graph_0368d63a.json
[051d5944] disk cache hit → /kaggle/working/django_graph_051d5944.json
[1a78ef2b] disk cache hit → /kaggle/working/django_graph_1a78ef2b.json
[1d9d082a] disk cache hit → /kaggle/working/django_graph_1d9d082a.json
[2aaabe20] disk cache hit → /kaggle/working/django_graph_2aaabe20.json
[2fac0a18] disk cache hit → /kaggle/working/django_graph_2fac0a18.json
[32b7ffc2] disk cache hit → /kaggle/working/django_graph_32b7ffc2.json
[39f83765] disk cache hit → /kaggle/working/django_graph_39f83765.json
[419a7830] disk cache hit → /kaggle/working/django_graph_419a7830.json
[41e6b2a3] disk cache hit → /kaggle/working/django_graph_41e6b2a3.json
[44077985] disk cache hit → /kaggle/working/django_graph_44077985.json
[464a4c0c] disk cache hit → /kaggle/working/django_graph_464a4c0c.json
[475cffd1] disk cache hit → /kaggle/working/django_graph_475cffd1.json
[49ae7ce5] disk cache hit → /kaggle/working/django_graph_49ae7ce5.json
[511dfb33] disk cache hit → /kaggle/working/django_graph_511dfb33.json
[59942a66] disk cache hit → /kaggle/working/django_graph_59942a66.json
[60a7bd89] disk cache hit → /kaggle/working/django_graph_60a7bd89.json
[60dc957a] disk cache hit → /kaggle/working/django_graph_60dc957a.json
[65dfb06a] disk cache hit → /kaggle/working/django_graph_65dfb06a.json
[6f0b8c1c] disk cache hit → /kaggle/working/django_graph_6f0b8c1c.json
[7072bff1] disk cache hit → /kaggle/working/django_graph_7072bff1.json
[71ae1ab0] disk cache hit → /kaggle/working/django_graph_71ae1ab0.json
[76dfa834] disk cache hit → /kaggle/working/django_graph_76dfa834.json
[7c4f3965] disk cache hit → /kaggle/working/django_graph_7c4f3965.json
[838e432e] disk cache hit → /kaggle/working/django_graph_838e432e.json
[895f28f9] disk cache hit → /kaggle/working/django_graph_895f28f9.json
[98f6ada0] disk cache hit → /kaggle/working/django_graph_98f6ada0.json
[9dcfecb7] disk cache hit → /kaggle/working/django_graph_9dcfecb7.json
[a8bb4935] disk cache hit → /kaggle/working/django_graph_a8bb4935.json
[af1fa5e7] disk cache hit → /kaggle/working/django_graph_af1fa5e7.json
[b423873c] disk cache hit → /kaggle/working/django_graph_b423873c.json
[bef6f758] disk cache hit → /kaggle/working/django_graph_bef6f758.json
[cbe4d620] disk cache hit → /kaggle/working/django_graph_cbe4d620.json
[d08e6f55] disk cache hit → /kaggle/working/django_graph_d08e6f55.json
[d938b3b2] disk cache hit → /kaggle/working/django_graph_d938b3b2.json
[dd528cb2] disk cache hit → /kaggle/working/django_graph_dd528cb2.json
[df28ebd6] disk cache hit → /kaggle/working/django_graph_df28ebd6.json
[f9de1972] disk cache hit → /kaggle/working/django_graph_f9de1972.json
[fa4e963e] disk cache hit → /kaggle/working/django_graph_fa4e963e.json
[0410a6aa] disk cache hit → /kaggle/working/sympy_graph_0410a6aa.json
[0469e038] disk cache hit → /kaggle/working/sympy_graph_0469e038.json
[0cd4f13a] disk cache hit → /kaggle/working/sympy_graph_0cd4f13a.json
[205da797] disk cache hit → /kaggle/working/sympy_graph_205da797.json
[28d913d3] disk cache hit → /kaggle/working/sympy_graph_28d913d3.json
[356a73cd] disk cache hit → /kaggle/working/sympy_graph_356a73cd.json
[360290c4] disk cache hit → /kaggle/working/sympy_graph_360290c4.json
[3f8c8c23] disk cache hit → /kaggle/working/sympy_graph_3f8c8c23.json
[46921d28] disk cache hit → /kaggle/working/sympy_graph_46921d28.json
[479939f8] disk cache hit → /kaggle/working/sympy_graph_479939f8.json
[496e7761] disk cache hit → /kaggle/working/sympy_graph_496e7761.json
[514579c6] disk cache hit → /kaggle/working/sympy_graph_514579c6.json
[546e1079] disk cache hit → /kaggle/working/sympy_graph_546e1079.json
[6399a809] disk cache hit → /kaggle/working/sympy_graph_6399a809.json
[678217d5] disk cache hit → /kaggle/working/sympy_graph_678217d5.json
[68bd3627] disk cache hit → /kaggle/working/sympy_graph_68bd3627.json
[70381f28] disk cache hit → /kaggle/working/sympy_graph_70381f28.json
[748ce734] disk cache hit → /kaggle/working/sympy_graph_748ce734.json
[8ca4a683] disk cache hit → /kaggle/working/sympy_graph_8ca4a683.json
[8fc63c2d] disk cache hit → /kaggle/working/sympy_graph_8fc63c2d.json
[96c9c40b] disk cache hit → /kaggle/working/sympy_graph_96c9c40b.json
[9a6104ea] disk cache hit → /kaggle/working/sympy_graph_9a6104ea.json
[9bf73cc2] disk cache hit → /kaggle/working/sympy_graph_9bf73cc2.json
[9cbea134] disk cache hit → /kaggle/working/sympy_graph_9cbea134.json
[a3475b3f] disk cache hit → /kaggle/working/sympy_graph_a3475b3f.json
[a53c4ad9] disk cache hit → /kaggle/working/sympy_graph_a53c4ad9.json
[ae3d62ab] disk cache hit → /kaggle/working/sympy_graph_ae3d62ab.json
[b1078cd0] disk cache hit → /kaggle/working/sympy_graph_b1078cd0.json
[b3934e41] disk cache hit → /kaggle/working/sympy_graph_b3934e41.json
[b4777fdc] disk cache hit → /kaggle/working/sympy_graph_b4777fdc.json
[c4d6b3eb] disk cache hit → /kaggle/working/sympy_graph_c4d6b3eb.json
[c4e836cd] disk cache hit → /kaggle/working/sympy_graph_c4e836cd.json
[c50643a4] disk cache hit → /kaggle/working/sympy_graph_c50643a4.json
[cab3c1cb] disk cache hit → /kaggle/working/sympy_graph_cab3c1cb.json
[cdef6fcb] disk cache hit → /kaggle/working/sympy_graph_cdef6fcb.json
[cffd4e0f] disk cache hit → /kaggle/working/sympy_graph_cffd4e0f.json
[d250ff08] disk cache hit → /kaggle/working/sympy_graph_d250ff08.json
[d3b4158d] disk cache hit → /kaggle/working/sympy_graph_d3b4158d.json
[d5571e8b] disk cache hit → /kaggle/working/sympy_graph_d5571e8b.json
[d57aaf06] disk cache hit → /kaggle/working/sympy_graph_d57aaf06.json
[d7bddf4f] disk cache hit → /kaggle/working/sympy_graph_d7bddf4f.json
[e0ef1da1] disk cache hit → /kaggle/working/sympy_graph_e0ef1da1.json
[eb926a1d] disk cache hit → /kaggle/working/sympy_graph_eb926a1d.json
[ec0fe8c5] disk cache hit → /kaggle/working/sympy_graph_ec0fe8c5.json
[f5e96594] disk cache hit → /kaggle/working/sympy_graph_f5e96594.json
[fcefd30c] disk cache hit → /kaggle/working/sympy_graph_fcefd30c.json
86 graph: thay cạnh 0 | build lại 0 (chunk cũ mang sai đường dẫn) | đã là v2 từ trước 86

In [20]:
# ── Section 5: gold trên base commit → graph snapshot; 1 dòng kết quả cho mỗi instance ─────
import subprocess
import tempfile

SCALE_SRCS = ("vote_ast", "random_ast")      # nguồn doc (cùng tập node như Section 4, sắp theo hạng AST)
SCALE_NS   = (20, 40)                        # thiết kế m suất của Section 4, để lặp lại H1
SCALE_M    = 10
FUSE_K     = 60                              # hằng số RRF (như RRF_C trong load_graph_indices)
SCALE_TOPK = 100                             # số node đầu của xếp hạng AST được lưu id (đủ để tính chính xác
                                             # top 100 của mọi cách trộn ở cell scale-fusion, và để gộp cho judge)
DOC_ALL_N  = 10                              # số chunk doc đầu tìm trên MỌI chunk (kể cả chunk không có cạnh
                                             # Documents), lưu để judge chấm

def _key(nid):
    """Id node bỏ tiền tố snapshot: 'abcd1234:django/db/x.py:Cls:m' → 'django/db/x.py:Cls:m'."""
    return nid.split(":", 1)[1]

def _skip_rel(rel):
    """Cùng bộ lọc với get_python_files: file test/docs/example và file cấu hình không có trong graph."""
    parts = rel.split("/")
    return any(p in _SKIP_DIRS for p in parts[:-1]) or parts[-1] in _SKIP_FILES

def _file_nodes_at(repo_path, commit, rel):
    """Node (dạng phẳng như build_graph) của 1 file tại 1 commit; id bỏ tiền tố commit."""
    data = subprocess.run(["git", "-C", repo_path, "show", f"{commit}:{rel}"], capture_output=True).stdout
    if not data:
        return []
    with tempfile.TemporaryDirectory() as td:
        p = Path(td) / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
        r = ASTEngine(str(p), td, "X", SCHEMA, EXTRACTOR).parse()
    deco, stack = {}, [_parser.parse(data).root_node]       # dòng def/class → dòng decorator đầu tiên
    while stack:
        t = stack.pop()
        if t.type == "decorated_definition" and t.child_by_field_name("definition") is not None:
            deco[t.child_by_field_name("definition").start_point[0] + 1] = t.start_point[0] + 1
        stack.extend(t.children)
    lines = data.decode("utf-8", errors="replace").split("\n")
    out = []
    for n in (r or {}).get("nodes", []):
        pr = n["properties"]
        nd = {"id": n["id"].split(":", 1)[1], "label": n["labels"][0], "name": pr.get("name", ""),
              "file": pr.get("file", ""), "start_line": pr.get("start_line"), "end_line": pr.get("end_line")}
        s = nd["start_line"]
        if nd["label"] in ("Function", "Class") and s and s <= len(lines):
            nd["deco_start"] = deco.get(s, s)
            nd["indent"] = len(lines[s - 1]) - len(lines[s - 1].lstrip(" \t"))
        out.append(nd)
    return out

def get_oracle_snapshot(inst, idx):
    """Như get_oracle(), nhưng gold tính trên đúng base commit (parse riêng các file bị sửa), rồi đổi sang
    id của graph snapshot. Gold không có trong snapshot (hàm thêm sau snapshot) bị bỏ, đếm ở 'dropped'."""
    changed, _ = _changed_lines(inst["patch"])
    rp = repo_path_of(inst["repo"])
    nodes = [n for rel in changed if rel.endswith(".py") and not _skip_rel(rel)
             for n in _file_nodes_at(rp, inst["commit"], rel)]
    orc = get_oracle(inst["patch"], nodes)
    ids = set(idx["node_by_id"])
    mapped = {f"{inst['snapshot'][:8]}:{k}" for k in orc["nodes"]}
    orc["dropped"] = len(mapped - ids)
    orc["nodes"] = mapped & ids
    return orc

def scale_row(c):
    """Dữ liệu của 1 instance. Lưu đủ để tính hạng sau khi trộn với mọi trọng số w ở cell phân tích:
    ast_gold = hạng AST của từng gold Function/Class; doc_r_<src> = hạng AST của từng node doc theo thứ tự doc
    (0 = ngoài xếp hạng AST); doc_gold_<src> = vị trí trong tập doc của từng gold (None = không có).
    Bản v2 lưu thêm (id bỏ tiền tố snapshot): ast_ids/ast_scores = SCALE_TOPK node đầu của xếp hạng AST và điểm hybrid;
    doc_ids/doc_score/doc_direct/doc_ast_score_<src> = tập doc theo thứ tự, điểm doc (vote: điểm doc_votes; random:
    1 nếu có cạnh Documents trực tiếp, 0,5 nếu do lan 1 bước), có cạnh trực tiếp không, điểm hybrid AST của node đó;
    gold_ids; node_meta = {id: [đơn vị mức class, file]} cho mọi node đã lưu."""
    idx, nbi, d2c, fwd, q = c["idx"], c["nbi"], c["d2c"], c["fwd"], c["q"]
    seed = instance_seed(c["iid"])
    _DOC_MEMO.clear()
    fs = funnel_setup(c)
    gfc = sorted(fs["gfc"])
    deep_res = [r for r in idx["search"](q, n=EXP_DEEP, method="hybrid", pool=EXP_DEEP) if r["label"] in _FC]
    deep = [r["id"] for r in deep_res]
    deep_sc = {r["id"]: r["score"] for r in deep_res}
    rk = {x: i + 1 for i, x in enumerate(deep)}
    row = {"Gold": len(gfc), "Nhóm doc": fs["group"], "B0": int(fs["group"] in ("a", "b")),
           "ast_len": len(deep), "ast_gold": [rk.get(g) for g in gfc],
           "issue_names_gold": int(any(_mention_re(nbi[g]["name"]).search(q) for g in gfc)),
           "ast_ids": [_key(x) for x in deep[:SCALE_TOPK]], "ast_scores": [deep_sc[x] for x in deep[:SCALE_TOPK]],
           "gold_ids": [_key(g) for g in gfc]}
    keep = set(deep[:SCALE_TOPK]) | set(gfc)
    for s in SCALE_SRCS:
        chunks, doc = doc_set(idx, q, d2c, fwd, s, seed)
        pos = {x: j + 1 for j, x in enumerate(doc)}
        direct = {t for ch in chunks for t in d2c.get(ch, []) if nbi.get(t, {}).get("label") in _FC}
        if s.startswith("vote"):
            votes = idx["doc_votes"](q, n_doc=EXP_N_DOC)
            dscore = [votes.get(x, 0.0) for x in doc]
        else:
            dscore = [1.0 if x in direct else 0.5 for x in doc]
        row[f"doc_ids_{s}"] = [_key(x) for x in doc]
        row[f"doc_score_{s}"] = [round(v, 6) for v in dscore]
        row[f"doc_direct_{s}"] = [int(x in direct) for x in doc]
        row[f"doc_ast_score_{s}"] = [deep_sc.get(x, 0.0) for x in doc]
        keep |= set(doc)
        row[f"doc_r_{s}"] = [rk.get(x, 0) for x in doc]
        row[f"doc_gold_{s}"] = [pos.get(g) for g in gfc]
        row[f"B1_{s}"] = int(any(ch in fs["names_gold"] for ch in chunks))
        row[f"B2_{s}"] = int(bool(set(gfc) & set(pos)))
        row[f"doc_chunks_{s}"] = list(chunks)                  # chunk doc nguồn này đã dùng (judge chấm)
        row[f"doc_chunk_targets_{s}"] = [[_key(t) for t in d2c.get(ch, []) if nbi.get(t, {}).get("label") in _FC]
                                         for ch in chunks]     # đích cạnh Documents của từng chunk
    row["doc_chunks_all"] = [x["id"] for x in idx["search_doc_all"](q, n=DOC_ALL_N)]
    row["doc_chunks_all_targets"] = [[_key(t) for t in d2c.get(ch, []) if nbi.get(t, {}).get("label") in _FC]
                                     for ch in row["doc_chunks_all"]]   # [] = chunk không có cạnh Documents
    # Nguồn history (cell hist-build): top k commit theo issue (vote) và k commit ngẫu nhiên (random) bỏ phiếu cho
    # hàm/lớp chúng đã sửa. Lưu như nguồn doc (tên doc_*_<nguồn>) để scale-fusion dùng chung fused_list.
    hidx = c.get("hidx")
    if hidx is not None:
        top, rnd = hidx["search"](q, max(HIST_KS)), hidx["random"](seed, max(HIST_KS))
        row["hist_commits_vote"] = [[hidx["sha8"](i), round(sc, 6)] for i, sc in top]
        row["hist_commits_random"] = [hidx["sha8"](i) for i, _ in rnd]
        for k in HIST_KS:
            for base, units in (("vote", top[:k]), ("random", rnd[:k])):
                s = f"{base}_hist{k}_ast"
                votes = hidx["votes"](units)
                doc = [x for x, _ in sorted(votes.items(), key=lambda kv: (-kv[1], kv[0]))]
                doc = sorted(doc, key=lambda x: rk.get(x, len(deep) + 1))       # sắp theo hạng AST, như nguồn *_ast
                pos = {x: j + 1 for j, x in enumerate(doc)}
                row[f"doc_ids_{s}"] = [_key(x) for x in doc]
                row[f"doc_score_{s}"] = [round(votes[x], 6) for x in doc]
                row[f"doc_direct_{s}"] = [1] * len(doc)
                row[f"doc_ast_score_{s}"] = [deep_sc.get(x, 0.0) for x in doc]
                row[f"doc_r_{s}"] = [rk.get(x, 0) for x in doc]
                row[f"doc_gold_{s}"] = [pos.get(g) for g in gfc]
                row[f"B2_{s}"] = int(bool(set(gfc) & set(pos)))
                keep |= set(doc)
    # Thiết kế m suất của Section 4 (cùng hàm candidates)
    for N in SCALE_NS:
        row[f"Hit{N}_m0"] = int(bool(set(gfc) & set(candidates(idx, q, N, 0, d2c, fwd)[0])))
        for s in SCALE_SRCS:
            row[f"Hit{N}_{s}"] = int(bool(set(gfc) & set(candidates(idx, q, N, SCALE_M, d2c, fwd, s, seed)[0])))
    row["node_meta"] = {_key(x): [_key(unit_of(x, nbi)), node_file(nbi[x])] for x in keep}
    return row

def fused_rank(row, s, w):
    """Hạng tốt nhất của gold khi trộn: điểm = 1/(FUSE_K + hạng AST) + w/(FUSE_K + vị trí trong tập doc).
    Hòa điểm tính bất lợi cho gold. None = gold không có trong cả xếp hạng AST lẫn tập doc."""
    A = lambda r: 1.0 / (FUSE_K + r) if r else 0.0
    D = lambda j: w / (FUSE_K + j) if j else 0.0
    ast_g, gpos, doc_r = row["ast_gold"], row[f"doc_gold_{s}"], row[f"doc_r_{s}"]
    sc = max(A(r) + D(j) for r, j in zip(ast_g, gpos))
    if sc == 0:
        return None
    gold_ast, gold_doc = {r for r in ast_g if r}, {j for j in gpos if j}
    doc_ast = {r for r in doc_r if r}
    better = sum(1 for r in range(1, int(row["ast_len"]) + 1)
                 if r not in doc_ast and r not in gold_ast and A(r) >= sc)
    better += sum(1 for j, r in enumerate(doc_r, 1) if j not in gold_doc and A(r) + D(j) >= sc)
    return better + 1

print(f"Section 5 sẵn sàng | nguồn doc {SCALE_SRCS} | m suất: N={SCALE_NS}, m={SCALE_M} | RRF k={FUSE_K}")

Section 5 sẵn sàng | nguồn doc ('vote_ast', 'random_ast') | m suất: N=(20, 40), m=10 | RRF k=60

In [21]:
# ── Section 5b: lớp history của graph: node Commit, cạnh Modifies ──────────────────────────────────────────
# Mỗi repo build 1 lần → HIST_DIR/<repo>_history.jsonl (1 dòng / commit: sha, cha thứ nhất, thời điểm, message,
# touch = hàm/lớp bị sửa, touch_mod = file có dòng đổi ngoài mọi hàm/lớp → cạnh Modifies tới Module, không bỏ phiếu).
# Embedding message lưu ở <repo>_history.emb.npy. hist_index() dựng tập commit và hàm tìm kiếm cho 1 snapshot.
import random
import shutil
import subprocess

HIST_DIR       = Path(WORK_DIR) / "history"
HIST_INPUT     = None        # thư mục có sẵn file <repo>_history.jsonl (vd dataset Kaggle); None = build tại chỗ
HIST_YEARS     = 5           # chỉ dùng commit trong HIST_YEARS năm trước snapshot
HIST_MAX_TOUCH = 50          # bỏ commit sửa quá nhiều hàm/lớp (đổi tên hàng loạt, format lại code)
HIST_KS        = (5, 10, 20) # số commit lấy theo issue; chọn trên tập dev ở scale-fusion
HIST_DIR.mkdir(parents=True, exist_ok=True)
_YEAR = 365 * 86400
_SNAP_CT = {(i["repo"], i["snapshot"]): i["snap_ct"] for i in SCALE_INSTANCES}

def _git(rp, *args):
    return subprocess.run(["git", "-C", rp, *args], capture_output=True, text=True, encoding="utf-8",
                          errors="replace").stdout

def _hist_path(repo):
    return HIST_DIR / f"{repo.split('/')[1]}_history_v2.jsonl"   # v2: oracle đã sửa (đổi tên file, decorator, dòng thêm)

def build_history(repo):
    """Đơn vị = commit trên nhánh chính, từ snapshot mới nhất lùi tới HIST_YEARS năm trước snapshot cũ nhất."""
    rp = repo_path_of(repo)
    snaps = {s: t for (r, s), t in _SNAP_CT.items() if r == repo}
    tip, since = max(snaps, key=snaps.get), min(snaps.values()) - HIST_YEARS * _YEAR
    log = _git(rp, "log", "--first-parent", f"--since=@{since}", "--format=%H%x1f%P%x1f%ct%x1f%B%x1e", tip)
    units = []
    for rec in log.split("\x1e"):
        rec = rec.strip("\n")
        if rec:
            h, parents, ct, msg = rec.split("\x1f", 3)
            if parents:
                units.append((h, parents.split()[0], int(ct), msg.strip(), len(parents.split()) > 1))
    with open(_hist_path(repo), "w", encoding="utf-8") as f:
        for h, p, ct, msg, merge in tqdm(units, desc=f"history {repo}", unit="commit"):
            diff = _git(rp, "diff", "-U0", p, h, "--", "*.py")
            changed, _ = _changed_lines(diff) if diff else ({}, set())
            nodes, mods = [], set()
            for rel, lines in changed.items():
                if not rel.endswith(".py") or _skip_rel(rel):
                    continue
                fn = _file_nodes_at(rp, p, rel)                    # node của file tại commit cha, như khi tính gold
                nodes += fn
                spans = [(n["start_line"], n["end_line"]) for n in fn if n["label"] in _FC and n.get("start_line")]
                if any(not any(a <= L <= b for a, b in spans) for L in lines):
                    mods.add(rel)
            lab = {n["id"]: n["label"] for n in nodes}
            orc = get_oracle(diff, nodes) if nodes else {"nodes": set(), "renames": {}}
            ren = orc["renames"]                               # file đổi tên: id theo tên mới (khớp snapshot sau)
            touch = sorted(ren[k.split(":", 1)[0]] + ":" + k.split(":", 1)[1] if k.split(":", 1)[0] in ren else k
                           for k in orc["nodes"] if lab.get(k) in _FC)
            f.write(json.dumps({"h": h, "p": p, "t": ct, "merge": merge, "msg": msg[:2000], "touch": touch,
                                "touch_mod": sorted(mods)}, ensure_ascii=False) + "\n")

def load_history(repo):
    p = _hist_path(repo)
    if not p.exists() and HIST_INPUT and (Path(HIST_INPUT) / p.name).exists():
        shutil.copy(Path(HIST_INPUT) / p.name, p)
    if not p.exists():
        build_history(repo)
    units = [json.loads(l) for l in open(p, encoding="utf-8") if l.strip()]
    ep = p.with_suffix(".emb.npy")
    emb = np.load(ep) if ep.exists() else None
    if emb is None or len(emb) != len(units):
        emb = _get_model(_EMBED_MODEL_ID).encode([u["msg"] for u in units], batch_size=EMBED_BATCH,
                                                 normalize_embeddings=True, convert_to_numpy=True,
                                                 show_progress_bar=True).astype(np.float32)
        np.save(ep, emb)
    return {"units": units, "emb": emb, "toks": [_tokenize_code(u["msg"]) for u in units]}

def hist_index(repo, snapshot, idx):
    """Tập commit của 1 snapshot: tổ tiên của snapshot, trong HIST_YEARS năm, sửa 1..HIST_MAX_TOUCH hàm/lớp có trong
    graph. search(q, n) = top n commit (RRF của BM25 và embedding message); votes = điểm cao nhất của commit đã sửa
    mỗi node; random(seed, n) = n commit ngẫu nhiên trong cùng tập (đối chứng)."""
    H, s8, nbi = HIST[repo], snapshot[:8], idx["node_by_id"]
    anc = set(_git(repo_path_of(repo), "rev-list", snapshot).split())
    t0 = _SNAP_CT[(repo, snapshot)] - HIST_YEARS * _YEAR
    sel, touch = [], {}
    for i, u in enumerate(H["units"]):
        if u["h"] in anc and u["t"] >= t0:
            tt = [f"{s8}:{k}" for k in u["touch"] if nbi.get(f"{s8}:{k}", {}).get("label") in _FC]
            if 1 <= len(tt) <= HIST_MAX_TOUCH:
                sel.append(i)
                touch[i] = tt
    bm = BM25Okapi([H["toks"][i] for i in sel]) if sel else None
    E = H["emb"][sel] if sel else None
    memo = {}
    def _rank(x):
        r = np.empty(len(x)); r[np.argsort(-x, kind="stable")] = np.arange(len(x)); return r
    def search(q, n):
        if not sel:
            return []
        if q not in memo:
            qe = _get_model(_EMBED_MODEL_ID).encode([_embed_query(q)], normalize_embeddings=True, convert_to_numpy=True)[0]
            sc = 1.0 / (60 + _rank(bm.get_scores(_tokenize_code(q)))) + 1.0 / (60 + _rank(E @ qe))
            memo[q] = [(sel[j], float(sc[j])) for j in np.argsort(-sc, kind="stable")[:max(HIST_KS)]]
        return memo[q][:n]
    def votes(units):
        v = {}
        for i, sc in units:
            for t in touch[i]:
                v[t] = max(v.get(t, 0.0), sc)
        return v
    def rand(seed, n):
        return [(i, 1.0) for i in random.Random(seed + 2).sample(sel, min(n, len(sel)))]
    return {"search": search, "votes": votes, "random": rand, "n": len(sel),
            "sha8": lambda i: H["units"][i]["h"][:8]}

HIST = {}
for _repo in SCALE_REPOS:
    HIST[_repo] = load_history(_repo)
    _u = HIST[_repo]["units"]
    print(f"{_repo}: {len(_u)} commit trên nhánh chính | sửa ≥ 1 hàm/lớp: {sum(bool(u['touch']) for u in _u)} | "
          f"chỉ đổi ngoài hàm/lớp: {sum(bool(u['touch_mod']) and not u['touch'] for u in _u)}")

history django/django:   0%|          | 0/22111 [00:00<?, ?commit/s]

Batches:   0%|          | 0/173 [00:00<?, ?it/s]

django/django: 22111 commit trên nhánh chính | sửa ≥ 1 hàm/lớp: 10736 | chỉ đổi ngoài hàm/lớp: 851

history sympy/sympy:   0%|          | 0/8141 [00:00<?, ?commit/s]

Batches:   0%|          | 0/64 [00:00<?, ?it/s]

sympy/sympy: 8141 commit trên nhánh chính | sửa ≥ 1 hàm/lớp: 6224 | chỉ đổi ngoài hàm/lớp: 520

In [22]:
%%v3
# ── Section 5: một lượt qua mọi instance, ghi dần vào SCALE_RESULTS (chạy lại thì tiếp tục) ──
import time
from tqdm.auto import tqdm

_done = set()
if Path(SCALE_RESULTS).exists():
    with open(SCALE_RESULTS, encoding="utf-8") as f:
        _done = {json.loads(l)["Instance"] for l in f if l.strip()}
_todo = [i for i in SCALE_INSTANCES if i["id"] not in _done]
print(f"Đã có {len(_done)} instance trong {SCALE_RESULTS} | còn {len(_todo)}")

_t0, _cur = time.perf_counter(), None
_pbar = tqdm(_todo, desc="Section 5", unit="inst")
for inst in _pbar:
    iid = inst["id"].split("__", 1)[-1]
    _pbar.set_postfix_str(iid)
    if _cur != (inst["repo"], inst["snapshot"]):              # snapshot mới: build (nếu thiếu) + dựng index 1 lần
        _cur = (inst["repo"], inst["snapshot"])
        of = build_graph(inst["snapshot"], repo_path=repo_path_of(inst["repo"]))
        idx = load_graph_indices(of)
        d2c, fwd = graph_edges(of)
        hidx = hist_index(inst["repo"], inst["snapshot"], idx)
    orc = get_oracle_snapshot(inst, idx)
    row = {"Instance": inst["id"], "Repo": inst["repo"], "version": inst["version"],
           "snapshot": inst["snapshot"][:8], "lite": inst["lite"], "gold_dropped": orc["dropped"]}
    if not any(idx["node_by_id"][g]["label"] in _FC for g in orc["nodes"]):
        row["skip"] = "không có gold Function/Class trong graph snapshot"
    else:
        c = {"inst": inst, "iid": iid, "idx": idx, "nbi": idx["node_by_id"], "orc": orc,
             "gold": orc["nodes"], "q": inst["text"], "d2c": d2c, "fwd": fwd, "hidx": hidx}
        row.update(scale_row(c))
    with open(SCALE_RESULTS, "a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")
print(f"Xong {len(_todo)} instance trong {time.perf_counter() - _t0:.0f}s → {SCALE_RESULTS}")

Bỏ qua cell của v3 (RUN_V3 = False)

In [23]:
%%v3
# ── Section 5: phân tích ─────────────────────────────────────────────────────────────────
# Nạp kết quả, chia tập dev (instance thuộc SWE-bench Lite) và tập test, định nghĩa hàm kiểm định dùng chung.
# Bảng của cell này: thiết kế m suất (lặp lại H1 của Section 4) và đối chiếu Hit chỉ AST với graph theo commit.
# Việc chọn cách trộn doc và kiểm định H1, H2, H3 nằm ở cell scale-fusion. Hiệu chỉnh Holm trong từng bảng và từng repo.
from scipy.stats import binomtest, wilcoxon
pd.set_option("display.max_rows", 500)

def holm(p):
    p = np.asarray(p, dtype=float)
    out, run = np.empty(len(p)), 0.0
    for k, i in enumerate(np.argsort(p)):
        run = max(run, min(1.0, (len(p) - k) * p[i]))
        out[i] = run
    return out.round(4)

def mcnemar(a, b):
    up, down = int(((a == 1) & (b == 0)).sum()), int(((a == 0) & (b == 1)).sum())
    return up, down, (binomtest(up, up + down, 0.5).pvalue if up + down else 1.0)

with open(SCALE_RESULTS, encoding="utf-8") as f:
    _all = pd.DataFrame([json.loads(l) for l in f if l.strip()])
_ok = _all["skip"].isna() if "skip" in _all else pd.Series(True, index=_all.index)
sdf = _all[_ok].reset_index(drop=True)
print("Số instance:")
display(_all.assign(dùng=_ok).groupby("Repo").agg(**{"Tổng": ("Instance", "size"), "Dùng": ("dùng", "sum"),
        "Dev (Lite)": ("lite", "sum"), "Gold bị bỏ (không có trong snapshot)": ("gold_dropped", "sum")}))

# Kiểm tra: w = 0 → hạng sau khi trộn = hạng AST tốt nhất của gold
sdf["rank_ast"] = [min([x for x in r if x], default=None) for r in sdf["ast_gold"]]
for _, r in sdf.iterrows():
    _fr = fused_rank(r, "vote_ast", 0.0)
    assert (_fr is None and pd.isna(r["rank_ast"])) or _fr == r["rank_ast"], r["Instance"]

KS       = (1, 5, 10, 20, 40)
RANK_CAP = 1000                                    # gold ngoài mọi xếp hạng tính là hạng 1000 khi so hạng

_hit  = lambda col, k: col.map(lambda x: int(not pd.isna(x) and x <= k))
_mrr  = lambda col: col.map(lambda x: 0.0 if pd.isna(x) else 1.0 / x).mean()
_lrk  = lambda col: np.log(col.fillna(RANK_CAP).clip(upper=RANK_CAP).astype(float))
dev, test = sdf[sdf["lite"]], sdf[~sdf["lite"]]

def compare_ranks(df, a, b, label):
    """So 2 cột hạng theo cặp: Hit@k (McNemar) và hạng (Wilcoxon trên log hạng). Holm trong từng repo."""
    rows = []
    for repo, g in df.groupby("Repo"):
        rr = []
        for k in KS:
            up, down, p = mcnemar(_hit(g[a], k), _hit(g[b], k))
            rr.append({"Repo": repo, "So sánh": label, "Chỉ số": f"Hit@{k}",
                       a: round(_hit(g[a], k).mean(), 3), b: round(_hit(g[b], k).mean(), 3),
                       "Tốt hơn": up, "Kém hơn": down, "p": p})
        da, db = _lrk(g[a]), _lrk(g[b])
        better, worse = int((da < db).sum()), int((da > db).sum())
        p = wilcoxon(da, db).pvalue if better + worse else 1.0
        rr.append({"Repo": repo, "So sánh": label, "Chỉ số": "Hạng (Wilcoxon)",
                   a: round(_mrr(g[a]), 3), b: round(_mrr(g[b]), 3), "Tốt hơn": better, "Kém hơn": worse, "p": p})
        rr = pd.DataFrame(rr)
        rr["p (Holm)"] = holm(rr["p"])
        rows.append(rr)
    out = pd.concat(rows, ignore_index=True)
    out["p"] = out["p"].round(4)
    return out

# Lặp lại H1 của Section 4 với thiết kế m suất (m = SCALE_M), trên tập test
print(f"\nThiết kế m suất của Section 4 (m = {SCALE_M}), trên tập test")
_r = []
for repo, g in test.groupby("Repo"):
    rr = []
    for N in SCALE_NS:
        for a, b in ((f"Hit{N}_vote_ast", f"Hit{N}_random_ast"), (f"Hit{N}_vote_ast", f"Hit{N}_m0"),
                     (f"Hit{N}_random_ast", f"Hit{N}_m0")):
            up, down, p = mcnemar(g[a], g[b])
            rr.append({"Repo": repo, "So sánh": f"{a} / {b}", "Tỷ lệ trái": round(g[a].mean(), 3),
                       "Tỷ lệ phải": round(g[b].mean(), 3), "Trái hơn": up, "Phải hơn": down, "p": p})
    for metric in ("B1", "B2"):
        up, down, p = mcnemar(g[f"{metric}_vote_ast"], g[f"{metric}_random_ast"])
        rr.append({"Repo": repo, "So sánh": f"{metric}_vote_ast / {metric}_random_ast",
                   "Tỷ lệ trái": round(g[f"{metric}_vote_ast"].mean(), 3),
                   "Tỷ lệ phải": round(g[f"{metric}_random_ast"].mean(), 3), "Trái hơn": up, "Phải hơn": down, "p": p})
    rr = pd.DataFrame(rr)
    rr["p (Holm)"] = holm(rr["p"])
    _r.append(rr)
_r = pd.concat(_r, ignore_index=True)
_r["p"] = _r["p"].round(4)
display(_r)

# Đối chiếu với Section 4: Hit chỉ AST trên các instance Lite (graph snapshot so với graph theo commit)
print("\nĐối chiếu với Section 4 (graph theo commit): Hit chỉ AST trên các instance Lite")
print("  Section 4 đã đo: Django N=20 0.561, N=40 0.614 | sympy N=20 0.481, N=40 0.519")
display(dev.groupby("Repo")[[f"Hit{N}_m0" for N in SCALE_NS]].mean().round(3))

Bỏ qua cell của v3 (RUN_V3 = False)

In [24]:
%%v3
# ── Section 5 (tiếp): chọn cách trộn doc trên tập dev, kiểm định 1 lần trên tập test ──────────
# Dùng id các xếp hạng mà scale_row lưu (SCALE_RESULTS bản v2), nên không cần chạy lại truy xuất.
# Hai cách trộn: rrf (điểm = 1/(k + hạng AST) + w/(k + vị trí trong tập doc), như cell trên) và convex (tổ hợp lồi
# của điểm AST và điểm doc đã chuẩn hóa min-max, theo Bruch và cộng sự, TOIS 2023). Hai tùy chọn giảm rủi ro:
# bảo vệ h node đầu của AST (Hit@1..h không thể giảm), và chỉ giữ node doc có cạnh Documents trực tiếp.
# Tiêu chí chọn (đặt trước khi chạy): trên tập dev, xét ΔHit@k = Hit@k(doc) − Hit@k(AST) ở mức hàm, k ∈ FUSE_KS.
# Trong các cấu hình không âm ở mọi k, chọn cấu hình có ΔHit trung bình lớn nhất. Nếu không có cấu hình nào
# không âm, chọn cấu hình có ΔHit trung bình lớn nhất. Hòa thì ưu tiên trọng số doc nhỏ hơn, rồi h nhỏ hơn.
from collections import defaultdict

assert "ast_ids" in sdf.columns, ("File kết quả chưa có id các xếp hạng → chạy lại scale-run với "
                                  "SCALE_RESULTS bản v2, rồi chạy lại scale-analysis")
FUSE_METHODS = [("rrf", w) for w in (0.05, 0.1, 0.25)] + [("convex", a) for a in (0.05, 0.1, 0.2, 0.3, 0.5)]
FUSE_HEADS   = (0, 1, 3, 5)
FUSE_FILTERS = ("all", "direct")
FUSE_KS      = (1, 5, 10, 20)
LIST_K       = 100
LEVELS       = ("func", "class", "file")
RISK_ALPHAS  = (1, 5)
DOC_FIXED    = ("rrf", 0.1, 1, "all")      # cấu hình DOC đã chọn trên 12 repo (scale_rows_v2); giữ nguyên để DOC mới
                                           # so được với kết quả cũ. None = chọn lại trên tập dev như lưới bên dưới

def _mm(vals):
    lo, hi = min(vals), max(vals)
    return [(v - lo) / (hi - lo) if hi > lo else 1.0 for v in vals]

def fused_list(row, s, method, p, h=0, flt="all"):
    """Top LIST_K (id) sau khi trộn xếp hạng AST với tập doc của nguồn s. Kết quả chính xác tới LIST_K, vì
    mọi node AST ngoài top SCALE_TOPK đều có điểm thấp hơn cả SCALE_TOPK node AST đầu."""
    ast = row["ast_ids"]
    ra = {x: i + 1 for i, x in enumerate(ast)}
    doc = [d for d in zip(row[f"doc_ids_{s}"], row[f"doc_score_{s}"], row[f"doc_direct_{s}"],
                          row[f"doc_ast_score_{s}"], row[f"doc_r_{s}"]) if flt == "all" or d[2]]
    score = defaultdict(float)
    if method == "rrf":
        for x, r in ra.items():
            score[x] += 1.0 / (FUSE_K + r)
        for j, (x, _, _, _, r) in enumerate(doc, 1):
            if x not in ra and r:
                score[x] += 1.0 / (FUSE_K + r)         # hạng AST ngoài top SCALE_TOPK vẫn được tính
            score[x] += p / (FUSE_K + j)
    else:
        a_raw = dict(zip(ast, row["ast_scores"]))
        for x, _, _, asc, _ in doc:
            a_raw.setdefault(x, asc)
        a_n = dict(zip(a_raw, _mm(list(a_raw.values()))))
        d_n = dict(zip([d[0] for d in doc], _mm([d[1] for d in doc]))) if doc else {}
        for x in set(a_n) | set(d_n):
            score[x] = (1 - p) * a_n.get(x, 0.0) + p * d_n.get(x, 0.0)
    order = sorted(score, key=lambda x: (-score[x], ra.get(x, 10 ** 6), x))
    if h:
        head = ast[:h]
        order = head + [x for x in order if x not in set(head)]
    return order[:LIST_K]

def level_rank(order, row, level):
    """Hạng (1-based) của node đầu tiên trúng gold ở mức hàm / class / file; None nếu không có trong order."""
    meta, gold = row["node_meta"], row["gold_ids"]
    f = {"func": lambda x: x, "class": lambda x: meta[x][0], "file": lambda x: meta[x][1]}[level]
    tgt = {f(g) for g in gold}
    return next((i + 1 for i, x in enumerate(order) if f(x) in tgt), None)

def urisk(new, base, alpha):
    """URisk và TRisk (Dinçer, Macdonald, Ounis, SIGIR 2014): phần mất bị phạt (1 + alpha) lần."""
    d = np.asarray(new, dtype=float) - np.asarray(base, dtype=float)
    adj = np.where(d >= 0, d, (1 + alpha) * d)
    se = adj.std(ddof=1) / np.sqrt(len(adj)) if len(adj) > 1 else np.nan
    return round(float(adj.mean()), 4), (round(float(adj.mean() / se), 2) if se and se > 0 else np.nan)

_hitk = lambda ranks, k: np.mean([r is not None and r <= k for r in ranks])

# Kiểm tra: rrf, h = 0, mọi node doc → hạng mức hàm trùng fused_rank của cell trên (fused_rank tính hòa bất lợi,
# nên chỉ có thể lớn hơn hoặc bằng)
for _, r in sdf.head(200).iterrows():
    a, b = level_rank(fused_list(r, "vote_ast", "rrf", 0.1), r, "func"), fused_rank(r, "vote_ast", 0.1)
    assert (a is None and (b is None or b > LIST_K)) or (a is not None and b is not None and a <= b), r["Instance"]

# 1. Lưới cấu hình trên tập dev
_ast_dev = [level_rank(r["ast_ids"], r, "func") for _, r in dev.iterrows()]
_grid = []
for (m, p) in FUSE_METHODS:
    for h in FUSE_HEADS:
        for flt in FUSE_FILTERS:
            rk = [level_rank(fused_list(r, "vote_ast", m, p, h, flt), r, "func") for _, r in dev.iterrows()]
            d = {k: _hitk(rk, k) - _hitk(_ast_dev, k) for k in FUSE_KS}
            _grid.append({"method": m, "p": p, "h": h, "filter": flt,
                          **{f"ΔHit@{k}": round(v, 4) for k, v in d.items()},
                          "ΔHit TB": round(np.mean(list(d.values())), 4), "ΔHit nhỏ nhất": round(min(d.values()), 4)})
_grid = pd.DataFrame(_grid)
_ok = _grid[_grid["ΔHit nhỏ nhất"] >= 0]
_pick = (_ok if len(_ok) else _grid).sort_values(["ΔHit TB", "p", "h"], ascending=[False, True, True]).iloc[0]
DOC_METHOD = (_pick["method"], float(_pick["p"]), int(_pick["h"]), _pick["filter"])
print(f"Tập dev: {len(dev)} instance | {len(_ok)}/{len(_grid)} cấu hình không âm ở mọi k ∈ {FUSE_KS}")
display(_grid.sort_values("ΔHit TB", ascending=False).head(12))
print(f"Cấu hình được chọn: method={DOC_METHOD[0]} p={DOC_METHOD[1]} h={DOC_METHOD[2]} filter={DOC_METHOD[3]}"
      + ("" if len(_ok) else "  (không có cấu hình nào không âm ở mọi k)"))

if DOC_FIXED is not None:
    DOC_METHOD = DOC_FIXED
    print(f"Dùng cấu hình DOC cố định (đã chọn trên 12 repo): method={DOC_METHOD[0]} p={DOC_METHOD[1]} "
          f"h={DOC_METHOD[2]} filter={DOC_METHOD[3]}")

def fused_multi(row, terms, h=0):
    """RRF của xếp hạng AST với nhiều tập (doc, history): điểm = 1/(k + hạng AST) + Σ p_s/(k + vị trí trong tập s).
    Với 1 tập, trùng fused_list(row, s, "rrf", p, h, "all")."""
    ast = row["ast_ids"]
    ra = {x: i + 1 for i, x in enumerate(ast)}
    score, extra = defaultdict(float), set()
    for x, r in ra.items():
        score[x] += 1.0 / (FUSE_K + r)
    for s, p in terms:
        for j, (x, r) in enumerate(zip(row[f"doc_ids_{s}"], row[f"doc_r_{s}"]), 1):
            if x not in ra and r and x not in extra:
                score[x] += 1.0 / (FUSE_K + r)             # hạng AST ngoài top SCALE_TOPK chỉ tính 1 lần
                extra.add(x)
            score[x] += p / (FUSE_K + j)
    order = sorted(score, key=lambda x: (-score[x], ra.get(x, 10 ** 6), x))
    if h:
        head = ast[:h]
        order = head + [x for x in order if x not in set(head)]
    return order[:LIST_K]

for _, r in sdf.head(200).iterrows():                    # kiểm tra: 1 tập → trùng fused_list
    assert fused_multi(r, [("vote_ast", 0.1)], 1) == fused_list(r, "vote_ast", "rrf", 0.1, 1), r["Instance"]

def _delta(rk, base):
    d = {k: _hitk(rk, k) - _hitk(base, k) for k in FUSE_KS}
    return {**{f"ΔHit@{k}": round(v, 4) for k, v in d.items()}, "ΔHit TB": round(np.mean(list(d.values())), 4),
            "ΔHit nhỏ nhất": round(min(d.values()), 4)}

def _choose(grid, keys):
    """Cùng tiêu chí với DOC: trong các cấu hình không âm ở mọi k, lấy ΔHit TB lớn nhất; hòa thì ưu tiên giá trị nhỏ."""
    g = pd.DataFrame(grid)
    ok = g[g["ΔHit nhỏ nhất"] >= 0]
    pick = (ok if len(ok) else g).sort_values(["ΔHit TB"] + keys, ascending=[False] + [True] * len(keys)).iloc[0]
    return g, ok, pick

# 1b. HIST: chọn số commit k, trọng số p và h trên tập dev (so với AST)
_RRF_P = [p for m, p in FUSE_METHODS if m == "rrf"]
_hgrid = []
for k in HIST_KS:
    for p in _RRF_P:
        for h in FUSE_HEADS:
            rk = [level_rank(fused_list(r, f"vote_hist{k}_ast", "rrf", p, h), r, "func") for _, r in dev.iterrows()]
            _hgrid.append({"k": k, "p": p, "h": h, **_delta(rk, _ast_dev)})
_hg, _hok, _hp = _choose(_hgrid, ["p", "h", "k"])
HIST_METHOD = (int(_hp["k"]), float(_hp["p"]), int(_hp["h"]))
print(f"\nHIST, tập dev: {len(_hok)}/{len(_hg)} cấu hình không âm ở mọi k ∈ {FUSE_KS}")
display(_hg.sort_values("ΔHit TB", ascending=False).head(8))
print(f"Cấu hình HIST: {HIST_METHOD[0]} commit, p={HIST_METHOD[1]}, h={HIST_METHOD[2]}"
      + ("" if len(_hok) else "  (không có cấu hình nào không âm ở mọi k)"))

# 1c. DOC+HIST: giữ nguyên phần DOC, thêm phần HIST (k của HIST); chọn p_hist và h trên tập dev (so với AST)
assert DOC_METHOD[0] == "rrf" and DOC_METHOD[3] == "all", "DOC+HIST cần DOC dùng rrf trên mọi node doc"
_cgrid = []
for p in _RRF_P:
    for h in FUSE_HEADS:
        rk = [level_rank(fused_multi(r, [("vote_ast", DOC_METHOD[1]), (f"vote_hist{HIST_METHOD[0]}_ast", p)], h),
                         r, "func") for _, r in dev.iterrows()]
        _cgrid.append({"p_hist": p, "h": h, **_delta(rk, _ast_dev)})
_cg, _cok, _cp = _choose(_cgrid, ["p_hist", "h"])
COMBO_METHOD = (float(_cp["p_hist"]), int(_cp["h"]))
print(f"\nDOC+HIST, tập dev (so với AST): {len(_cok)}/{len(_cg)} cấu hình không âm ở mọi k ∈ {FUSE_KS}")
display(_cg.sort_values("ΔHit TB", ascending=False).head(8))
print(f"Cấu hình DOC+HIST: DOC p={DOC_METHOD[1]}, HIST {HIST_METHOD[0]} commit p={COMBO_METHOD[0]}, h={COMBO_METHOD[1]}"
      + ("" if len(_cok) else "  (không có cấu hình nào không âm ở mọi k)"))

SYSTEMS = ("AST", "DOC", "RAND", "HIST", "RAND_HIST", "DOC+HIST")
PAIRS   = (("DOC", "AST"), ("DOC", "RAND"), ("HIST", "AST"), ("HIST", "RAND_HIST"), ("DOC+HIST", "HIST"),
           ("DOC+HIST", "DOC"))

def system_orders(row):
    """Các xếp hạng được so sánh và được gộp cho judge. RAND / RAND_HIST dùng cùng cấu hình với DOC / HIST."""
    k, ph, hh = HIST_METHOD
    return {"AST": row["ast_ids"][:LIST_K],
            "DOC": fused_list(row, "vote_ast", *DOC_METHOD),
            "RAND": fused_list(row, "random_ast", *DOC_METHOD),
            "HIST": fused_list(row, f"vote_hist{k}_ast", "rrf", ph, hh),
            "RAND_HIST": fused_list(row, f"random_hist{k}_ast", "rrf", ph, hh),
            "DOC+HIST": fused_multi(row, [("vote_ast", DOC_METHOD[1]), (f"vote_hist{k}_ast", COMBO_METHOD[0])],
                                    COMBO_METHOD[1])}

# 2. Tập test, chạy 1 lần với cấu hình đã chọn: 3 mức hàm / class / file
ORDERS = {r["Instance"]: system_orders(r) for _, r in sdf.iterrows()}      # dùng lại ở Section 6
for lvl in LEVELS:
    for sys_name in SYSTEMS:
        sdf[f"{sys_name}_{lvl}"] = [level_rank(ORDERS[r["Instance"]][sys_name], r, lvl) for _, r in sdf.iterrows()]
dev, test = sdf[sdf["lite"]], sdf[~sdf["lite"]]
for lvl in LEVELS:
    print(f"\nMức {lvl}, tập test ({len(test)} instance)")
    for a, b in PAIRS:
        display(compare_ranks(test, f"{a}_{lvl}", f"{b}_{lvl}", f"{a} so với {b}, mức {lvl}"))

# 3. Rủi ro so với AST (reciprocal rank mức hàm)
_rr = lambda col: col.map(lambda x: 0.0 if pd.isna(x) else 1.0 / x)
_risk = []
for sys_name in ("DOC", "HIST", "DOC+HIST"):
    for repo, g in test.groupby("Repo"):
        for a in RISK_ALPHAS:
            u, t = urisk(_rr(g[f"{sys_name}_func"]), _rr(g["AST_func"]), a)
            _risk.append({"Hệ thống": sys_name, "Repo": repo, "alpha": a, "URisk": u, "TRisk": t,
                          "Thắng": int((_rr(g[f"{sys_name}_func"]) > _rr(g["AST_func"])).sum()),
                          "Thua": int((_rr(g[f"{sys_name}_func"]) < _rr(g["AST_func"])).sum())})
print("\nRủi ro so với AST (reciprocal rank mức hàm). TRisk > 2: tốt hơn có ý nghĩa; < −2: kém hơn có ý nghĩa")
display(pd.DataFrame(_risk))

# 4. H3: tách theo issue có gọi tên gold (mức hàm)
for v, name in ((0, "không gọi tên gold"), (1, "gọi tên gold")):
    g = test[test["issue_names_gold"] == v]
    print(f"\nH3, issue {name}: {len(g)} instance")
    display(compare_ranks(g, "DOC_func", "AST_func", f"DOC so với AST, issue {name}"))

# 5. Cơ chế: tập node của doc / history có chứa gold không (B2), và hai nguồn bổ sung nhau thế nào (tập test)
_k = HIST_METHOD[0]
_b = pd.DataFrame({"Repo": test["Repo"], "doc": test["B2_vote_ast"].astype(bool),
                   "hist": test[f"B2_vote_hist{_k}_ast"].astype(bool),
                   "rhist": test[f"B2_random_hist{_k}_ast"].astype(bool)})
print(f"\nTập node chứa gold (B2), tập test, history {_k} commit")
display(_b.groupby("Repo").agg(**{"Instance": ("doc", "size"), "Tập doc chứa gold": ("doc", "mean"),
                                   "Tập history chứa gold": ("hist", "mean"),
                                   "Tập history ngẫu nhiên chứa gold": ("rhist", "mean")}).round(3))
_b["Nhóm"] = np.select([_b["doc"] & _b["hist"], _b["doc"], _b["hist"]], ["Cả hai", "Chỉ doc", "Chỉ history"],
                       "Không nguồn nào")
display(pd.crosstab(_b["Repo"], _b["Nhóm"], normalize="index").round(3))

Bỏ qua cell của v3 (RUN_V3 = False)

In [25]:
%%v3
# ── Section 5b: commit tìm trên toàn bộ history (không qua bộ lọc), để đánh giá history giống document ───────────
# Document có danh sách "toàn bộ doc": chunk tìm trên mọi chunk, kể cả chunk không có cạnh tới code. Tương tự, cell này
# tìm HIST_ALL_N commit giống issue nhất trên MỌI commit là tổ tiên của snapshot, không lọc theo cửa sổ thời gian hay số
# hàm/lớp bị sửa (cùng cách tìm với HIST: RRF của BM25 và embedding message), và ghi lý do mỗi commit có hoặc không
# được HIST dùng. Judge chấm thêm các commit này (request <instance>#histall ở judge-pool).
HIST_ALL_N = 10
_REASONS = ("dùng được", "ngoài cửa sổ thời gian", "sửa quá nhiều hàm/lớp", "không sửa hàm/lớp nào còn trong snapshot")
_text_of = {i["id"]: i["text"] for i in SCALE_INSTANCES}
_snap_of = {i["id"]: i["snapshot"] for i in SCALE_INSTANCES}

def hist_all_index(repo, snapshot):
    """Hàm tìm commit trên mọi tổ tiên của snapshot; mỗi kết quả kèm số hàm/lớp sửa có trong graph và lý do."""
    H, s8, rp = HIST[repo], snapshot[:8], repo_path_of(repo)
    anc = set(_git(rp, "rev-list", snapshot).split())
    ids = [i for i, u in enumerate(H["units"]) if u["h"] in anc]
    if not ids:
        return lambda q, n: []
    lab = {n["id"]: n["label"] for n in load_graph_summary(build_graph(snapshot, repo_path=rp))["nodes"]}
    t0 = _SNAP_CT[(repo, snapshot)] - HIST_YEARS * _YEAR
    info = []
    for i in ids:
        u = H["units"][i]
        n_fc = sum(lab.get(f"{s8}:{k}") in _FC for k in u["touch"])
        info.append((n_fc, _REASONS[3] if n_fc == 0 else _REASONS[1] if u["t"] < t0 else
                     _REASONS[2] if n_fc > HIST_MAX_TOUCH else _REASONS[0]))
    bm, E = BM25Okapi([H["toks"][i] for i in ids]), H["emb"][ids]
    def _rank(x):
        r = np.empty(len(x)); r[np.argsort(-x, kind="stable")] = np.arange(len(x)); return r
    def search(q, n):
        qe = _get_model(_EMBED_MODEL_ID).encode([_embed_query(q)], normalize_embeddings=True, convert_to_numpy=True)[0]
        sc = 1.0 / (60 + _rank(bm.get_scores(_tokenize_code(q)))) + 1.0 / (60 + _rank(E @ qe))
        return [{"h": H["units"][ids[j]]["h"][:8], "score": round(float(sc[j]), 6), "n_fc": info[j][0],
                 "reason": info[j][1]} for j in np.argsort(-sc, kind="stable")[:n]]
    return search

HIST_ALL = {}
for (_repo, _snap), _g in tqdm(sdf.assign(_s=sdf["Instance"].map(_snap_of)).groupby(["Repo", "_s"]),
                               desc="toàn bộ history", unit="snapshot"):
    _search = hist_all_index(_repo, _snap)
    for _iid in _g["Instance"]:
        HIST_ALL[_iid] = _search(_text_of[_iid], HIST_ALL_N)
_ra = pd.DataFrame([{"Repo": sdf.set_index("Instance").at[i, "Repo"], "Lý do": c["reason"]}
                    for i, v in HIST_ALL.items() for c in v])
print(f"{len(HIST_ALL)} instance | {HIST_ALL_N} commit mỗi instance, tìm trên toàn bộ history. Tỷ lệ commit theo lý do:")
display(pd.crosstab(_ra["Repo"], _ra["Lý do"], normalize="index").round(3))

Bỏ qua cell của v3 (RUN_V3 = False)

## 6. LLM-as-a-judge: chấm mọi node của kết quả truy xuất (node code, chunk doc, commit)

Thước đo theo gold chỉ tính một node là trúng khi nó nằm trong patch. Section này dùng LLM chấm mức độ liên quan của mọi node mà truy xuất trả về. Nhờ vậy, Section này đánh giá được cả bản thân document và commit, chứ không chỉ tác động của chúng lên xếp hạng code.

Mỗi instance có ba request:

- **Node code**: hợp top `POOL_DEPTH` của mọi xếp hạng (AST, DOC, RAND, HIST, RAND_HIST, DOC+HIST). Judge thấy toàn bộ code của node, kể cả thân lớp, lấy từ git tại commit snapshot.
- **Chunk doc**: các chunk mà DOC dùng, các chunk ngẫu nhiên của RAND, và `DOC_ALL_N` chunk đầu khi tìm trên mọi chunk, kể cả chunk không có cạnh `Documents`. Judge thấy toàn văn chunk.
- **Commit**: các commit mà HIST dùng và cùng số commit ngẫu nhiên của RAND_HIST. Judge thấy message và danh sách hàm, lớp mà commit đã sửa. Một request thứ tư chấm các commit tìm trên toàn bộ history (cell `hist-all`, không qua bộ lọc của HIST) mà request commit chưa có.

Judge không thấy patch hay gold, và không biết phần tử đến từ nguồn nào. Thứ tự phần tử được xáo trộn với seed cố định theo instance. Thang điểm 0 đến 3 cho từng loại phần tử nằm trong các prompt ở cell `judge-config`.

Nhãn của thực nghiệm này nằm trong `JUDGE_DIR`, tức thư mục `judge_v3` trong `WORK_DIR`. Nhãn của lượt 12 repo trước vẫn ở thư mục `judge`. Chạy lại `judge-run` sẽ bỏ qua các request đã có kết quả.

In [26]:
# ── Section 6: cấu hình LLM-as-a-judge (Gemini API) ─────────────────────────────────────────
!pip install -q -U google-genai
import json
import random
import re
import time
from pathlib import Path

GOOGLE_API_KEY = ""                          # dán API key của Google AI Studio vào đây
JUDGE_MODEL    = "gemini-3.1-flash-lite"     # ổn định, có gói miễn phí
THINKING_LEVEL = "LOW"                       # token thinking tính như token đầu ra → để thấp
POOL_DEPTH     = 10                          # gộp top 10 của mỗi xếp hạng
# Judge nhận toàn văn issue, toàn bộ code của node (lấy từ git theo dòng đầu/cuối), toàn văn chunk doc và message commit
JUDGE_DIR      = Path(WORK_DIR) / "judge_v3"   # thực nghiệm v3 (django + sympy); nhãn của lượt 12 repo vẫn ở judge/
JUDGE_DIR.mkdir(parents=True, exist_ok=True)

JUDGE_PROMPT = """You are assessing how relevant each code element is to resolving a GitHub issue.
You do not see the fix. Judge each element independently, using only the issue and the element's code.

## Issue
{issue}

## Code elements
{elements}

## Scale
3 = the fix must change code inside this element
2 = must be read or understood to make the fix (it is on the failing execution path, or it defines behavior the issue refers to)
1 = same feature or area, but not needed for the fix
0 = unrelated

Return a JSON array with exactly one object per element: {{"id": "C1", "score": <0-3>, "reason": "<one short sentence>"}}."""

JUDGE_PROMPT_DOC = """You are assessing how relevant each passage of the project documentation is to resolving a GitHub issue.
You do not see the fix. Judge each passage independently, using only the issue and the passage.

## Issue
{issue}

## Documentation passages
{elements}

## Scale
3 = describes exactly the behavior or feature that the fix must change, or names the code element that must change
2 = contains information needed to understand or locate the fix
1 = same feature or area, but not needed for the fix
0 = unrelated

Return a JSON array with exactly one object per passage: {{"id": "D1", "score": <0-3>, "reason": "<one short sentence>"}}."""

JUDGE_PROMPT_HIST = """You are assessing how relevant each past commit of the project is to resolving a GitHub issue.
Every commit was made before the issue was reported. You see its message and the functions or classes it changed.
You do not see the fix. Judge each commit independently, using only the issue and the commit.

## Issue
{issue}

## Past commits
{elements}

## Scale
3 = changed the same behavior the issue is about, so the fix very likely touches the code this commit changed
2 = gives information needed to understand or locate the fix (related behavior, or code on the same execution path)
1 = same feature or area, but not needed for the fix
0 = unrelated

Return a JSON array with exactly one object per commit: {{"id": "H1", "score": <0-3>, "reason": "<one short sentence>"}}."""

JUDGE_SCHEMA = {"type": "array",
                "items": {"type": "object",
                          "properties": {"id": {"type": "string"},
                                         "score": {"type": "integer", "minimum": 0, "maximum": 3},
                                         "reason": {"type": "string"}},
                          "required": ["id", "score", "reason"]}}
print(f"Judge: {JUDGE_MODEL} | thinking={THINKING_LEVEL} | pool top {POOL_DEPTH} | {JUDGE_DIR}")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 1.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 20.7 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 267.9/267.9 kB 14.7 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.48.0 requires google-cloud-bigquery-storage<3.0.0,>=2.30.0, which is not installed.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.62.0 which is incompatible.
google-colab 1.0.0 requires jupyter-server==2.20.0, but you have jupyter-server 2.12.5 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 2.3.3 which is incompatible.
google-colab 1.0.0 requires requests==2.32.4, but you have requests 2.34.2 which is incompatible.
Judge: gemini-3.1-flash-lite | thinking=LOW | pool top 10 | /kaggle/working/judge_v3

In [27]:
%%v3
# ── Section 6: request cho judge. Mỗi instance có 3 request: node code, chunk doc, commit ──────────────────
# Code: hợp top POOL_DEPTH của mọi xếp hạng trong ORDERS; toàn bộ code của node lấy từ git tại commit snapshot theo
# dòng đầu/cuối (không cắt). Doc: chunk mà DOC dùng, chunk ngẫu nhiên của RAND, và DOC_ALL_N chunk đầu tìm trên mọi
# chunk (kể cả chunk không có cạnh Documents); toàn văn chunk. Commit: các commit mà HIST dùng (k của HIST_METHOD) và
# cùng số commit ngẫu nhiên của RAND_HIST; message và các hàm/lớp commit đã sửa. Mỗi request xáo trộn phần tử (seed theo
# instance) và đặt tên C1.., D1.., H1..; judge không biết phần tử đến từ nguồn nào.
# Request thứ tư (<instance>#histall): commit tìm trên toàn bộ history (cell hist-all) mà request commit chưa có.
from collections import defaultdict

_snap_full = {i["id"]: (i["repo"], i["snapshot"]) for i in SCALE_INSTANCES}
_text = {i["id"]: i["text"] for i in SCALE_INSTANCES}
_FILE_TXT = {}

def _file_lines(repo, snap, path):
    if (snap, path) not in _FILE_TXT:
        if len(_FILE_TXT) > 2000:
            _FILE_TXT.clear()
        _FILE_TXT[(snap, path)] = _git(repo_path_of(repo), "show", f"{snap}:{path}").split("\n")
    return _FILE_TXT[(snap, path)]

def _code_of(nd, repo, snap):
    """Toàn bộ code của node (hàm hoặc lớp, kể cả thân lớp) tại commit snapshot."""
    if nd.get("file") and nd.get("start_line") and nd.get("end_line"):
        txt = "\n".join(_file_lines(repo, snap, nd["file"])[nd["start_line"] - 1: nd["end_line"]])
        if txt.strip():
            return txt
    return nd.get("source") or f"{nd['label']} {nd.get('name', '')}"

def _qual(key):
    parts = key.split(":")
    return (".".join(parts[1:]) or parts[0]), parts[0]

def _request(prompt):
    return {"contents": [{"role": "user", "parts": [{"text": prompt}]}],
            "generationConfig": {"responseMimeType": "application/json", "responseJsonSchema": JUDGE_SCHEMA,
                                 "thinkingConfig": {"thinkingLevel": THINKING_LEVEL}}}

def _items(members, iid, prefix):
    items = [{"node": k, "systems": sorted(v)} for k, v in members.items()]
    random.Random(iid + prefix).shuffle(items)
    for j, it in enumerate(items, 1):
        it["alias"] = f"{prefix}{j}"
    return items

def _commit_el(repo, it):
    """Phần tử commit trong prompt: message và mọi hàm/lớp (kể cả code cấp module) commit đã sửa."""
    u = _units[repo][it["node"]]
    changed = [f"- {_qual(k)[0]} ({_qual(k)[1]})" for k in u["touch"]]
    changed += [f"- module-level code in {f}" for f in u["touch_mod"]]
    return f"[{it['alias']}] commit {it['node']}\nMessage:\n{u['msg']}\nChanged:\n" + "\n".join(changed)

REQ, POOL = {}, {}
_k_hist = HIST_METHOD[0]
_units = {repo: {u["h"][:8]: u for u in HIST[repo]["units"]} for repo in HIST}
_rows = sdf.assign(_snap=sdf["Instance"].map(lambda x: _snap_full[x][1])).sort_values(["Repo", "_snap", "Instance"])
for (repo, snap), g in tqdm(_rows.groupby(["Repo", "_snap"], sort=False), desc="judge pool", unit="snapshot"):
    nbi = {n["id"]: n for n in read_graph_json(build_graph(snap, repo_path=repo_path_of(repo)))["nodes"]}
    s8 = snap[:8]
    for _, r in g.iterrows():
        iid, issue, gold = r["Instance"], _text[r["Instance"]], set(r["gold_ids"])
        base = {"Instance": iid, "Repo": repo, "issue_names_gold": int(r["issue_names_gold"])}
        # 1. Node code
        mem = defaultdict(set)
        for sys_name, order in ORDERS[iid].items():
            for k in order[:POOL_DEPTH]:
                mem[k].add(sys_name)
        items = _items(mem, iid, "C")
        els = []
        for it in items:
            it["is_gold"] = it["node"] in gold
            qn, f = _qual(it["node"])
            els.append(f"[{it['alias']}] {qn}  ({f})\n```python\n{_code_of(nbi[s8 + ':' + it['node']], repo, snap)}\n```")
        REQ[f"{iid}#code"] = _request(JUDGE_PROMPT.format(issue=issue, elements="\n\n".join(els)))
        POOL[f"{iid}#code"] = {**base, "kind": "code", "items": items}
        # 2. Chunk doc
        mem = defaultdict(set)
        for src, ids in (("DOC", r["doc_chunks_vote_ast"]), ("RAND", r["doc_chunks_random_ast"]),
                         ("ALL", r["doc_chunks_all"])):
            for cid in ids:
                mem[cid].add(src)
        if mem:
            items = _items(mem, iid, "D")
            els = [f"[{it['alias']}] {nbi[it['node']]['file']} | {nbi[it['node']].get('heading') or ''}\n"
                   f"{nbi[it['node']].get('text') or ''}" for it in items]
            REQ[f"{iid}#doc"] = _request(JUDGE_PROMPT_DOC.format(issue=issue, elements="\n\n".join(els)))
            POOL[f"{iid}#doc"] = {**base, "kind": "doc", "items": items}
        # 3. Commit
        mem = defaultdict(set)
        for h, _ in r["hist_commits_vote"][:_k_hist]:
            mem[h].add("HIST")
        for h in r["hist_commits_random"][:_k_hist]:
            mem[h].add("RAND_HIST")
        if mem:
            items = _items(mem, iid, "H")
            REQ[f"{iid}#hist"] = _request(JUDGE_PROMPT_HIST.format(
                issue=issue, elements="\n\n".join(_commit_el(repo, it) for it in items)))
            POOL[f"{iid}#hist"] = {**base, "kind": "hist", "items": items}
        # 4. Commit tìm trên toàn bộ history, chỉ các commit request commit ở trên chưa có
        extra = {c["h"]: {"ALL_HIST"} for c in HIST_ALL.get(iid, []) if c["h"] not in mem}
        if extra:
            items = _items(extra, iid, "H")
            REQ[f"{iid}#histall"] = _request(JUDGE_PROMPT_HIST.format(
                issue=issue, elements="\n\n".join(_commit_el(repo, it) for it in items)))
            POOL[f"{iid}#histall"] = {**base, "kind": "histall", "items": items}

with open(JUDGE_DIR / "requests.jsonl", "w", encoding="utf-8") as f:
    for k, v in REQ.items():
        f.write(json.dumps({"key": k, "request": v}, ensure_ascii=False) + "\n")
with open(JUDGE_DIR / "pool.jsonl", "w", encoding="utf-8") as f:
    for k, v in POOL.items():
        f.write(json.dumps({"key": k, **v}, ensure_ascii=False) + "\n")
for kind in ("code", "doc", "hist", "histall"):
    ks = [k for k, v in POOL.items() if v["kind"] == kind]
    n = pd.Series([len(POOL[k]["items"]) for k in ks])
    ch = pd.Series([len(REQ[k]["contents"][0]["parts"][0]["text"]) for k in ks])
    print(f"{kind}: {len(ks)} request | phần tử mỗi request TB {n.mean():.1f}, max {n.max()} | "
          f"độ dài prompt TB {ch.mean() / 4:.0f} token, max {ch.max() / 4:.0f} token (ước lượng)")

Bỏ qua cell của v3 (RUN_V3 = False)

In [28]:
%%v3
# ── Section 6: gọi judge cho mọi instance ─────────────────────────────────────────────────
# JUDGE_MODE = "sync": gọi từng request, dùng được gói miễn phí (bị giới hạn số request mỗi phút và mỗi ngày).
# JUDGE_MODE = "batch": batch của Gemini API, giảm 50%, cần project có billing; xong trong vòng 24 giờ.
#   Request được chia theo instance: mỗi batch gồm mọi request (code, doc, commit) của JUDGE_BATCH_INSTANCES instance.
#   Các batch gửi lần lượt (batch sau chỉ gửi khi batch trước xong), nên tổng token đang xếp hàng không vượt giới hạn
#   "batch enqueued tokens" của gói (Tier 1: 10 triệu token cho flash-lite). Mỗi batch có tên cố định, ghi trong
#   JUDGE_DIR/batch_jobs.txt; chạy lại cell thì batch đã gửi được chờ và lấy kết quả, không bị gửi lại. Tên batch gồm
#   các loại request còn thiếu nhãn, nên khi thêm loại request mới (vd #histall), request mới thành batch mới.
# Kết quả: JUDGE_DIR/labels_<model>.jsonl. Request lỗi hoặc thiếu node được chấm lại từng cái ở cuối.
from concurrent.futures import ThreadPoolExecutor
from google import genai

JUDGE_MODE = "batch"
JUDGE_BATCH_INSTANCES = 150                  # số instance mỗi batch; giảm nếu vẫn gặp lỗi 429 RESOURCE_EXHAUSTED
SYNC_WORKERS = 4                             # giảm xuống 1 nếu dùng gói miễn phí và gặp lỗi 429 liên tục

_client = None
def _gclient():
    global _client
    if _client is None:
        assert GOOGLE_API_KEY, "Chưa đặt GOOGLE_API_KEY trong cell judge-config"
        _client = genai.Client(api_key=GOOGLE_API_KEY)
    return _client

def _labels_path(model):
    return JUDGE_DIR / f"labels_{model}.jsonl"

def load_labels(model):
    out = {}
    p = _labels_path(model)
    if p.exists():
        for line in open(p, encoding="utf-8"):
            if line.strip():
                o = json.loads(line)
                if o.get("labels"):
                    out[o["key"]] = o["labels"]
    return out

def parse_judgment(text, aliases):
    """{alias: {"score", "reason"}} nếu đủ mọi alias với điểm 0..3; ngược lại None."""
    try:
        arr = json.loads(text)
    except Exception:
        m = re.search(r"\[.*\]", text or "", re.S)
        try:
            arr = json.loads(m.group(0)) if m else None
        except Exception:
            arr = None
    if not isinstance(arr, list):
        return None
    out = {}
    for it in arr:
        if not isinstance(it, dict):
            continue
        a, s = str(it.get("id", "")).strip(), it.get("score")
        if a in aliases and a not in out and isinstance(s, (int, float)) and int(s) in (0, 1, 2, 3):
            out[a] = {"score": int(s), "reason": str(it.get("reason", ""))[:300]}
    return out if set(out) == set(aliases) else None

def _write(model, key, labels, raw, usage=None):
    with open(_labels_path(model), "a", encoding="utf-8") as f:
        f.write(json.dumps({"key": key, "model": model, "labels": labels, "raw": (raw or "")[:4000],
                            "usage": usage}, ensure_ascii=False) + "\n")

def _sync_one(model, key):
    req = REQ[key]
    cfg = {"response_mime_type": "application/json", "response_json_schema": JUDGE_SCHEMA,
           "thinking_config": {"thinking_level": THINKING_LEVEL}}
    aliases = {it["alias"] for it in POOL[key]["items"]}
    for attempt in range(6):
        try:
            r = _gclient().models.generate_content(model=model, contents=req["contents"], config=cfg)
            u = getattr(r, "usage_metadata", None)
            usage = {"in": getattr(u, "prompt_token_count", None), "out": getattr(u, "candidates_token_count", None),
                     "think": getattr(u, "thoughts_token_count", None)} if u else None
            return key, parse_judgment(r.text, aliases), r.text, usage
        except Exception as e:
            msg = str(e)
            if "response_json_schema" in msg and "response_json_schema" in cfg:
                print("  ⚠ SDK không nhận response_json_schema → dùng response_schema")
                cfg["response_schema"] = cfg.pop("response_json_schema")
                continue
            if "thinking" in msg.lower() and "thinking_config" in cfg:
                print(f"  ⚠ {model} không nhận thinking_level → gọi lại không đặt thinking"); cfg.pop("thinking_config")
                continue
            if any(t in msg for t in ("429", "RESOURCE_EXHAUSTED", "500", "503", "UNAVAILABLE", "DEADLINE")):
                time.sleep(min(90, 5 * 2 ** attempt))
                continue
            return key, None, f"ERROR: {msg[:500]}", None
    return key, None, "ERROR: hết số lần thử", None

def run_sync(model, keys):
    done = load_labels(model)
    todo = [k for k in keys if k not in done]
    print(f"[{model}] sync: {len(keys) - len(todo)} đã có, chấm {len(todo)}")
    bad = 0
    with ThreadPoolExecutor(SYNC_WORKERS) as ex:
        for key, labels, raw, usage in tqdm(ex.map(lambda k: _sync_one(model, k), todo), total=len(todo),
                                            desc=f"judge {model}"):
            _write(model, key, labels, raw, usage)
            bad += labels is None
    if bad:
        print(f"  ⚠ {bad} request không parse được hoặc thiếu node; chạy lại cell sẽ thử lại")

def _resp_text(resp):
    parts = (((resp or {}).get("candidates") or [{}])[0].get("content") or {}).get("parts") or []
    return "".join(p.get("text", "") for p in parts if not p.get("thought"))

def collect_batch(model, job_name):
    """Lấy kết quả của 1 batch job (dùng lại được khi cell bị ngắt: tên job ghi trong JUDGE_DIR/batch_jobs.txt)."""
    job = _gclient().batches.get(name=job_name)
    if job.state.name != "JOB_STATE_SUCCEEDED":
        print(f"  batch {job_name}: {job.state.name}")
        return False
    data = _gclient().files.download(file=job.dest.file_name).decode("utf-8")
    done = load_labels(model)
    n = 0
    for line in data.splitlines():
        if not line.strip():
            continue
        o = json.loads(line)
        key = o.get("key")
        if key not in POOL or key in done:
            continue
        text = _resp_text(o.get("response"))
        labels = parse_judgment(text, {it["alias"] for it in POOL[key]["items"]})
        usage = (o.get("response") or {}).get("usageMetadata")
        _write(model, key, labels, text or json.dumps(o.get("error", ""))[:500], usage)
        n += labels is not None
    print(f"  batch {job_name}: nhận {n} kết quả hợp lệ")
    return True

def _batch_parts(keys):
    """Chia request theo instance (key = <instance>#<loại>): mỗi phần gồm mọi request của JUDGE_BATCH_INSTANCES instance."""
    by_inst = {}
    for k in keys:
        by_inst.setdefault(k.split("#", 1)[0], []).append(k)
    insts = list(by_inst)
    return [[k for i in insts[j:j + JUDGE_BATCH_INSTANCES] for k in by_inst[i]]
            for j in range(0, len(insts), JUDGE_BATCH_INSTANCES)]

def _jobs_of(model):
    """{tên phần: tên job gửi gần nhất} trong JUDGE_DIR/batch_jobs.txt (dòng: model, job, tên phần)."""
    out, p = {}, JUDGE_DIR / "batch_jobs.txt"
    if p.exists():
        for line in open(p, encoding="utf-8"):
            f = line.rstrip("\n").split("\t")
            if len(f) == 3 and f[0] == model:
                out[f[2]] = f[1]
    return out

def _wait(job_name, poll):
    while True:
        state = _gclient().batches.get(name=job_name).state.name
        if state in ("JOB_STATE_SUCCEEDED", "JOB_STATE_FAILED", "JOB_STATE_CANCELLED", "JOB_STATE_EXPIRED"):
            return state
        time.sleep(poll)

def run_batch(model, keys, poll=60):
    parts = _batch_parts(keys)
    print(f"[{model}] batch: {len(keys)} request, {len(parts)} phần, mỗi phần tối đa {JUDGE_BATCH_INSTANCES} instance")
    for i, part in enumerate(parts, 1):
        todo = [k for k in part if k not in load_labels(model)]
        if not todo:
            print(f"  phần {i}/{len(parts)}: đã có nhãn đủ")
            continue
        kinds = "-".join(sorted({k.split("#", 1)[1] for k in todo}))
        name = f"{JUDGE_DIR.name}_{model}_p{i:03d}of{len(parts):03d}_{kinds}"
        job = _jobs_of(model).get(name)
        state = None
        if job:                                   # đã gửi ở lần chạy trước: chờ và lấy kết quả, không gửi lại
            print(f"  phần {i}/{len(parts)}: đã gửi trước đó ({job}), chờ kết quả")
            state = _wait(job, poll)
        if state != "JOB_STATE_SUCCEEDED":
            if job:
                print(f"  phần {i}/{len(parts)}: batch cũ kết thúc {state} → gửi lại {len(todo)} request còn thiếu")
            src = JUDGE_DIR / f"batch_in_{name}.jsonl"
            with open(src, "w", encoding="utf-8") as f:
                for k in todo:
                    f.write(json.dumps({"key": k, "request": REQ[k]}, ensure_ascii=False) + "\n")
            tok = sum(len(REQ[k]["contents"][0]["parts"][0]["text"]) for k in todo) / 4
            up = _gclient().files.upload(file=str(src), config={"display_name": name, "mime_type": "jsonl"})
            job = _gclient().batches.create(model=model, src=up.name, config={"display_name": name}).name
            with open(JUDGE_DIR / "batch_jobs.txt", "a", encoding="utf-8") as f:
                f.write(f"{model}\t{job}\t{name}\n")
            print(f"  phần {i}/{len(parts)}: đã gửi {job} ({len(todo)} request, khoảng {tok / 1e6:.1f} triệu token); chờ kết quả")
            state = _wait(job, poll)
        print(f"  phần {i}/{len(parts)}: batch kết thúc {state}")
        if state == "JOB_STATE_SUCCEEDED":
            collect_batch(model, job)
    left = [k for k in keys if k not in load_labels(model)]
    if left:
        print(f"  chấm lại từng cái {len(left)} request còn thiếu")
        run_sync(model, left)

(run_batch if JUDGE_MODE == "batch" else run_sync)(JUDGE_MODEL, list(REQ))
print(f"{JUDGE_MODEL}: {len(load_labels(JUDGE_MODEL))}/{len(REQ)} request đã có nhãn")

Bỏ qua cell của v3 (RUN_V3 = False)

In [29]:
%%v3
# ── Section 6: phân tích nhãn judge (thực nghiệm v3) ───────────────────────────────────────────────────────
# Node code: nDCG@10 (lợi ích 2^điểm − 1, lý tưởng = các node code đã chấm của chính instance), Rel@k (≥ 1 node điểm ≥ 2
# trong top k), Strict@k (≥ 1 node điểm 3), cho mọi xếp hạng trong ORDERS; so theo cặp (PAIRS), Holm trong từng repo.
# Chunk doc và commit: tỷ lệ instance có ít nhất 1 phần tử liên quan (điểm ≥ 2) theo nguồn, và nhóm nguyên nhân.
from scipy.stats import binomtest, wilcoxon

LAB = load_labels(JUDGE_MODEL)

def _scores(key):
    lab = LAB.get(key)
    return None if lab is None else {it["node"]: lab[it["alias"]]["score"] for it in POOL[key]["items"]}

def judge_metrics():
    rows = []
    for key, meta in POOL.items():
        if meta["kind"] != "code" or (sc := _scores(key)) is None:
            continue
        orders = {s: o[:POOL_DEPTH] for s, o in ORDERS[meta["Instance"]].items()}
        ideal = sorted(sc.values(), reverse=True)[:POOL_DEPTH]
        idcg = sum((2 ** s - 1) / np.log2(i + 2) for i, s in enumerate(ideal))
        row = {"Instance": meta["Instance"], "Repo": meta["Repo"], "issue_names_gold": meta["issue_names_gold"]}
        for s, o in orders.items():
            g = [sc[x] for x in o]
            row[f"nDCG_{s}"] = sum((2 ** v - 1) / np.log2(i + 2) for i, v in enumerate(g)) / idcg if idcg else 0.0
            for k in (1, 5, 10):
                row[f"Rel@{k}_{s}"] = int(any(v >= 2 for v in g[:k]))
                row[f"Strict@{k}_{s}"] = int(any(v == 3 for v in g[:k]))
        for s in ("DOC", "HIST", "DOC+HIST"):          # node nguồn s đưa vào top 10 / node AST bị đẩy ra
            vin = [sc[x] for x in orders[s] if x not in set(orders["AST"])]
            vout = [sc[x] for x in orders["AST"] if x not in set(orders[s])]
            row[f"{s}_vào"] = np.mean(vin) if vin else np.nan
            row[f"AST_ra_{s}"] = np.mean(vout) if vout else np.nan
        row["AST_ra"] = row["AST_ra_DOC"]               # tên cột Section 7 dùng
        rows.append(row)
    return pd.DataFrame(rows)

def compare_judge(jm, a, b, label):
    out = []
    for repo, g in jm.groupby("Repo"):
        rr = []
        x, y = g[f"nDCG_{a}"], g[f"nDCG_{b}"]
        better, worse = int((x > y).sum()), int((x < y).sum())
        rr.append({"Repo": repo, "So sánh": label, "Chỉ số": "nDCG@10 (Wilcoxon)", a: round(x.mean(), 3),
                   b: round(y.mean(), 3), "Tốt hơn": better, "Kém hơn": worse,
                   "p": wilcoxon(x, y).pvalue if better + worse else 1.0})
        for m in ("Rel", "Strict"):
            for k in (1, 5, 10):
                up, down, p = mcnemar(g[f"{m}@{k}_{a}"], g[f"{m}@{k}_{b}"])
                rr.append({"Repo": repo, "So sánh": label, "Chỉ số": f"{m}@{k}", a: round(g[f"{m}@{k}_{a}"].mean(), 3),
                           b: round(g[f"{m}@{k}_{b}"].mean(), 3), "Tốt hơn": up, "Kém hơn": down, "p": p})
        rr = pd.DataFrame(rr)
        rr["p (Holm)"] = holm(rr["p"])
        out.append(rr)
    out = pd.concat(out, ignore_index=True)
    out["p"] = out["p"].round(4)
    return out

def element_table(kind, groups):
    """Mỗi instance: điểm cao nhất, điểm TB, và có phần tử liên quan (điểm ≥ 2) hay không, theo nhóm nguồn."""
    rows = []
    for key, meta in POOL.items():
        if meta["kind"] != kind or (sc := _scores(key)) is None:
            continue
        row = {"Instance": meta["Instance"], "Repo": meta["Repo"]}
        for gname in groups:
            v = [sc[it["node"]] for it in meta["items"] if gname in it["systems"]]
            row[f"max_{gname}"] = max(v) if v else np.nan
            row[f"tb_{gname}"] = np.mean(v) if v else np.nan
            row[f"lq_{gname}"] = int(bool(v) and max(v) >= 2)
        rows.append(row)
    return pd.DataFrame(rows)

def mcnemar_by_repo(df, a, b, label):
    rows = []
    for repo, g in df.groupby("Repo"):
        up, down, p = mcnemar(g[a], g[b])
        rows.append({"Repo": repo, "So sánh": label, "Trái hơn": up, "Phải hơn": down, "p": round(p, 4)})
    return pd.DataFrame(rows)

_kinds = pd.Series([v["kind"] for k, v in POOL.items() if k in LAB]).value_counts().to_dict()
print(f"{JUDGE_MODEL}: request đã có nhãn theo loại {_kinds} / tổng {len(POOL)}")

# ── A. Node code ──────────────────────────────────────────────────────────────────────────────────────
JM = judge_metrics()
assert len(JM), "Chưa có nhãn node code → chạy judge-run"
_gs = [LAB[k][it["alias"]]["score"] for k, v in POOL.items() if v["kind"] == "code" and k in LAB
       for it in v["items"] if it["is_gold"]]
print(f"Kiểm tra nhanh: {len(_gs)} gold nằm trong top {POOL_DEPTH} của ít nhất 1 xếp hạng; "
      f"điểm judge TB {np.mean(_gs):.2f}, tỷ lệ ≥ 2: {np.mean([x >= 2 for x in _gs]):.1%}")
for a, b in PAIRS:
    print(f"\nNode code theo judge: {a} so với {b}")
    display(compare_judge(JM, a, b, f"{a} so với {b}"))

_risk = [{"Hệ thống": s, "Repo": repo, "alpha": a, **dict(zip(("URisk", "TRisk"), urisk(g[f"nDCG_{s}"], g["nDCG_AST"], a)))}
         for s in ("DOC", "HIST", "DOC+HIST") for repo, g in JM.groupby("Repo") for a in RISK_ALPHAS]
print("\nRủi ro so với AST theo nDCG@10"); display(pd.DataFrame(_risk))

_sw = []
for s in ("DOC", "HIST", "DOC+HIST"):
    for repo, g in JM.groupby("Repo"):
        h = g.dropna(subset=[f"{s}_vào", f"AST_ra_{s}"])
        diff = h[f"{s}_vào"] - h[f"AST_ra_{s}"]
        p = wilcoxon(h[f"{s}_vào"], h[f"AST_ra_{s}"]).pvalue if (diff != 0).any() else 1.0
        _sw.append({"Hệ thống": s, "Repo": repo, "Instance có đổi node": len(h),
                    "Điểm TB node đưa vào": round(h[f"{s}_vào"].mean(), 3),
                    "Điểm TB node AST bị đẩy ra": round(h[f"AST_ra_{s}"].mean(), 3),
                    "Đưa vào cao hơn": int((diff > 0).sum()), "Đưa vào thấp hơn": int((diff < 0).sum()),
                    "p (Wilcoxon)": round(p, 4),
                    "Kịch bản": "A" if p < 0.05 and diff.mean() > 0 else ("C" if p < 0.05 and diff.mean() < 0 else "B")})
print("\nNode được đưa vào top 10 so với node AST bị đẩy ra (A: cao hơn có ý nghĩa, B: không khác, C: thấp hơn có ý nghĩa)")
display(pd.DataFrame(_sw))

print("\nH3 theo judge: DOC so với AST, tách theo issue có gọi tên gold")
for v, name in ((0, "không gọi tên gold"), (1, "gọi tên gold")):
    g = JM[JM["issue_names_gold"] == v]
    print(f"Issue {name}: {len(g)} instance"); display(compare_judge(g, "DOC", "AST", f"DOC so với AST, issue {name}"))

_cmp = JM.merge(sdf[["Instance", "AST_func", "DOC_func", "HIST_func"]], on="Instance")
for s in ("AST", "DOC", "HIST"):
    hit = _cmp[f"{s}_func"].map(lambda x: int(not pd.isna(x) and x <= 10))
    print(f"{s}: Strict@10 (judge) trùng Hit@10 (gold) ở {(hit == _cmp[f'Strict@10_{s}']).mean():.1%} instance")

# ── B. Chunk doc: doc lấy được có liên quan không, và lỗi nằm ở bước nào ─────────────────────────────────────
JD = element_table("doc", ("DOC", "RAND", "ALL"))
print("\nChunk doc: tỷ lệ instance có ít nhất 1 chunk liên quan (điểm ≥ 2) và điểm TB của chunk, theo nguồn")
display(JD.groupby("Repo").agg(**{"Instance": ("Instance", "size"), "Có chunk liên quan: DOC": ("lq_DOC", "mean"),
                                  "Có chunk liên quan: RAND": ("lq_RAND", "mean"),
                                  "Có chunk liên quan: toàn bộ doc": ("lq_ALL", "mean"),
                                  "Điểm TB chunk DOC": ("tb_DOC", "mean"), "Điểm TB chunk RAND": ("tb_RAND", "mean"),
                                  "Điểm TB chunk toàn bộ doc": ("tb_ALL", "mean")}).round(3))
display(mcnemar_by_repo(JD, "lq_DOC", "lq_RAND", "Có chunk liên quan: DOC / RAND"))
_d = (JD.merge(sdf[["Instance", "B2_vote_ast"]], on="Instance")
        .merge(JM[["Instance", "nDCG_DOC", "nDCG_AST"]], on="Instance"))
_d["Δ nDCG@10 (DOC − AST)"] = _d["nDCG_DOC"] - _d["nDCG_AST"]
# Chunk liên quan (điểm ≥ 2) trong danh sách tìm trên toàn bộ doc có cạnh Documents hay không
_tg = {r["Instance"]: dict(zip(r["doc_chunks_all"], r["doc_chunks_all_targets"])) for _, r in sdf.iterrows()}
def _all_rel_linked(key):
    sc, meta = _scores(key), POOL[key]
    rel = [it["node"] for it in meta["items"] if "ALL" in it["systems"] and sc[it["node"]] >= 2]
    return int(any(_tg[meta["Instance"]].get(c) for c in rel))
_d["lq_ALL_có_cạnh"] = _d["Instance"].map({v["Instance"]: _all_rel_linked(k) for k, v in POOL.items()
                                          if v["kind"] == "doc" and k in LAB})
_d["Nhóm"] = np.select(
    [(_d["lq_DOC"] == 1) & (_d["B2_vote_ast"] == 1), _d["lq_DOC"] == 1,
     (_d["lq_ALL"] == 1) & (_d["lq_ALL_có_cạnh"] == 1), _d["lq_ALL"] == 1],
    ["1. DOC lấy được chunk liên quan, tập doc chứa gold",
     "2. DOC lấy được chunk liên quan, tập doc không chứa gold (cạnh nối chưa dẫn tới gold)",
     "3a. Chunk liên quan có cạnh Documents, nhưng DOC xếp ngoài top EXP_N_DOC",
     "3b. Chunk liên quan không có cạnh Documents (phương pháp không nối được tới code)"],
    "4. Không tìm được chunk liên quan")
print("\nNhóm nguyên nhân theo chunk doc (số instance, tỷ lệ, Δ nDCG@10 TB của DOC so với AST)")
display(_d.groupby(["Repo", "Nhóm"]).agg(**{"Instance": ("Instance", "size"),
                                            "Δ nDCG@10 TB": ("Δ nDCG@10 (DOC − AST)", "mean")})
          .assign(**{"Tỷ lệ": lambda t: (t["Instance"] / t.groupby(level=0)["Instance"].transform("sum")).round(3)})
          .round(4))

# ── C. Commit: history lấy được có liên quan không, và lỗi nằm ở bước nào (đối xứng với phần B) ────────────────
# Điểm của commit gộp từ request commit (HIST, RAND_HIST) và request toàn bộ history (#histall). Danh sách "toàn bộ
# history" (cell hist-all) tìm trên mọi commit là tổ tiên của snapshot, không qua bộ lọc của HIST.
def commit_scores(iid):
    sc = {}
    for kind in ("hist", "histall"):
        if f"{iid}#{kind}" in LAB:
            sc.update(_scores(f"{iid}#{kind}"))
    return sc

_rc = []
for _, r in sdf.iterrows():
    iid, sc = r["Instance"], commit_scores(r["Instance"])
    if not sc:
        continue
    hist = [h for h, _ in r["hist_commits_vote"][:_k_hist]]
    lists = {"HIST": hist, "RAND_HIST": r["hist_commits_random"][:_k_hist], "ALL": [c["h"] for c in HIST_ALL.get(iid, [])]}
    row = {"Instance": iid, "Repo": r["Repo"]}
    for gname, lst in lists.items():
        v = [sc[h] for h in lst if h in sc]
        row[f"lq_{gname}"] = int(bool(v) and max(v) >= 2)
        row[f"tb_{gname}"] = np.mean(v) if v else np.nan
    rel = [c for c in HIST_ALL.get(iid, []) if sc.get(c["h"], 0) >= 2 and c["h"] not in set(hist)]
    row["Lý do"] = ("dùng được" if any(c["reason"] == _REASONS[0] for c in rel) else
                    "bị bộ lọc loại" if any(c["reason"] in _REASONS[1:3] for c in rel) else
                    "không sửa hàm/lớp trong snapshot" if rel else "")
    _rc.append(row)
JH = pd.DataFrame(_rc)
print(f"\nCommit ({_k_hist} commit cho HIST và RAND_HIST, {HIST_ALL_N} commit cho toàn bộ history): tỷ lệ instance có ít "
      "nhất 1 commit liên quan (điểm ≥ 2) và điểm TB")
display(JH.groupby("Repo").agg(**{"Instance": ("Instance", "size"), "Có commit liên quan: HIST": ("lq_HIST", "mean"),
                                  "Có commit liên quan: RAND_HIST": ("lq_RAND_HIST", "mean"),
                                  "Có commit liên quan: toàn bộ history": ("lq_ALL", "mean"),
                                  "Điểm TB commit HIST": ("tb_HIST", "mean"),
                                  "Điểm TB commit RAND_HIST": ("tb_RAND_HIST", "mean"),
                                  "Điểm TB commit toàn bộ history": ("tb_ALL", "mean")}).round(3))
display(mcnemar_by_repo(JH, "lq_HIST", "lq_RAND_HIST", "Có commit liên quan: HIST / RAND_HIST"))
_ca = pd.DataFrame([{"Repo": r["Repo"], "Lý do": c["reason"], "Liên quan (điểm ≥ 2)": commit_scores(r["Instance"]).get(c["h"], -1) >= 2}
                    for _, r in sdf.iterrows() for c in HIST_ALL.get(r["Instance"], [])
                    if c["h"] in commit_scores(r["Instance"])])
print("\nCommit của danh sách toàn bộ history: số commit và tỷ lệ liên quan, theo lý do có hoặc không được HIST dùng")
display(_ca.groupby(["Repo", "Lý do"]).agg(**{"Số commit": ("Liên quan (điểm ≥ 2)", "size"),
                                              "Tỷ lệ liên quan": ("Liên quan (điểm ≥ 2)", "mean")}).round(3))
_h = (JH.merge(sdf[["Instance", f"B2_vote_hist{_k_hist}_ast"]], on="Instance")
        .merge(JM[["Instance", "nDCG_HIST", "nDCG_AST"]], on="Instance"))
_h["Δ nDCG@10 (HIST − AST)"] = _h["nDCG_HIST"] - _h["nDCG_AST"]
_h["Nhóm"] = np.select(
    [(_h["lq_HIST"] == 1) & (_h[f"B2_vote_hist{_k_hist}_ast"] == 1), _h["lq_HIST"] == 1,
     (_h["lq_ALL"] == 1) & (_h["Lý do"] == "dùng được"), (_h["lq_ALL"] == 1) & (_h["Lý do"] == "bị bộ lọc loại"),
     (_h["lq_ALL"] == 1) & (_h["Lý do"] == "không sửa hàm/lớp trong snapshot")],
    ["1. HIST lấy được commit liên quan, tập history chứa gold",
     "2. HIST lấy được commit liên quan, tập history không chứa gold (commit không sửa gold)",
     "3a. Commit liên quan qua được bộ lọc, nhưng HIST xếp ngoài top k",
     "3b. Commit liên quan bị bộ lọc loại (ngoài cửa sổ thời gian hoặc sửa quá nhiều hàm/lớp)",
     "3c. Commit liên quan không sửa hàm/lớp nào còn trong snapshot"],
    "4. Không tìm được commit liên quan")
print("\nNhóm nguyên nhân theo commit (số instance, tỷ lệ, Δ nDCG@10 TB của HIST so với AST)")
display(_h.groupby(["Repo", "Nhóm"]).agg(**{"Instance": ("Instance", "size"),
                                            "Δ nDCG@10 TB": ("Δ nDCG@10 (HIST − AST)", "mean")})
          .assign(**{"Tỷ lệ": lambda t: (t["Instance"] / t.groupby(level=0)["Instance"].transform("sum")).round(3)})
          .round(4))

Bỏ qua cell của v3 (RUN_V3 = False)

### 6b. Đánh giá theo chuỗi của từng nguồn (kiến trúc v3)

Mỗi nguồn đi qua một chuỗi ba bước: lấy bằng chứng (chunk doc hoặc commit), nối bằng chứng tới code (cạnh `Documents` hoặc `Modifies`), rồi kết hợp vào xếp hạng. Các độ đo ở Section 5 và 6 chỉ đo kết quả cuối. Cell `eval-v3` đo từng bước, để biết khi một nguồn không giúp thì lỗi nằm ở đâu, và mỗi nguồn đóng góp bao nhiêu.

- **Tầng 1, chất lượng bằng chứng.** Dùng điểm judge của chunk và commit: Success@k (có ít nhất một phần tử điểm ≥ 2), Precision@k, nDCG@k theo thứ tự lấy về, và recall theo pool (phần tử liên quan lấy được chia cho mọi phần tử liên quan đã chấm của instance). RAND và RAND_HIST là đối chứng. Danh sách "toàn bộ doc" (chunk tìm trên mọi chunk, kể cả chunk không có cạnh) và "toàn bộ history" (commit tìm trên mọi tổ tiên của snapshot, không qua bộ lọc của HIST) cho biết nguồn có chứa thông tin liên quan hay không, độc lập với phương pháp.
- **Tầng 2, chất lượng liên kết.** Trong các chunk (hoặc commit) liên quan: tỷ lệ có cạnh tới code (độ phủ), và tỷ lệ có cạnh tới gold (độ chính xác). Phần tử không liên quan được đặt cạnh để so.
- **Tầng 3, mức tận dụng khi kết hợp.** Tỷ lệ tận dụng: trong các instance mà tập của nguồn chứa gold nhưng top k của AST chưa có gold, tỷ lệ xếp hạng kết hợp đưa gold vào top k. Tỷ lệ gây hại do chèn: trong các instance mà top k của AST có gold, tỷ lệ xếp hạng kết hợp làm gold rơi khỏi top k.
- **Tầng 4, đóng góp của từng nguồn.** Giá trị Shapley: φ_DOC = ½[(M_DOC − M_AST) + (M_DOC+HIST − M_HIST)], φ_HIST tính đối xứng, và φ_DOC + φ_HIST = M_DOC+HIST − M_AST. Lợi ích riêng: tỷ lệ instance chỉ DOC, chỉ HIST, hoặc cả hai đưa gold vào top 10.
- **Tầng 5, thông tin mới so với issue.** Chia instance theo việc bằng chứng có chỉ tới gold không (doc: chunk lấy về nêu tên gold; commit: commit lấy về đã sửa gold), và issue có nêu tên gold không. Khung lập luận dự đoán tác động dương khi thông tin là mới, và gần 0 khi thông tin trùng với issue.
- **Tầng 6, tổng hợp.** Mức chênh trung bình kèm khoảng tin cậy bootstrap 95%, tính theo instance và theo repo (mỗi repo một phiếu).

Mọi số liệu tính trên tập test, vì cấu hình của HIST và DOC+HIST được chọn trên tập dev. Chỉ số M là nDCG@10 theo judge và reciprocal rank (RR) mức hàm theo gold. Cell không gọi lại truy xuất hay judge.

In [30]:
%%v3
# ── Section 6b: đánh giá theo 6 tầng cho kiến trúc v3 (nguồn doc và history), trên tập test ─────────────────
EVAL_KS = (5, 10)                 # k của tầng 3
BOOT_N  = 2000                    # số lần lấy mẫu lại cho khoảng tin cậy bootstrap 95%
_K     = HIST_METHOD[0]           # số commit HIST dùng (chọn trên tập dev)
_T     = test.set_index("Instance")
_REPOS = sorted(_T["Repo"].unique())
_gold  = {iid: set(r["gold_ids"]) for iid, r in _T.iterrows()}

def boot_ci(x, n=BOOT_N, seed=0):
    """(trung bình, cận 2,5%, cận 97,5%) của trung bình x, bootstrap theo instance; bỏ giá trị thiếu."""
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    if len(x) == 0:
        return np.nan, np.nan, np.nan
    m = x[np.random.default_rng(seed).integers(0, len(x), (n, len(x)))].mean(axis=1)
    return float(x.mean()), float(np.percentile(m, 2.5)), float(np.percentile(m, 97.5))

def _lab_of(key):
    return _scores(key) if key in LAB else None

def _dcg(g):
    return sum((2 ** v - 1) / np.log2(i + 2) for i, v in enumerate(g))

def _hit(col, k):
    return col.map(lambda x: not pd.isna(x) and x <= k)

def _by_repo():
    """[(repo, mặt nạ)] cho từng repo và cho toàn bộ."""
    return [(repo, _T["Repo"] == repo) for repo in _REPOS] + [("Tất cả", pd.Series(True, index=_T.index))]

_J = JM.set_index("Instance").reindex(_T.index)
METRICS = {"nDCG@10 (judge)": lambda s: _J[f"nDCG_{s}"],
           "RR mức hàm (gold)": lambda s: _T[f"{s}_func"].map(lambda x: 0.0 if pd.isna(x) else 1.0 / x)}

# ── Tầng 1: chất lượng bằng chứng (judge) ─────────────────────────────────────────────────────────────────
_ev = []
for iid, r in _T.iterrows():
    for kind, sc, lists in (
            ("Chunk doc", _lab_of(f"{iid}#doc"), (("DOC", r["doc_chunks_vote_ast"]), ("RAND", r["doc_chunks_random_ast"]),
                                                   ("Toàn bộ doc", r["doc_chunks_all"]))),
            ("Commit", commit_scores(iid), (("HIST", [h for h, _ in r["hist_commits_vote"][:_K]]),
                                            ("RAND_HIST", r["hist_commits_random"][:_K]),
                                            ("Toàn bộ history", [c["h"] for c in HIST_ALL.get(iid, [])])))):
        if not sc:
            continue
        pool = list(sc.values())
        n_rel = sum(v >= 2 for v in pool)
        for name, lst in lists:
            g = [sc[x] for x in lst if x in sc]
            if not g:
                continue
            ideal = _dcg(sorted(pool, reverse=True)[:len(g)])
            _ev.append({"Loại": kind, "Repo": r["Repo"], "Nguồn": name, "Instance": iid,
                        "Success@k": int(any(v >= 2 for v in g)), "Precision@k": np.mean([v >= 2 for v in g]),
                        "nDCG@k": _dcg(g) / ideal if ideal else 0.0,
                        "Recall theo pool": sum(v >= 2 for v in g) / n_rel if n_rel else np.nan})
EV = pd.DataFrame(_ev)
print(f"Tầng 1. Chất lượng bằng chứng theo judge (k = số phần tử nguồn lấy về; commit: {_K} commit), tập test")
display(EV.groupby(["Loại", "Repo", "Nguồn"])[["Success@k", "Precision@k", "nDCG@k", "Recall theo pool"]].mean().round(3))
_t1 = []
for kind, a, b in (("Chunk doc", "DOC", "RAND"), ("Commit", "HIST", "RAND_HIST")):
    w = EV[EV["Loại"] == kind].pivot_table(index=["Repo", "Instance"], columns="Nguồn", values="nDCG@k")
    if a not in w.columns or b not in w.columns:
        continue
    w = w.dropna(subset=[a, b])
    for repo, g in w.groupby(level=0):
        d = g[a] - g[b]
        _t1.append({"Loại": kind, "Repo": repo, "So sánh": f"{a} so với {b}, nDCG@k", "Tốt hơn": int((d > 0).sum()),
                    "Kém hơn": int((d < 0).sum()), "p (Wilcoxon)": round(wilcoxon(g[a], g[b]).pvalue, 4) if (d != 0).any() else 1.0})
display(pd.DataFrame(_t1))

# ── Tầng 2: chất lượng liên kết (gold) ─────────────────────────────────────────────────────────────────
_lk = []
for iid, r in _T.iterrows():
    sc = _lab_of(f"{iid}#doc")
    if sc is not None:
        for name, ids, tgs in (("DOC", r["doc_chunks_vote_ast"], r["doc_chunk_targets_vote_ast"]),
                               ("Toàn bộ doc", r["doc_chunks_all"], r["doc_chunks_all_targets"])):
            for c, tg in zip(ids, tgs):
                if c in sc:
                    _lk.append({"Loại": "Chunk doc", "Repo": r["Repo"], "Nguồn": name, "Liên quan (điểm ≥ 2)": sc[c] >= 2,
                                "Có cạnh tới code": bool(tg), "Có cạnh tới gold": bool(set(tg) & _gold[iid])})
    sc = commit_scores(iid)
    if sc:
        info = {c["h"]: c for c in HIST_ALL.get(iid, [])}
        for name, lst in (("HIST", [h for h, _ in r["hist_commits_vote"][:_K]]), ("Toàn bộ history", list(info))):
            for h in lst:
                if h in sc:
                    tg = _units[r["Repo"]][h]["touch"]
                    _lk.append({"Loại": "Commit", "Repo": r["Repo"], "Nguồn": name, "Liên quan (điểm ≥ 2)": sc[h] >= 2,
                                "Có cạnh tới code": info[h]["n_fc"] >= 1 if name == "Toàn bộ history" else True,
                                "Có cạnh tới gold": bool(set(tg) & _gold[iid])})
LK = pd.DataFrame(_lk)
print("\nTầng 2. Chất lượng liên kết: độ phủ (có cạnh tới code) và độ chính xác (có cạnh tới gold), theo mức liên quan")
display(LK.groupby(["Loại", "Repo", "Nguồn", "Liên quan (điểm ≥ 2)"])
          .agg(**{"Số phần tử": ("Có cạnh tới code", "size"), "Độ phủ liên kết": ("Có cạnh tới code", "mean"),
                  "Độ chính xác liên kết": ("Có cạnh tới gold", "mean")}).round(3))

# ── Tầng 3: mức tận dụng và gây hại khi kết hợp (gold, mức hàm) ───────────────────────────────────────────
_b2 = {"DOC": _T["B2_vote_ast"] == 1, "RAND": _T["B2_random_ast"] == 1,
       "HIST": _T[f"B2_vote_hist{_K}_ast"] == 1, "RAND_HIST": _T[f"B2_random_hist{_K}_ast"] == 1,
       "DOC+HIST": (_T["B2_vote_ast"] == 1) | (_T[f"B2_vote_hist{_K}_ast"] == 1)}
_ut = []
for k in EVAL_KS:
    ast_hit = _hit(_T["AST_func"], k)
    for s, b2 in _b2.items():
        s_hit = _hit(_T[f"{s}_func"], k)
        for repo, m in _by_repo():
            pot, had = m & b2 & ~ast_hit, m & ast_hit
            _ut.append({"k": k, "Hệ thống": s, "Repo": repo, "Instance tiềm năng": int(pot.sum()),
                        "Tỷ lệ tận dụng": s_hit[pot].mean() if pot.any() else np.nan,
                        "Instance AST có gold": int(had.sum()),
                        "Tỷ lệ gây hại do chèn": (~s_hit[had]).mean() if had.any() else np.nan})
print("\nTầng 3. Tỷ lệ tận dụng tiềm năng (tập nguồn chứa gold, AST chưa có trong top k) và tỷ lệ gây hại do chèn")
display(pd.DataFrame(_ut).round(3))

# ── Tầng 4: đóng góp của từng nguồn (Shapley) và lợi ích riêng ──────────────────────────────────────────
_sh = []
for mname, f in METRICS.items():
    A, D, H, DH = f("AST"), f("DOC"), f("HIST"), f("DOC+HIST")
    for src, v in (("DOC", 0.5 * ((D - A) + (DH - H))), ("HIST", 0.5 * ((H - A) + (DH - D)))):
        for repo, m in _by_repo():
            mean, lo, hi = boot_ci(v[m])
            _sh.append({"Chỉ số": mname, "Nguồn": src, "Repo": repo, "Instance": int(v[m].notna().sum()),
                        "Shapley TB": mean, "CI 2,5%": lo, "CI 97,5%": hi})
print("\nTầng 4. Giá trị Shapley của từng nguồn (đóng góp trung bình khi có và khi không có nguồn kia), CI bootstrap 95%")
display(pd.DataFrame(_sh).round(4))
_a10 = _hit(_T["AST_func"], 10)
_gd, _gh = ~_a10 & _hit(_T["DOC_func"], 10), ~_a10 & _hit(_T["HIST_func"], 10)
_ex = pd.DataFrame({"Repo": _T["Repo"], "Chỉ DOC đưa gold vào top 10": _gd & ~_gh, "Chỉ HIST đưa vào": _gh & ~_gd,
                    "Cả hai cùng đưa vào": _gd & _gh, "DOC+HIST đưa vào": ~_a10 & _hit(_T["DOC+HIST_func"], 10)})
print("Lợi ích riêng: tỷ lệ instance mà top 10 của AST chưa có gold, và nguồn đưa được gold vào top 10")
display(_ex.groupby("Repo").mean().round(3))

# ── Tầng 5: thông tin mới so với issue ────────────────────────────────────────────────────────────────
_GRP = ("Thông tin mới: bằng chứng chỉ tới gold, issue không nêu tên gold",
        "Thông tin trùng: bằng chứng chỉ tới gold, issue cũng nêu tên gold", "Bằng chứng không chỉ tới gold")
_points = {"DOC": _T["B1_vote_ast"] == 1,                       # chunk DOC lấy về nêu tên gold (text hoặc cạnh)
           "HIST": _T[f"B2_vote_hist{_K}_ast"] == 1}            # commit HIST lấy về đã sửa gold
_named = _T["issue_names_gold"] == 1
_nv = []
for src, pts in _points.items():
    grp = pd.Series(np.select([pts & ~_named, pts], _GRP[:2], _GRP[2]), index=_T.index)
    for mname, f in METRICS.items():
        d = f(src) - f("AST")
        for repo, m in _by_repo():
            for gname in _GRP:
                mean, lo, hi = boot_ci(d[m & (grp == gname)])
                _nv.append({"Nguồn": src, "Chỉ số": f"Δ {mname} so với AST", "Repo": repo, "Nhóm": gname,
                            "Instance": int((m & (grp == gname)).sum()), "Δ TB": mean, "CI 2,5%": lo, "CI 97,5%": hi})
print("\nTầng 5. Mức chênh so với AST theo việc bằng chứng mang thông tin mới hay trùng với issue")
display(pd.DataFrame(_nv).round(4))

# ── Tầng 6: tổng hợp, CI bootstrap 95%, theo instance và theo repo ───────────────────────────────────────
_ag = []
for a, b in PAIRS:
    for mname, f in METRICS.items():
        d = f(a) - f(b)
        mean, lo, hi = boot_ci(d)
        _ag.append({"So sánh": f"{a} so với {b}", "Chỉ số": mname, "Instance": int(d.notna().sum()),
                    "Δ TB theo instance": mean, "CI 2,5%": lo, "CI 97,5%": hi,
                    "Δ TB theo repo (mỗi repo 1 phiếu)": np.nanmean([d[_T["Repo"] == repo].mean() for repo in _REPOS])})
print("\nTầng 6. Mức chênh trung bình giữa các hệ thống, CI bootstrap 95% (tính theo instance) và trung bình theo repo")
display(pd.DataFrame(_ag).round(4))

Bỏ qua cell của v3 (RUN_V3 = False)

### 6c. Kiểm chứng: dữ liệu đa nguồn so với chỉ source code

Mục tiêu của đề tài là chứng minh dữ liệu đa nguồn (source code cùng document và git history) hiệu quả hơn khi chỉ dùng source code (AST). Cell `verify-v3` trả lời trực tiếp các câu hỏi kiểm chứng trên tập test, theo từng repo và gộp cả hai repo:

- **A. Câu hỏi chính.** Q1 code + doc so với AST; Q2 code + history so với AST; Q3 code + doc + history so với AST; Q4 doc + history so với chỉ doc; Q5 doc + history so với chỉ history. Mỗi câu có nDCG@10 theo judge (Wilcoxon), Hit@10 theo gold (McNemar) và RR theo gold (Wilcoxon), kèm mức chênh trung bình và khoảng tin cậy bootstrap 95%.
- **B. Phạm vi tác động so với AST.** Tỷ lệ instance tốt hơn, kém hơn, không đổi; tỷ lệ đưa gold vào top 10 khi AST trượt; tỷ lệ làm gold rơi khỏi top 10; phần tác động dương chỉ do doc, chỉ do history, hoặc do cả hai.
- **C. Theo độ khó với AST.** Chia instance theo hạng của gold trong AST: trong top 10, hạng 11 đến 100, ngoài top 100.
- **D. Độ nhạy theo cấu hình.** Mức chênh so với AST ở mọi cấu hình kết hợp trên tập test (theo gold), và phép so DOC với HIST ở cùng cấu hình.
- **E. Theo issue có nêu tên gold (H3)**, cho DOC, HIST và DOC+HIST.
- **F. Ví dụ minh họa** cho các trường hợp đa nguồn giúp nhờ doc, giúp nhờ history, và gây hại.
- **G. Vì sao history đóng góp nhiều hơn doc.** Độ phủ của cạnh tới gold (doc: cạnh `Documents`; history: cạnh `Modifies` của commit dùng được), và mức trùng từ giữa issue với chunk doc và với message commit.

Cell chỉ dùng dữ liệu đã có của Section 5 và 6, không gọi lại truy xuất hay judge.

In [31]:
%%v3
# ── Section 6c: kiểm chứng đa nguồn so với chỉ source code (AST), trên tập test ──────────────────────────────
import re as _re
VERIFY_EX_N = 2                    # số ví dụ minh họa mỗi nhóm
_T = test.set_index("Instance")
_J = JM.set_index("Instance").reindex(_T.index)
_REPOS = sorted(_T["Repo"].unique())
_MASKS = [(r, _T["Repo"] == r) for r in _REPOS] + [("Tất cả", pd.Series(True, index=_T.index))]
_rrs = lambda s: _T[f"{s}_func"].map(lambda x: 0.0 if pd.isna(x) else 1.0 / x)
_h10 = lambda s: _T[f"{s}_func"].map(lambda x: not pd.isna(x) and x <= 10)
_nd = lambda s: _J[f"nDCG_{s}"]

def _verdict(d_lo, d_hi):
    return "Có (tốt hơn có ý nghĩa)" if d_lo > 0 else ("Kém hơn có ý nghĩa" if d_hi < 0 else "Chưa có ý nghĩa")

# ── A. Câu hỏi chính ──────────────────────────────────────────────────────────────────────────────────
QUESTIONS = [("Q1. Code + doc so với chỉ code", "DOC", "AST"),
             ("Q2. Code + history so với chỉ code", "HIST", "AST"),
             ("Q3. Code + doc + history so với chỉ code", "DOC+HIST", "AST"),
             ("Q4. Doc + history so với chỉ doc", "DOC+HIST", "DOC"),
             ("Q5. Doc + history so với chỉ history", "DOC+HIST", "HIST")]
_qa = []
for q, a, b in QUESTIONS:
    for repo, m in _MASKS:
        for mname, xa, xb in (("nDCG@10 (judge)", _nd(a), _nd(b)), ("RR mức hàm (gold)", _rrs(a), _rrs(b))):
            ok = m & xa.notna() & xb.notna()
            d = xa[ok] - xb[ok]
            mean, lo, hi = boot_ci(d)
            nz = (d != 0).any()
            _qa.append({"Câu hỏi": q, "Repo": repo, "Chỉ số": mname, "Hệ thống": round(xa[ok].mean(), 4),
                        "Mốc": round(xb[ok].mean(), 4), "Tốt hơn": int((d > 0).sum()), "Kém hơn": int((d < 0).sum()),
                        "p": wilcoxon(xa[ok], xb[ok]).pvalue if nz else 1.0, "Δ TB": mean, "CI 2,5%": lo, "CI 97,5%": hi,
                        "Kết luận": _verdict(lo, hi)})
        ha, hb = _h10(a)[m].astype(int), _h10(b)[m].astype(int)
        up, down, p = mcnemar(ha, hb)
        _qa.append({"Câu hỏi": q, "Repo": repo, "Chỉ số": "Hit@10 (gold)", "Hệ thống": round(ha.mean(), 4),
                    "Mốc": round(hb.mean(), 4), "Tốt hơn": up, "Kém hơn": down, "p": p, "Δ TB": ha.mean() - hb.mean(),
                    "CI 2,5%": np.nan, "CI 97,5%": np.nan,
                    "Kết luận": ("Có (tốt hơn có ý nghĩa)" if p < 0.05 and up > down else
                                 "Kém hơn có ý nghĩa" if p < 0.05 and down > up else "Chưa có ý nghĩa")})
QA = pd.DataFrame(_qa)
QA["p"] = QA["p"].round(4)
print("A. Câu hỏi kiểm chứng chính (tập test). Hệ thống là vế trái của câu hỏi, Mốc là vế phải.")
display(QA.round(4))

# ── B. Phạm vi tác động so với AST ────────────────────────────────────────────────────────────────────
_a10 = _h10("AST")
_imp = []
for s in ("DOC", "HIST", "DOC+HIST"):
    dj, dr, s10 = _nd(s) - _nd("AST"), _rrs(s) - _rrs("AST"), _h10(s)
    for repo, m in _MASKS:
        mj = m & dj.notna()
        _imp.append({"Hệ thống": s, "Repo": repo,
                     "Judge tốt hơn": (dj[mj] > 0).mean(), "Judge kém hơn": (dj[mj] < 0).mean(),
                     "Judge không đổi": (dj[mj] == 0).mean(),
                     "Gold RR tốt hơn": (dr[m] > 0).mean(), "Gold RR kém hơn": (dr[m] < 0).mean(),
                     "Đưa gold vào top 10 khi AST trượt": s10[m & ~_a10].mean(),
                     "Làm gold rơi khỏi top 10": (~s10[m & _a10]).mean()})
print("\nB. Phạm vi tác động so với AST: tỷ lệ instance (tập test)")
display(pd.DataFrame(_imp).round(3))
_upd, _uph = (_nd("DOC") - _nd("AST")) > 0, (_nd("HIST") - _nd("AST")) > 0
_gd, _gh = ~_a10 & _h10("DOC"), ~_a10 & _h10("HIST")
_ov = []
for repo, m in _MASKS:
    mj = m & _J["nDCG_AST"].notna()
    miss = m & ~_a10
    _ov.append({"Repo": repo,
                "Judge: chỉ doc làm tốt hơn": (_upd & ~_uph)[mj].mean(), "Judge: chỉ history": (~_upd & _uph)[mj].mean(),
                "Judge: cả hai": (_upd & _uph)[mj].mean(),
                "Gold (khi AST trượt top 10): chỉ doc cứu": (_gd & ~_gh)[miss].mean(),
                "Gold: chỉ history cứu": (~_gd & _gh)[miss].mean(), "Gold: cả hai cùng cứu": (_gd & _gh)[miss].mean(),
                "Gold: DOC+HIST cứu": (~_a10 & _h10("DOC+HIST"))[miss].mean()})
print("Phần tác động dương do từng nguồn: bổ sung nhau hay trùng nhau (tỷ lệ instance)")
display(pd.DataFrame(_ov).round(3))

# ── C. Theo độ khó với AST ────────────────────────────────────────────────────────────────────────────
_bk = _T["AST_func"].map(lambda x: "1. AST đã có gold trong top 10" if (not pd.isna(x) and x <= 10) else
                         "2. Gold ở hạng 11 đến 100 của AST" if not pd.isna(x) else "3. Gold ngoài top 100 của AST")
_df = []
for b in sorted(_bk.unique()):
    for repo, m in _MASKS:
        mb = m & (_bk == b)
        row = {"Độ khó": b, "Repo": repo, "Instance": int(mb.sum()), "Hit@10 AST": _h10("AST")[mb].mean()}
        for s in ("DOC", "HIST", "DOC+HIST"):
            row[f"Hit@10 {s}"] = _h10(s)[mb].mean()
            row[f"Δ nDCG@10 {s}"] = (_nd(s) - _nd("AST"))[mb].mean()
            row[f"Δ RR {s}"] = (_rrs(s) - _rrs("AST"))[mb].mean()
        _df.append(row)
print("\nC. Theo độ khó với AST (hạng của gold trong xếp hạng AST), tập test")
display(pd.DataFrame(_df).round(4))

# ── D. Độ nhạy theo cấu hình (gold, tập test) và DOC so với HIST ở cùng cấu hình ─────────────────────────────
_testr = list(test.iterrows())
_ast_t = [level_rank(r["ast_ids"], r, "func") for _, r in _testr]
def _gold_delta(order_fn):
    rk = [level_rank(order_fn(r), r, "func") for _, r in _testr]
    rr = lambda ranks: np.mean([0.0 if x is None else 1.0 / x for x in ranks])
    return _hitk(rk, 10) - _hitk(_ast_t, 10), rr(rk) - rr(_ast_t)
_cfg = []
for p in _RRF_P:
    for h in FUSE_HEADS:
        dh, dr = _gold_delta(lambda r: fused_list(r, "vote_ast", "rrf", p, h))
        _cfg.append({"Hệ thống": "DOC", "k": None, "p": p, "h": h, "ΔHit@10": dh, "ΔRR": dr})
        dh, dr = _gold_delta(lambda r: fused_multi(r, [("vote_ast", DOC_METHOD[1]), (f"vote_hist{HIST_METHOD[0]}_ast", p)], h))
        _cfg.append({"Hệ thống": "DOC+HIST", "k": HIST_METHOD[0], "p": p, "h": h, "ΔHit@10": dh, "ΔRR": dr})
        for k in HIST_KS:
            dh, dr = _gold_delta(lambda r: fused_list(r, f"vote_hist{k}_ast", "rrf", p, h))
            _cfg.append({"Hệ thống": "HIST", "k": k, "p": p, "h": h, "ΔHit@10": dh, "ΔRR": dr})
CFG = pd.DataFrame(_cfg)
print("\nD. Mức chênh so với AST ở mọi cấu hình kết hợp, tập test gộp, theo gold")
display(CFG.groupby("Hệ thống").agg(**{"Số cấu hình": ("ΔHit@10", "size"),
                                       "Tỷ lệ cấu hình ΔHit@10 > 0": ("ΔHit@10", lambda v: (v > 0).mean()),
                                       "Tỷ lệ cấu hình ΔRR > 0": ("ΔRR", lambda v: (v > 0).mean()),
                                       "ΔHit@10 nhỏ nhất": ("ΔHit@10", "min"), "ΔHit@10 trung vị": ("ΔHit@10", "median"),
                                       "ΔHit@10 lớn nhất": ("ΔHit@10", "max"), "ΔRR trung vị": ("ΔRR", "median")}).round(4))
_k, _p, _h = HIST_METHOD
_eq = CFG[((CFG["Hệ thống"] == "DOC") & (CFG["p"] == _p) & (CFG["h"] == _h)) |
          ((CFG["Hệ thống"] == "HIST") & (CFG["k"] == _k) & (CFG["p"] == _p) & (CFG["h"] == _h))]
print(f"DOC và HIST ở cùng cấu hình p={_p}, h={_h} (cấu hình đã chọn cho HIST), theo gold:")
display(_eq.round(4))

# ── E. Theo issue có nêu tên gold (H3) ──────────────────────────────────────────────────────────────────
_h3 = []
for v, name in ((0, "Issue không nêu tên gold"), (1, "Issue nêu tên gold")):
    for s in ("DOC", "HIST", "DOC+HIST"):
        for repo, m in _MASKS:
            mv = m & (_T["issue_names_gold"] == v)
            mean, lo, hi = boot_ci((_nd(s) - _nd("AST"))[mv])
            up, down, p = mcnemar(_h10(s)[mv].astype(int), _h10("AST")[mv].astype(int))
            _h3.append({"Nhóm issue": name, "Hệ thống": s, "Repo": repo, "Instance": int(mv.sum()),
                        "Δ nDCG@10 TB": mean, "CI 2,5%": lo, "CI 97,5%": hi,
                        "Hit@10 tốt hơn": up, "Hit@10 kém hơn": down, "p (McNemar)": round(p, 4)})
print("\nE. So với AST, tách theo issue có nêu tên gold, tập test")
display(pd.DataFrame(_h3).round(4))

# ── F. Ví dụ minh họa ─────────────────────────────────────────────────────────────────────────────────
def _elements(key):
    """{node: text} của các phần tử trong prompt (chunk doc hoặc commit), lấy từ request đã gửi judge."""
    if key not in REQ:
        return {}
    txt = REQ[key]["contents"][0]["parts"][0]["text"]
    body = txt.split("\n## Scale")[0]
    parts = _re.split(r"^\[([CDH]\d+)\] ", body, flags=_re.M)
    alias2node = {it["alias"]: it["node"] for it in POOL[key]["items"]}
    return {alias2node[parts[i]]: parts[i + 1].strip() for i in range(1, len(parts) - 1, 2) if parts[i] in alias2node}
def _show_example(iid):
    r, g = _T.loc[iid], set(_T.loc[iid, "gold_ids"])
    print(f"\n  ▸ {iid} | hạng gold: AST {r['AST_func']} → DOC {r['DOC_func']}, HIST {r['HIST_func']}, "
          f"DOC+HIST {r['DOC+HIST_func']} | gold: {sorted(g)[:3]}")
    print("    Issue:", " ".join(_text_of[iid].split())[:300])
    dsc, dtx = _lab_of(f"{iid}#doc") or {}, _elements(f"{iid}#doc")
    for c, tg in zip(r["doc_chunks_vote_ast"], r["doc_chunk_targets_vote_ast"]):
        if dsc.get(c, 0) >= 2:
            print(f"    Chunk doc (judge {dsc[c]}, {'có' if set(tg) & g else 'không có'} cạnh tới gold):",
                  " ".join(dtx.get(c, c).split())[:250])
    csc = commit_scores(iid)
    for h, _ in r["hist_commits_vote"][:HIST_METHOD[0]]:
        if csc.get(h, 0) >= 2:
            u = _units[r["Repo"]][h]
            print(f"    Commit {h} (judge {csc[h]}, {'có' if set(u['touch']) & g else 'không'} sửa gold):",
                  u["msg"].split("\n")[0][:200])
_rng = np.random.default_rng(0)
for title, mask in (("Đa nguồn đưa gold vào top 10 nhờ doc", ~_a10 & _h10("DOC") & _h10("DOC+HIST")),
                    ("Đa nguồn đưa gold vào top 10 nhờ history", ~_a10 & ~_h10("DOC") & _h10("HIST") & _h10("DOC+HIST")),
                    ("Đa nguồn làm gold rơi khỏi top 10", _a10 & ~_h10("DOC+HIST"))):
    ids = list(_T.index[mask])
    print(f"\nF. {title}: {len(ids)} instance trên tập test")
    for iid in _rng.choice(ids, size=min(VERIFY_EX_N, len(ids)), replace=False) if ids else []:
        _show_example(iid)

# ── G. Vì sao history đóng góp nhiều hơn doc ────────────────────────────────────────────────────────────
def _usable_touch(repo, snapshot):
    """Mọi hàm/lớp (key) mà các commit HIST dùng được của snapshot đã sửa."""
    H, s8, rp = HIST[repo], snapshot[:8], repo_path_of(repo)
    anc = set(_git(rp, "rev-list", snapshot).split())
    lab = {n["id"]: n["label"] for n in load_graph_summary(build_graph(snapshot, repo_path=rp))["nodes"]}
    t0, out = _SNAP_CT[(repo, snapshot)] - HIST_YEARS * _YEAR, set()
    for u in H["units"]:
        if u["h"] in anc and u["t"] >= t0:
            tt = [k for k in u["touch"] if lab.get(f"{s8}:{k}") in _FC]
            if 1 <= len(tt) <= HIST_MAX_TOUCH:
                out.update(tt)
    return out
_cov = {}
for (repo, snap), g in _T.assign(_s=_T.index.map(_snap_of)).groupby(["Repo", "_s"]):
    touched = _usable_touch(repo, snap)
    for iid in g.index:
        _cov[iid] = bool(set(_T.loc[iid, "gold_ids"]) & touched)
_G = pd.DataFrame({"Repo": _T["Repo"], "Nhóm doc": _T["Nhóm doc"], "Gold có commit dùng được sửa": pd.Series(_cov)})
print("\nG1. Độ phủ của cạnh tới gold, tập test. Nhóm doc: a = gold có cạnh Documents; b = doc nhắc tên gold nhưng "
      "không có cạnh; b-cls = doc chỉ nói tới lớp chứa gold; c = doc không nhắc tới gold.")
display(pd.concat([pd.crosstab(_G["Repo"], _G["Nhóm doc"], normalize="index"),
                   _G.groupby("Repo")["Gold có commit dùng được sửa"].mean().rename("History: gold có commit dùng được sửa")],
                  axis=1).round(3))
def _toks(s):
    return {t for t in _tokenize_code(s) if len(t) > 2}
_vo = []
for iid, r in _T.iterrows():
    I = _toks(_text_of[iid])
    if not I:
        continue
    dsc, dtx, csc = _lab_of(f"{iid}#doc") or {}, _elements(f"{iid}#doc"), commit_scores(iid)
    for kind, items in (("Chunk doc (DOC)", [(dtx.get(c, ""), dsc.get(c)) for c in r["doc_chunks_vote_ast"]]),
                        ("Commit (HIST)", [(_units[r["Repo"]][h]["msg"], csc.get(h))
                                           for h, _ in r["hist_commits_vote"][:HIST_METHOD[0]]])):
        for text, score in items:
            T_ = _toks(text)
            if T_:
                _vo.append({"Repo": r["Repo"], "Loại": kind, "Liên quan (điểm ≥ 2)": score is not None and score >= 2,
                            "Tỷ lệ từ của phần tử có trong issue": len(I & T_) / len(T_),
                            "Tỷ lệ từ của issue có trong phần tử": len(I & T_) / len(I)})
print("G2. Mức trùng từ giữa issue và phần tử lấy về (từ dài hơn 2 ký tự), tập test")
display(pd.DataFrame(_vo).groupby(["Repo", "Loại", "Liên quan (điểm ≥ 2)"]).mean(numeric_only=True).round(3))

Bỏ qua cell của v3 (RUN_V3 = False)

## 7. Doc giúp khi nào, và chỉ dùng doc khi bằng chứng đủ mạnh

Cell `doc-profile` đặt đặc điểm kho doc của từng repo cạnh mức lợi hoặc hại của doc, để trả lời câu hỏi doc giúp khi nào. Cell `doc-gate` chỉ dùng xếp hạng DOC khi một tín hiệu không dùng gold đủ mạnh, ngược lại giữ xếp hạng AST. Ngưỡng được chọn trên tập dev; kết quả được đánh giá trên tập test bằng cả gold và judge. Cả hai cell chỉ dùng dữ liệu đã có của Section 5 và 6, không gọi lại truy xuất hay judge.

In [32]:
%%v3
# ── Hướng 1: đặc điểm doc của từng repo và mức lợi / hại của doc ───────────────────────────
# Đặc điểm kho doc lấy từ file tóm tắt graph của snapshot có nhiều instance nhất trong repo.
# Mức lợi / hại = trung bình theo instance của (DOC − AST): nDCG@10 và Strict@10 theo judge, điểm judge của node DOC
# đưa vào top 10 trừ node AST bị đẩy ra, Hit@10 và reciprocal rank (RR) theo gold.
# Tương quan Spearman tính trên 12 repo: cỡ mẫu nhỏ, chỉ dùng để mô tả xu hướng.
from collections import Counter
from scipy.stats import spearmanr

_KIND_RE = [("changelog", re.compile(r"changelog|changes|whats_?new|release|history|news|announce|deprecat", re.I)),
            ("api", re.compile(r"(^|/)(api|ref|reference|modules|generated)(/|\.|$)", re.I))]
def doc_kind(path):
    """Loại doc theo đường dẫn file: changelog, api (API reference) hoặc guide (còn lại)."""
    return next((k for k, rx in _KIND_RE if rx.search(path)), "guide")

_snapfull = {(i["repo"], i["snapshot"][:8]): i["snapshot"] for i in SCALE_INSTANCES}
_jm = JM.set_index("Instance")
_rr = lambda col: col.map(lambda x: 0.0 if pd.isna(x) else 1.0 / x)
_h10 = lambda col: col.map(lambda x: int(not pd.isna(x) and x <= 10))
_prof = []
for repo, g in sdf.groupby("Repo"):
    snap8 = g["snapshot"].mode()[0]
    s = load_graph_summary(build_graph(_snapfull[(repo, snap8)], repo_path=repo_path_of(repo)))
    chunks = [n for n in s["nodes"] if n["label"] == "DocChunk"]
    kinds = Counter(doc_kind(n.get("file", "")) for n in chunks)
    n_doc_edges = s["stats"]["edge_types"].get("Documents", 0)
    j = _jm.reindex(g["Instance"]).dropna(subset=["nDCG_DOC"])
    _prof.append({
        "Repo": repo, "Instance": len(g), "Chunk doc": len(chunks),
        "Cạnh Documents / chunk": round(n_doc_edges / max(1, len(chunks)), 2),
        "% chunk api": round(kinds["api"] / max(1, len(chunks)), 2),
        "% chunk guide": round(kinds["guide"] / max(1, len(chunks)), 2),
        "% chunk changelog": round(kinds["changelog"] / max(1, len(chunks)), 2),
        "B1 (chunk lấy về nêu tên gold)": round(g["B1_vote_ast"].mean(), 3),
        "B2 (tập doc chứa gold)": round(g["B2_vote_ast"].mean(), 3),
        "Δ nDCG@10 (judge)": round((j["nDCG_DOC"] - j["nDCG_AST"]).mean(), 4),
        "Δ Strict@10 (judge)": round((j["Strict@10_DOC"] - j["Strict@10_AST"]).mean(), 4),
        "Δ điểm node đổi (judge)": round((j["DOC_vào"] - j["AST_ra"]).mean(), 3),
        "Δ Hit@10 (gold)": round((_h10(g["DOC_func"]) - _h10(g["AST_func"])).mean(), 4),
        "Δ RR (gold)": round((_rr(g["DOC_func"]) - _rr(g["AST_func"])).mean(), 4)})
PROFILE = pd.DataFrame(_prof).sort_values("Δ nDCG@10 (judge)", ascending=False).reset_index(drop=True)
print("Đặc điểm doc và mức lợi / hại của doc theo repo (sắp theo Δ nDCG@10)")
display(PROFILE)

_feat = ["Chunk doc", "Cạnh Documents / chunk", "% chunk api", "% chunk guide", "% chunk changelog",
         "B1 (chunk lấy về nêu tên gold)", "B2 (tập doc chứa gold)"]
_eff = ["Δ nDCG@10 (judge)", "Δ điểm node đổi (judge)", "Δ Hit@10 (gold)", "Δ RR (gold)"]
def _sp(a, b):
    r = spearmanr(a, b)
    return f"{r[0]:.2f} (p={r[1]:.2f})"
print("Tương quan Spearman giữa đặc điểm doc và mức lợi / hại (12 repo)")
display(pd.DataFrame([{"Đặc điểm": f, **{e: _sp(PROFILE[f], PROFILE[e]) for e in _eff}} for f in _feat]))

# Mức instance: doc giúp hay hại tùy chunk lấy về có nêu tên gold không (B1) và tập doc có chứa gold không (B2)
_ji = JM.merge(sdf[["Instance", "B1_vote_ast", "B2_vote_ast"]], on="Instance")
_ji["Δ nDCG@10"] = _ji["nDCG_DOC"] - _ji["nDCG_AST"]
print("Δ nDCG@10 (judge) theo B1 và B2, gộp mọi repo")
display(_ji.groupby(["B1_vote_ast", "B2_vote_ast"])["Δ nDCG@10"].agg(["size", "mean"]).round(4))

Bỏ qua cell của v3 (RUN_V3 = False)

In [33]:
%%v3
# ── Hướng 2: chỉ dùng doc khi bằng chứng của doc đủ mạnh (tín hiệu không dùng gold) ─────────
# Mỗi instance dùng xếp hạng DOC nếu tín hiệu đạt ngưỡng, ngược lại giữ xếp hạng AST. Tín hiệu:
#   agree : số node trong tập doc nằm trong top GATE_K của xếp hạng AST (doc và code cùng chỉ một vùng code)
#   vmax  : điểm doc_votes lớn nhất trong tập doc (độ liên quan của chunk doc tốt nhất)
#   ndoc  : cỡ tập doc (dùng điều kiện ≤: tập doc nhỏ nghĩa là doc chỉ vào một vùng hẹp)
# Ngưỡng thử ở các phân vị 0, 10, ..., 100% trên tập dev. Tiêu chí chọn (đặt trước): theo gold trên tập dev, không âm
# ở mọi Hit@k (k ∈ FUSE_KS) và ΔRR ≥ 0; trong các ngưỡng đạt, chọn ΔHit trung bình lớn nhất. Nếu không có ngưỡng nào
# đạt, chọn ngưỡng có ΔRR lớn nhất. Đánh giá trên tập test bằng gold và judge: xếp hạng sau cổng là DOC hoặc AST,
# cả hai đều đã được judge chấm.
GATE_K = 50

def _signals(r):
    ranks = [x for x in r["doc_r_vote_ast"] if x]
    return {"agree": sum(1 for x in ranks if x <= GATE_K),
            "vmax": max(r["doc_score_vote_ast"], default=0.0),
            "ndoc": len(r["doc_ids_vote_ast"])}

_sig = pd.DataFrame([_signals(r) for _, r in sdf.iterrows()], index=sdf.index)
for col in _sig:
    sdf[f"sig_{col}"] = _sig[col]
dev, test = sdf[sdf["lite"]], sdf[~sdf["lite"]]

def gate_use(df, sig, thr, op):
    return df[f"sig_{sig}"] >= thr if op == ">=" else df[f"sig_{sig}"] <= thr

_grid = []
for sig, op in (("agree", ">="), ("vmax", ">="), ("ndoc", "<=")):
    for thr in sorted(set(float(dev[f"sig_{sig}"].quantile(q)) for q in np.linspace(0, 1, 11))):
        use = gate_use(dev, sig, thr, op)
        rk = dev["DOC_func"].where(use, dev["AST_func"])
        d = {k: _hitk(list(rk), k) - _hitk(list(dev["AST_func"]), k) for k in FUSE_KS}
        drr = float((_rr(rk) - _rr(dev["AST_func"])).mean())
        _grid.append({"Tín hiệu": sig, "Điều kiện": op, "Ngưỡng": round(thr, 5), "Dùng doc (%)": round(100 * use.mean(), 1),
                      **{f"ΔHit@{k}": round(v, 4) for k, v in d.items()}, "ΔHit TB": round(np.mean(list(d.values())), 4),
                      "ΔRR": round(drr, 4), "Không âm": bool(min(d.values()) >= 0 and drr >= 0)})
_grid = pd.DataFrame(_grid)
_okg = _grid[_grid["Không âm"]]
_pick = (_okg.sort_values(["ΔHit TB", "ΔRR"], ascending=False) if len(_okg)
         else _grid.sort_values("ΔRR", ascending=False)).iloc[0]
GATE = (_pick["Tín hiệu"], float(_pick["Ngưỡng"]), _pick["Điều kiện"])
print(f"Tập dev: {len(dev)} instance | {len(_okg)}/{len(_grid)} ngưỡng không âm")
display(_grid.sort_values(["Không âm", "ΔHit TB", "ΔRR"], ascending=False).head(12))
print(f"Cổng được chọn: {GATE[0]} {GATE[2]} {GATE[1]}" + ("" if len(_okg) else "  (không có ngưỡng nào không âm)"))

sdf["gate_use"] = gate_use(sdf, GATE[0], GATE[1], GATE[2])
sdf["GATE_func"] = sdf["DOC_func"].where(sdf["gate_use"], sdf["AST_func"])
dev, test = sdf[sdf["lite"]], sdf[~sdf["lite"]]
print(f"\nTập test ({len(test)} instance): dùng doc ở {test['gate_use'].mean():.1%} instance")
print("Theo repo:", test.groupby("Repo")["gate_use"].mean().round(2).to_dict())

# Gold: cổng so với AST, gộp và theo repo
print("\nGold, mức hàm: cổng so với AST, gộp 12 repo")
display(compare_ranks(test.assign(Repo="Tất cả"), "GATE_func", "AST_func", "Cổng so với AST"))

# Judge: xếp hạng sau cổng lấy điểm của DOC hoặc AST
_jt = JM.merge(sdf[["Instance", "gate_use", "lite"]], on="Instance")
_jt = _jt[~_jt["lite"]].copy()
_jt["nDCG_GATE"] = _jt["nDCG_DOC"].where(_jt["gate_use"], _jt["nDCG_AST"])
for m in ("Rel", "Strict"):
    for k in (1, 5, 10):
        _jt[f"{m}@{k}_GATE"] = _jt[f"{m}@{k}_DOC"].where(_jt["gate_use"], _jt[f"{m}@{k}_AST"])
print("Judge: cổng so với AST, gộp 12 repo")
display(compare_judge(_jt.assign(Repo="Tất cả"), "GATE", "AST", "Cổng so với AST"))

# Theo repo: DOC không cổng và DOC có cổng, so với AST (trung bình Δ và TRisk với alpha = 1)
_t = test.set_index("Instance")
_rows = []
for repo, g in _jt.groupby("Repo"):
    gg = _t.loc[g["Instance"]]
    _rows.append({"Repo": repo, "Dùng doc (%)": round(100 * g["gate_use"].mean(), 1),
                  "Δ nDCG DOC": round((g["nDCG_DOC"] - g["nDCG_AST"]).mean(), 4),
                  "Δ nDCG cổng": round((g["nDCG_GATE"] - g["nDCG_AST"]).mean(), 4),
                  "TRisk nDCG DOC": urisk(g["nDCG_DOC"], g["nDCG_AST"], 1)[1],
                  "TRisk nDCG cổng": urisk(g["nDCG_GATE"], g["nDCG_AST"], 1)[1],
                  "TRisk RR DOC (gold)": urisk(_rr(gg["DOC_func"]), _rr(gg["AST_func"]), 1)[1],
                  "TRisk RR cổng (gold)": urisk(_rr(gg["GATE_func"]), _rr(gg["AST_func"]), 1)[1]})
print("Theo repo: doc không cổng và doc có cổng, so với AST. TRisk < −2: kém hơn AST có ý nghĩa")
display(pd.DataFrame(_rows).sort_values("Δ nDCG DOC", ascending=False).reset_index(drop=True))

Bỏ qua cell của v3 (RUN_V3 = False)

## 8. Thực nghiệm v4: nguồn HIST theo Locus

Phần này chạy thực nghiệm v4 trên Django và SymPy. Kết quả nằm riêng trong `V4_DIR`, nên file của v3 không bị đè. Thiết kế đầy đủ nằm ở `planning.md` và `pipeline_design.md`.

Cờ `RUN_V3` ở cell cấu hình đầu notebook quyết định các cell chỉ phục vụ v3 có chạy hay không. Các cell đó có dòng đầu là `%%v3`. Khi `RUN_V3 = False`, chúng in một dòng thông báo rồi bỏ qua. Nhờ vậy Run All hoặc Save Version không chạy lại truy hồi v3, và không gửi lại batch judge v3.

Lượt 1 trên Kaggle chạy từ đầu notebook tới hết phần này. Các cell chính của lượt 1 như sau.

- `hist-build` dựng lớp history bằng oracle mới, ghi vào `history/<repo>_history_v2.jsonl`.
- `v4-run` chạy lại truy hồi với oracle mới và lưu 500 id AST cho mỗi instance, ghi vào `scale_rows_v4.jsonl`.
- `hist-proc` dựng chỉ mục hunk, rồi xếp hạng hàm/lớp theo Locus và thêm cột HIST vào `scale_rows_v4.jsonl`.

LLM chỉ là judge. Không cell nào trong phần này gọi LLM.

In [34]:
# ── Section 8 (v4): cấu hình ───────────────────────────────────────────────────────────────────────────────
# Kết quả của v4 nằm riêng trong V4_DIR, không đè file của v3. nltk cần cho bước đưa từ về gốc (Porter) của hist-proc.
!pip install -q nltk
V4_DIR     = Path(WORK_DIR) / "v4"
V4_RESULTS = V4_DIR / "scale_rows_v4.jsonl"   # 1 dòng / instance: xếp hạng AST, nguồn DOC, HIST của v3 và HIST theo Locus
V4_TOPK    = 500                              # số id AST lưu cho mỗi instance, bằng EXP_DEEP → MRR và MAP tính tới hạng 500
V4_DIR.mkdir(parents=True, exist_ok=True)
print(f"V4_DIR: {V4_DIR} | V4_RESULTS: {V4_RESULTS} | V4_TOPK: {V4_TOPK} | RUN_V3: {RUN_V3}")

V4_DIR: /kaggle/working/v4 | V4_RESULTS: /kaggle/working/v4/scale_rows_v4.jsonl | V4_TOPK: 500 | RUN_V3: False

In [35]:
# ── Section 8 (v4): truy hồi lại với oracle mới, lưu V4_TOPK id AST mỗi instance (việc 1.2) ───────────────────
# Giống scale-run của v3, chỉ khác hai điểm. Kết quả ghi vào V4_RESULTS, nên SCALE_RESULTS của v3 không bị đè. Số id AST
# được lưu là V4_TOPK = 500 thay vì 100, để MRR và MAP tính tới hạng 500. Gold dùng oracle mới (cell 1dc937a9). Nguồn DOC
# (vote_ast, random_ast) và HIST của v3 vẫn được tính, để tính lại v3 ở việc 1.2. Chạy lại thì tiếp tục từ instance chưa có.
import time
from tqdm.auto import tqdm

SCALE_TOPK = V4_TOPK                                          # scale_row đọc hằng số này khi lưu ast_ids
_done = set()
if V4_RESULTS.exists():
    with open(V4_RESULTS, encoding="utf-8") as f:
        _done = {json.loads(l)["Instance"] for l in f if l.strip()}
_todo = [i for i in SCALE_INSTANCES if i["id"] not in _done]
print(f"Đã có {len(_done)} instance trong {V4_RESULTS} | còn {len(_todo)}")

_t0, _cur = time.perf_counter(), None
_pbar = tqdm(_todo, desc="v4-run", unit="inst")
for inst in _pbar:
    iid = inst["id"].split("__", 1)[-1]
    _pbar.set_postfix_str(iid)
    if _cur != (inst["repo"], inst["snapshot"]):              # snapshot mới: build (nếu thiếu) + dựng index 1 lần
        _cur = (inst["repo"], inst["snapshot"])
        of = build_graph(inst["snapshot"], repo_path=repo_path_of(inst["repo"]))
        idx = load_graph_indices(of)
        d2c, fwd = graph_edges(of)
        hidx = hist_index(inst["repo"], inst["snapshot"], idx)
    orc = get_oracle_snapshot(inst, idx)
    row = {"Instance": inst["id"], "Repo": inst["repo"], "version": inst["version"],
           "snapshot": inst["snapshot"][:8], "lite": inst["lite"], "gold_dropped": orc["dropped"]}
    if not any(idx["node_by_id"][g]["label"] in _FC for g in orc["nodes"]):
        row["skip"] = "không có gold Function/Class trong graph snapshot"
    else:
        c = {"inst": inst, "iid": iid, "idx": idx, "nbi": idx["node_by_id"], "orc": orc,
             "gold": orc["nodes"], "q": inst["text"], "d2c": d2c, "fwd": fwd, "hidx": hidx}
        row.update(scale_row(c))
    with open(V4_RESULTS, "a", encoding="utf-8") as f:
        f.write(json.dumps(row, ensure_ascii=False) + "\n")
print(f"Xong {len(_todo)} instance trong {time.perf_counter() - _t0:.0f}s → {V4_RESULTS}")

Đã có 0 instance trong /kaggle/working/v4/scale_rows_v4.jsonl | còn 1236

v4-run:   0%|          | 0/1236 [00:00<?, ?inst/s]

[f9de1972] disk cache hit → /kaggle/working/django_graph_f9de1972.json

[django_graph_f9de1972] tokenize AST:   0%|          | 0/9006 [00:00<?, ?node/s]

[django_graph_f9de1972] tokenize doc:   0%|          | 0/5455 [00:00<?, ?chunk/s]

[django_graph_f9de1972] indices: ast=9006 chunks=5455 (bridged=1968) vec=(8307, 384) | 2.4s
[django_graph_f9de1972] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[9dcfecb7] disk cache hit → /kaggle/working/django_graph_9dcfecb7.json

[django_graph_9dcfecb7] tokenize AST:   0%|          | 0/9016 [00:00<?, ?node/s]

[django_graph_9dcfecb7] tokenize doc:   0%|          | 0/5494 [00:00<?, ?chunk/s]

[django_graph_9dcfecb7] indices: ast=9016 chunks=5494 (bridged=2004) vec=(8317, 384) | 2.4s
[django_graph_9dcfecb7] index timing: load=0.6s tok_ast=0.3s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[0368d63a] disk cache hit → /kaggle/working/django_graph_0368d63a.json

[django_graph_0368d63a] tokenize AST:   0%|          | 0/9472 [00:00<?, ?node/s]

[django_graph_0368d63a] tokenize doc:   0%|          | 0/5815 [00:00<?, ?chunk/s]

[django_graph_0368d63a] indices: ast=9472 chunks=5815 (bridged=2168) vec=(8761, 384) | 3.3s
[django_graph_0368d63a] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.8s
[af1fa5e7] disk cache hit → /kaggle/working/django_graph_af1fa5e7.json

[django_graph_af1fa5e7] tokenize AST:   0%|          | 0/9320 [00:00<?, ?node/s]

[django_graph_af1fa5e7] tokenize doc:   0%|          | 0/5836 [00:00<?, ?chunk/s]

[django_graph_af1fa5e7] indices: ast=9320 chunks=5836 (bridged=2184) vec=(8622, 384) | 2.6s
[django_graph_af1fa5e7] index timing: load=0.7s tok_ast=0.3s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[a8bb4935] disk cache hit → /kaggle/working/django_graph_a8bb4935.json

[django_graph_a8bb4935] tokenize AST:   0%|          | 0/9410 [00:00<?, ?node/s]

[django_graph_a8bb4935] tokenize doc:   0%|          | 0/5882 [00:00<?, ?chunk/s]

[django_graph_a8bb4935] indices: ast=9410 chunks=5882 (bridged=2201) vec=(8710, 384) | 2.6s
[django_graph_a8bb4935] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[511dfb33] disk cache hit → /kaggle/working/django_graph_511dfb33.json

[django_graph_511dfb33] tokenize AST:   0%|          | 0/9552 [00:00<?, ?node/s]

[django_graph_511dfb33] tokenize doc:   0%|          | 0/5921 [00:00<?, ?chunk/s]

[django_graph_511dfb33] indices: ast=9552 chunks=5921 (bridged=2233) vec=(8842, 384) | 2.6s
[django_graph_511dfb33] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.1s
[6f0b8c1c] disk cache hit → /kaggle/working/django_graph_6f0b8c1c.json

[django_graph_6f0b8c1c] tokenize AST:   0%|          | 0/9519 [00:00<?, ?node/s]

[django_graph_6f0b8c1c] tokenize doc:   0%|          | 0/5983 [00:00<?, ?chunk/s]

[django_graph_6f0b8c1c] indices: ast=9519 chunks=5983 (bridged=2221) vec=(8817, 384) | 3.3s
[django_graph_6f0b8c1c] index timing: load=0.7s tok_ast=1.2s bm25_ast=0.2s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[02cd16a7] disk cache hit → /kaggle/working/django_graph_02cd16a7.json

[django_graph_02cd16a7] tokenize AST:   0%|          | 0/9612 [00:00<?, ?node/s]

[django_graph_02cd16a7] tokenize doc:   0%|          | 0/6057 [00:00<?, ?chunk/s]

[django_graph_02cd16a7] indices: ast=9612 chunks=6057 (bridged=2239) vec=(8908, 384) | 2.6s
[django_graph_02cd16a7] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[76dfa834] disk cache hit → /kaggle/working/django_graph_76dfa834.json

[django_graph_76dfa834] tokenize AST:   0%|          | 0/9738 [00:00<?, ?node/s]

[django_graph_76dfa834] tokenize doc:   0%|          | 0/6117 [00:00<?, ?chunk/s]

[django_graph_76dfa834] indices: ast=9738 chunks=6117 (bridged=2283) vec=(9030, 384) | 2.6s
[django_graph_76dfa834] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.3s adj=0.0s
[838e432e] disk cache hit → /kaggle/working/django_graph_838e432e.json

[django_graph_838e432e] tokenize AST:   0%|          | 0/9857 [00:00<?, ?node/s]

[django_graph_838e432e] tokenize doc:   0%|          | 0/6189 [00:00<?, ?chunk/s]

[django_graph_838e432e] indices: ast=9857 chunks=6189 (bridged=2303) vec=(9153, 384) | 3.5s
[django_graph_838e432e] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.3s bm25_full=0.4s vec_full=0.4s adj=0.8s
[2aaabe20] disk cache hit → /kaggle/working/django_graph_2aaabe20.json

[django_graph_2aaabe20] tokenize AST:   0%|          | 0/9799 [00:00<?, ?node/s]

[django_graph_2aaabe20] tokenize doc:   0%|          | 0/6217 [00:00<?, ?chunk/s]

[django_graph_2aaabe20] indices: ast=9799 chunks=6217 (bridged=2317) vec=(9098, 384) | 2.7s
[django_graph_2aaabe20] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.4s vec_full=0.3s adj=0.1s
[df28ebd6] disk cache hit → /kaggle/working/django_graph_df28ebd6.json

[django_graph_df28ebd6] tokenize AST:   0%|          | 0/9809 [00:00<?, ?node/s]

[django_graph_df28ebd6] tokenize doc:   0%|          | 0/6229 [00:00<?, ?chunk/s]

[django_graph_df28ebd6] indices: ast=9809 chunks=6229 (bridged=2327) vec=(9108, 384) | 2.7s
[django_graph_df28ebd6] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.4s vec_full=0.3s adj=0.1s
[60dc957a] disk cache hit → /kaggle/working/django_graph_60dc957a.json

[django_graph_60dc957a] tokenize AST:   0%|          | 0/9885 [00:00<?, ?node/s]

[django_graph_60dc957a] tokenize doc:   0%|          | 0/6288 [00:00<?, ?chunk/s]

[django_graph_60dc957a] indices: ast=9885 chunks=6288 (bridged=2352) vec=(9180, 384) | 2.7s
[django_graph_60dc957a] index timing: load=0.6s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.3s bm25_full=0.5s vec_full=0.3s adj=0.0s
[44077985] disk cache hit → /kaggle/working/django_graph_44077985.json

[django_graph_44077985] tokenize AST:   0%|          | 0/9923 [00:00<?, ?node/s]

[django_graph_44077985] tokenize doc:   0%|          | 0/6368 [00:00<?, ?chunk/s]

[django_graph_44077985] indices: ast=9923 chunks=6368 (bridged=2372) vec=(9217, 384) | 3.4s
[django_graph_44077985] index timing: load=0.6s tok_ast=0.4s bm25_ast=1.1s vec=0.2s tok_doc=0.4s bm25_full=0.4s vec_full=0.3s adj=0.0s
[cbe4d620] disk cache hit → /kaggle/working/django_graph_cbe4d620.json

[django_graph_cbe4d620] tokenize AST:   0%|          | 0/9964 [00:00<?, ?node/s]

[django_graph_cbe4d620] tokenize doc:   0%|          | 0/6397 [00:00<?, ?chunk/s]

[django_graph_cbe4d620] indices: ast=9964 chunks=6397 (bridged=2388) vec=(9258, 384) | 2.7s
[django_graph_cbe4d620] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.4s vec=0.2s tok_doc=0.3s bm25_full=0.5s vec_full=0.3s adj=0.0s
[b423873c] disk cache hit → /kaggle/working/django_graph_b423873c.json

[django_graph_b423873c] tokenize AST:   0%|          | 0/9989 [00:00<?, ?node/s]

[django_graph_b423873c] tokenize doc:   0%|          | 0/6447 [00:00<?, ?chunk/s]

[django_graph_b423873c] indices: ast=9989 chunks=6447 (bridged=2412) vec=(9284, 384) | 2.7s
[django_graph_b423873c] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[895f28f9] disk cache hit → /kaggle/working/django_graph_895f28f9.json

[django_graph_895f28f9] tokenize AST:   0%|          | 0/10040 [00:00<?, ?node/s]

[django_graph_895f28f9] tokenize doc:   0%|          | 0/6497 [00:00<?, ?chunk/s]

[django_graph_895f28f9] indices: ast=10040 chunks=6497 (bridged=2423) vec=(9334, 384) | 2.7s
[django_graph_895f28f9] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.5s bm25_full=0.4s vec_full=0.3s adj=0.1s
[49ae7ce5] disk cache hit → /kaggle/working/django_graph_49ae7ce5.json

[django_graph_49ae7ce5] tokenize AST:   0%|          | 0/10115 [00:00<?, ?node/s]

[django_graph_49ae7ce5] tokenize doc:   0%|          | 0/6556 [00:00<?, ?chunk/s]

[django_graph_49ae7ce5] indices: ast=10115 chunks=6556 (bridged=2432) vec=(9407, 384) | 2.7s
[django_graph_49ae7ce5] index timing: load=0.7s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[d08e6f55] disk cache hit → /kaggle/working/django_graph_d08e6f55.json

[django_graph_d08e6f55] tokenize AST:   0%|          | 0/10166 [00:00<?, ?node/s]

[django_graph_d08e6f55] tokenize doc:   0%|          | 0/6593 [00:00<?, ?chunk/s]

[django_graph_d08e6f55] indices: ast=10166 chunks=6593 (bridged=2453) vec=(9455, 384) | 2.8s
[django_graph_d08e6f55] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[419a7830] disk cache hit → /kaggle/working/django_graph_419a7830.json

[django_graph_419a7830] tokenize AST:   0%|          | 0/9972 [00:00<?, ?node/s]

[django_graph_419a7830] tokenize doc:   0%|          | 0/6435 [00:00<?, ?chunk/s]

[django_graph_419a7830] indices: ast=9972 chunks=6435 (bridged=2401) vec=(9265, 384) | 2.7s
[django_graph_419a7830] index timing: load=0.6s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.4s vec_full=0.3s adj=0.0s
[71ae1ab0] disk cache hit → /kaggle/working/django_graph_71ae1ab0.json

[django_graph_71ae1ab0] tokenize AST:   0%|          | 0/10178 [00:00<?, ?node/s]

[django_graph_71ae1ab0] tokenize doc:   0%|          | 0/6643 [00:00<?, ?chunk/s]

[django_graph_71ae1ab0] indices: ast=10178 chunks=6643 (bridged=2481) vec=(9477, 384) | 3.6s
[django_graph_71ae1ab0] index timing: load=0.7s tok_ast=0.5s bm25_ast=1.0s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[464a4c0c] disk cache hit → /kaggle/working/django_graph_464a4c0c.json

[django_graph_464a4c0c] tokenize AST:   0%|          | 0/10259 [00:00<?, ?node/s]

[django_graph_464a4c0c] tokenize doc:   0%|          | 0/6670 [00:00<?, ?chunk/s]

[django_graph_464a4c0c] indices: ast=10259 chunks=6670 (bridged=2498) vec=(9556, 384) | 2.8s
[django_graph_464a4c0c] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.5s bm25_full=0.5s vec_full=0.3s adj=0.1s
[7072bff1] disk cache hit → /kaggle/working/django_graph_7072bff1.json

[django_graph_7072bff1] tokenize AST:   0%|          | 0/10310 [00:00<?, ?node/s]

[django_graph_7072bff1] tokenize doc:   0%|          | 0/6697 [00:00<?, ?chunk/s]

[django_graph_7072bff1] indices: ast=10310 chunks=6697 (bridged=2516) vec=(9606, 384) | 2.8s
[django_graph_7072bff1] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[bef6f758] disk cache hit → /kaggle/working/django_graph_bef6f758.json

[django_graph_bef6f758] tokenize AST:   0%|          | 0/10268 [00:00<?, ?node/s]

[django_graph_bef6f758] tokenize doc:   0%|          | 0/6715 [00:00<?, ?chunk/s]

[django_graph_bef6f758] indices: ast=10268 chunks=6715 (bridged=2507) vec=(9565, 384) | 3.7s
[django_graph_bef6f758] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.9s
[41e6b2a3] disk cache hit → /kaggle/working/django_graph_41e6b2a3.json

[django_graph_41e6b2a3] tokenize AST:   0%|          | 0/10290 [00:00<?, ?node/s]

[django_graph_41e6b2a3] tokenize doc:   0%|          | 0/6747 [00:00<?, ?chunk/s]

[django_graph_41e6b2a3] indices: ast=10290 chunks=6747 (bridged=2522) vec=(9585, 384) | 2.8s
[django_graph_41e6b2a3] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[65dfb06a] disk cache hit → /kaggle/working/django_graph_65dfb06a.json

[django_graph_65dfb06a] tokenize AST:   0%|          | 0/10320 [00:00<?, ?node/s]

[django_graph_65dfb06a] tokenize doc:   0%|          | 0/6714 [00:00<?, ?chunk/s]

[django_graph_65dfb06a] indices: ast=10320 chunks=6714 (bridged=2526) vec=(9616, 384) | 2.8s
[django_graph_65dfb06a] index timing: load=0.6s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[fa4e963e] disk cache hit → /kaggle/working/django_graph_fa4e963e.json

[django_graph_fa4e963e] tokenize AST:   0%|          | 0/10331 [00:00<?, ?node/s]

[django_graph_fa4e963e] tokenize doc:   0%|          | 0/6788 [00:00<?, ?chunk/s]

[django_graph_fa4e963e] indices: ast=10331 chunks=6788 (bridged=2534) vec=(9626, 384) | 2.8s
[django_graph_fa4e963e] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[59942a66] disk cache hit → /kaggle/working/django_graph_59942a66.json

[django_graph_59942a66] tokenize AST:   0%|          | 0/10400 [00:00<?, ?node/s]

[django_graph_59942a66] tokenize doc:   0%|          | 0/6831 [00:00<?, ?chunk/s]

[django_graph_59942a66] indices: ast=10400 chunks=6831 (bridged=2544) vec=(9695, 384) | 3.7s
[django_graph_59942a66] index timing: load=0.7s tok_ast=0.5s bm25_ast=1.1s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.0s
[475cffd1] disk cache hit → /kaggle/working/django_graph_475cffd1.json

[django_graph_475cffd1] tokenize AST:   0%|          | 0/10490 [00:00<?, ?node/s]

[django_graph_475cffd1] tokenize doc:   0%|          | 0/6866 [00:00<?, ?chunk/s]

[django_graph_475cffd1] indices: ast=10490 chunks=6866 (bridged=2554) vec=(9784, 384) | 2.9s
[django_graph_475cffd1] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.0s
[32b7ffc2] disk cache hit → /kaggle/working/django_graph_32b7ffc2.json

[django_graph_32b7ffc2] tokenize AST:   0%|          | 0/10485 [00:00<?, ?node/s]

[django_graph_32b7ffc2] tokenize doc:   0%|          | 0/6895 [00:00<?, ?chunk/s]

[django_graph_32b7ffc2] indices: ast=10485 chunks=6895 (bridged=2568) vec=(9779, 384) | 2.8s
[django_graph_32b7ffc2] index timing: load=0.6s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[dd528cb2] disk cache hit → /kaggle/working/django_graph_dd528cb2.json

[django_graph_dd528cb2] tokenize AST:   0%|          | 0/10533 [00:00<?, ?node/s]

[django_graph_dd528cb2] tokenize doc:   0%|          | 0/6910 [00:00<?, ?chunk/s]

[django_graph_dd528cb2] indices: ast=10533 chunks=6910 (bridged=2578) vec=(9826, 384) | 3.6s
[django_graph_dd528cb2] index timing: load=0.6s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.9s
[7c4f3965] disk cache hit → /kaggle/working/django_graph_7c4f3965.json

[django_graph_7c4f3965] tokenize AST:   0%|          | 0/10594 [00:00<?, ?node/s]

[django_graph_7c4f3965] tokenize doc:   0%|          | 0/6954 [00:00<?, ?chunk/s]

[django_graph_7c4f3965] indices: ast=10594 chunks=6954 (bridged=2595) vec=(9886, 384) | 2.8s
[django_graph_7c4f3965] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[1d9d082a] disk cache hit → /kaggle/working/django_graph_1d9d082a.json

[django_graph_1d9d082a] tokenize AST:   0%|          | 0/10628 [00:00<?, ?node/s]

[django_graph_1d9d082a] tokenize doc:   0%|          | 0/6984 [00:00<?, ?chunk/s]

[django_graph_1d9d082a] indices: ast=10628 chunks=6984 (bridged=2609) vec=(9916, 384) | 3.0s
[django_graph_1d9d082a] index timing: load=0.7s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.0s
[1a78ef2b] disk cache hit → /kaggle/working/django_graph_1a78ef2b.json

[django_graph_1a78ef2b] tokenize AST:   0%|          | 0/10708 [00:00<?, ?node/s]

[django_graph_1a78ef2b] tokenize doc:   0%|          | 0/7063 [00:00<?, ?chunk/s]

[django_graph_1a78ef2b] indices: ast=10708 chunks=7063 (bridged=2634) vec=(9996, 384) | 2.9s
[django_graph_1a78ef2b] index timing: load=0.6s tok_ast=0.5s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.0s
[2fac0a18] disk cache hit → /kaggle/working/django_graph_2fac0a18.json

[django_graph_2fac0a18] tokenize AST:   0%|          | 0/10721 [00:00<?, ?node/s]

[django_graph_2fac0a18] tokenize doc:   0%|          | 0/7083 [00:00<?, ?chunk/s]

[django_graph_2fac0a18] indices: ast=10721 chunks=7083 (bridged=2644) vec=(10008, 384) | 3.0s
[django_graph_2fac0a18] index timing: load=0.7s tok_ast=0.5s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.4s adj=0.1s
[d938b3b2] disk cache hit → /kaggle/working/django_graph_d938b3b2.json

[django_graph_d938b3b2] tokenize AST:   0%|          | 0/10751 [00:00<?, ?node/s]

[django_graph_d938b3b2] tokenize doc:   0%|          | 0/7092 [00:00<?, ?chunk/s]

[django_graph_d938b3b2] indices: ast=10751 chunks=7092 (bridged=2651) vec=(10038, 384) | 2.9s
[django_graph_d938b3b2] index timing: load=0.7s tok_ast=0.5s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.1s
[60a7bd89] disk cache hit → /kaggle/working/django_graph_60a7bd89.json

[django_graph_60a7bd89] tokenize AST:   0%|          | 0/10802 [00:00<?, ?node/s]

[django_graph_60a7bd89] tokenize doc:   0%|          | 0/7114 [00:00<?, ?chunk/s]

[django_graph_60a7bd89] indices: ast=10802 chunks=7114 (bridged=2659) vec=(10086, 384) | 2.9s
[django_graph_60a7bd89] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.2s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.1s
[39f83765] disk cache hit → /kaggle/working/django_graph_39f83765.json

[django_graph_39f83765] tokenize AST:   0%|          | 0/10855 [00:00<?, ?node/s]

[django_graph_39f83765] tokenize doc:   0%|          | 0/7156 [00:00<?, ?chunk/s]

[django_graph_39f83765] indices: ast=10855 chunks=7156 (bridged=2664) vec=(10140, 384) | 3.8s
[django_graph_39f83765] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=1.2s bm25_full=0.5s vec_full=0.4s adj=0.0s
[051d5944] disk cache hit → /kaggle/working/django_graph_051d5944.json

[django_graph_051d5944] tokenize AST:   0%|          | 0/10907 [00:00<?, ?node/s]

[django_graph_051d5944] tokenize doc:   0%|          | 0/7201 [00:00<?, ?chunk/s]

[django_graph_051d5944] indices: ast=10907 chunks=7201 (bridged=2686) vec=(10192, 384) | 3.0s
[django_graph_051d5944] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[98f6ada0] disk cache hit → /kaggle/working/django_graph_98f6ada0.json

[django_graph_98f6ada0] tokenize AST:   0%|          | 0/10944 [00:00<?, ?node/s]

[django_graph_98f6ada0] tokenize doc:   0%|          | 0/7230 [00:00<?, ?chunk/s]

[django_graph_98f6ada0] indices: ast=10944 chunks=7230 (bridged=2702) vec=(10228, 384) | 2.9s
[django_graph_98f6ada0] index timing: load=0.7s tok_ast=0.4s bm25_ast=0.3s vec=0.2s tok_doc=0.4s bm25_full=0.5s vec_full=0.3s adj=0.0s
[496e7761] disk cache hit → /kaggle/working/sympy_graph_496e7761.json

[sympy_graph_496e7761] tokenize AST:   0%|          | 0/14798 [00:00<?, ?node/s]

[sympy_graph_496e7761] tokenize doc:   0%|          | 0/1381 [00:00<?, ?chunk/s]

[sympy_graph_496e7761] indices: ast=14798 chunks=1381 (bridged=532) vec=(14240, 384) | 3.9s
[sympy_graph_496e7761] index timing: load=0.7s tok_ast=0.8s bm25_ast=0.4s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.9s
[360290c4] disk cache hit → /kaggle/working/sympy_graph_360290c4.json

[sympy_graph_360290c4] tokenize AST:   0%|          | 0/14942 [00:00<?, ?node/s]

[sympy_graph_360290c4] tokenize doc:   0%|          | 0/1435 [00:00<?, ?chunk/s]

[sympy_graph_360290c4] indices: ast=14942 chunks=1435 (bridged=548) vec=(14379, 384) | 3.0s
[sympy_graph_360290c4] index timing: load=0.7s tok_ast=0.7s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.1s
[0410a6aa] disk cache hit → /kaggle/working/sympy_graph_0410a6aa.json

[sympy_graph_0410a6aa] tokenize AST:   0%|          | 0/14941 [00:00<?, ?node/s]

[sympy_graph_0410a6aa] tokenize doc:   0%|          | 0/1434 [00:00<?, ?chunk/s]

[sympy_graph_0410a6aa] indices: ast=14941 chunks=1434 (bridged=548) vec=(14377, 384) | 2.9s
[sympy_graph_0410a6aa] index timing: load=0.6s tok_ast=0.7s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.1s
[a53c4ad9] disk cache hit → /kaggle/working/sympy_graph_a53c4ad9.json

[sympy_graph_a53c4ad9] tokenize AST:   0%|          | 0/15054 [00:00<?, ?node/s]

[sympy_graph_a53c4ad9] tokenize doc:   0%|          | 0/1438 [00:00<?, ?chunk/s]

[sympy_graph_a53c4ad9] indices: ast=15054 chunks=1438 (bridged=549) vec=(14489, 384) | 3.9s
[sympy_graph_a53c4ad9] index timing: load=0.6s tok_ast=0.7s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.9s
[479939f8] disk cache hit → /kaggle/working/sympy_graph_479939f8.json

[sympy_graph_479939f8] tokenize AST:   0%|          | 0/15184 [00:00<?, ?node/s]

[sympy_graph_479939f8] tokenize doc:   0%|          | 0/1444 [00:00<?, ?chunk/s]

[sympy_graph_479939f8] indices: ast=15184 chunks=1444 (bridged=552) vec=(14616, 384) | 3.0s
[sympy_graph_479939f8] index timing: load=0.6s tok_ast=0.7s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.1s
[0cd4f13a] disk cache hit → /kaggle/working/sympy_graph_0cd4f13a.json

[sympy_graph_0cd4f13a] tokenize AST:   0%|          | 0/15459 [00:00<?, ?node/s]

[sympy_graph_0cd4f13a] tokenize doc:   0%|          | 0/1440 [00:00<?, ?chunk/s]

[sympy_graph_0cd4f13a] indices: ast=15459 chunks=1440 (bridged=552) vec=(14885, 384) | 3.0s
[sympy_graph_0cd4f13a] index timing: load=0.7s tok_ast=0.7s bm25_ast=0.4s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.1s
[d250ff08] disk cache hit → /kaggle/working/sympy_graph_d250ff08.json

[sympy_graph_d250ff08] tokenize AST:   0%|          | 0/15448 [00:00<?, ?node/s]

[sympy_graph_d250ff08] tokenize doc:   0%|          | 0/1441 [00:00<?, ?chunk/s]

[sympy_graph_d250ff08] indices: ast=15448 chunks=1441 (bridged=552) vec=(14873, 384) | 3.0s
[sympy_graph_d250ff08] index timing: load=0.6s tok_ast=0.7s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.1s
[ae3d62ab] disk cache hit → /kaggle/working/sympy_graph_ae3d62ab.json

[sympy_graph_ae3d62ab] tokenize AST:   0%|          | 0/17045 [00:00<?, ?node/s]

[sympy_graph_ae3d62ab] tokenize doc:   0%|          | 0/1444 [00:00<?, ?chunk/s]

[sympy_graph_ae3d62ab] indices: ast=17045 chunks=1444 (bridged=553) vec=(16441, 384) | 3.8s
[sympy_graph_ae3d62ab] index timing: load=1.0s tok_ast=0.9s bm25_ast=0.4s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.3s
[b3934e41] disk cache hit → /kaggle/working/sympy_graph_b3934e41.json

[sympy_graph_b3934e41] tokenize AST:   0%|          | 0/17216 [00:00<?, ?node/s]

[sympy_graph_b3934e41] tokenize doc:   0%|          | 0/1465 [00:00<?, ?chunk/s]

[sympy_graph_b3934e41] indices: ast=17216 chunks=1465 (bridged=556) vec=(16606, 384) | 3.8s
[sympy_graph_b3934e41] index timing: load=1.0s tok_ast=0.9s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=0.3s
[9bf73cc2] disk cache hit → /kaggle/working/sympy_graph_9bf73cc2.json

[sympy_graph_9bf73cc2] tokenize AST:   0%|          | 0/17307 [00:00<?, ?node/s]

[sympy_graph_9bf73cc2] tokenize doc:   0%|          | 0/1465 [00:00<?, ?chunk/s]

[sympy_graph_9bf73cc2] indices: ast=17307 chunks=1465 (bridged=556) vec=(16695, 384) | 4.8s
[sympy_graph_9bf73cc2] index timing: load=1.0s tok_ast=0.9s bm25_ast=0.4s vec=0.3s tok_doc=0.1s bm25_full=0.4s vec_full=0.3s adj=1.2s
[205da797] disk cache hit → /kaggle/working/sympy_graph_205da797.json

[sympy_graph_205da797] tokenize AST:   0%|          | 0/17911 [00:00<?, ?node/s]

[sympy_graph_205da797] tokenize doc:   0%|          | 0/1472 [00:00<?, ?chunk/s]

[sympy_graph_205da797] indices: ast=17911 chunks=1472 (bridged=561) vec=(17279, 384) | 3.9s
[sympy_graph_205da797] index timing: load=1.0s tok_ast=0.8s bm25_ast=0.6s vec=0.3s tok_doc=0.1s bm25_full=0.5s vec_full=0.4s adj=0.3s
[8fc63c2d] disk cache hit → /kaggle/working/sympy_graph_8fc63c2d.json

[sympy_graph_8fc63c2d] tokenize AST:   0%|          | 0/18016 [00:00<?, ?node/s]

[sympy_graph_8fc63c2d] tokenize doc:   0%|          | 0/1473 [00:00<?, ?chunk/s]

[sympy_graph_8fc63c2d] indices: ast=18016 chunks=1473 (bridged=561) vec=(17380, 384) | 3.9s
[sympy_graph_8fc63c2d] index timing: load=1.0s tok_ast=0.9s bm25_ast=0.5s vec=0.4s tok_doc=0.1s bm25_full=0.4s vec_full=0.4s adj=0.3s
[9cbea134] disk cache hit → /kaggle/working/sympy_graph_9cbea134.json

[sympy_graph_9cbea134] tokenize AST:   0%|          | 0/18435 [00:00<?, ?node/s]

[sympy_graph_9cbea134] tokenize doc:   0%|          | 0/1486 [00:00<?, ?chunk/s]

[sympy_graph_9cbea134] indices: ast=18435 chunks=1486 (bridged=564) vec=(17783, 384) | 5.0s
[sympy_graph_9cbea134] index timing: load=1.0s tok_ast=1.9s bm25_ast=0.5s vec=0.3s tok_doc=0.1s bm25_full=0.5s vec_full=0.4s adj=0.3s
[678217d5] disk cache hit → /kaggle/working/sympy_graph_678217d5.json

[sympy_graph_678217d5] tokenize AST:   0%|          | 0/27739 [00:00<?, ?node/s]

[sympy_graph_678217d5] tokenize doc:   0%|          | 0/1556 [00:00<?, ?chunk/s]

[sympy_graph_678217d5] indices: ast=27739 chunks=1556 (bridged=576) vec=(27057, 384) | 5.2s
[sympy_graph_678217d5] index timing: load=1.3s tok_ast=1.2s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.5s adj=0.3s
[6399a809] disk cache hit → /kaggle/working/sympy_graph_6399a809.json

[sympy_graph_6399a809] tokenize AST:   0%|          | 0/27863 [00:00<?, ?node/s]

[sympy_graph_6399a809] tokenize doc:   0%|          | 0/1567 [00:00<?, ?chunk/s]

[sympy_graph_6399a809] indices: ast=27863 chunks=1567 (bridged=582) vec=(27180, 384) | 6.2s
[sympy_graph_6399a809] index timing: load=1.3s tok_ast=2.3s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.5s adj=0.3s
[28d913d3] disk cache hit → /kaggle/working/sympy_graph_28d913d3.json

[sympy_graph_28d913d3] tokenize AST:   0%|          | 0/27959 [00:00<?, ?node/s]

[sympy_graph_28d913d3] tokenize doc:   0%|          | 0/1567 [00:00<?, ?chunk/s]

[sympy_graph_28d913d3] indices: ast=27959 chunks=1567 (bridged=582) vec=(27273, 384) | 5.1s
[sympy_graph_28d913d3] index timing: load=1.3s tok_ast=1.2s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.5s adj=0.3s
[356a73cd] disk cache hit → /kaggle/working/sympy_graph_356a73cd.json

[sympy_graph_356a73cd] tokenize AST:   0%|          | 0/28167 [00:00<?, ?node/s]

[sympy_graph_356a73cd] tokenize doc:   0%|          | 0/1560 [00:00<?, ?chunk/s]

[sympy_graph_356a73cd] indices: ast=28167 chunks=1560 (bridged=584) vec=(27481, 384) | 6.5s
[sympy_graph_356a73cd] index timing: load=1.3s tok_ast=2.4s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[0469e038] disk cache hit → /kaggle/working/sympy_graph_0469e038.json

[sympy_graph_0469e038] tokenize AST:   0%|          | 0/28180 [00:00<?, ?node/s]

[sympy_graph_0469e038] tokenize doc:   0%|          | 0/1560 [00:00<?, ?chunk/s]

[sympy_graph_0469e038] indices: ast=28180 chunks=1560 (bridged=584) vec=(27494, 384) | 5.2s
[sympy_graph_0469e038] index timing: load=1.3s tok_ast=1.2s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[c50643a4] disk cache hit → /kaggle/working/sympy_graph_c50643a4.json

[sympy_graph_c50643a4] tokenize AST:   0%|          | 0/28365 [00:00<?, ?node/s]

[sympy_graph_c50643a4] tokenize doc:   0%|          | 0/1566 [00:00<?, ?chunk/s]

[sympy_graph_c50643a4] indices: ast=28365 chunks=1566 (bridged=586) vec=(27678, 384) | 6.4s
[sympy_graph_c50643a4] index timing: load=1.4s tok_ast=2.3s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[8ca4a683] disk cache hit → /kaggle/working/sympy_graph_8ca4a683.json

[sympy_graph_8ca4a683] tokenize AST:   0%|          | 0/28662 [00:00<?, ?node/s]

[sympy_graph_8ca4a683] tokenize doc:   0%|          | 0/1568 [00:00<?, ?chunk/s]

[sympy_graph_8ca4a683] indices: ast=28662 chunks=1568 (bridged=588) vec=(27971, 384) | 5.3s
[sympy_graph_8ca4a683] index timing: load=1.3s tok_ast=1.2s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[f5e96594] disk cache hit → /kaggle/working/sympy_graph_f5e96594.json

[sympy_graph_f5e96594] tokenize AST:   0%|          | 0/29102 [00:00<?, ?node/s]

[sympy_graph_f5e96594] tokenize doc:   0%|          | 0/1587 [00:00<?, ?chunk/s]

[sympy_graph_f5e96594] indices: ast=29102 chunks=1587 (bridged=595) vec=(28399, 384) | 6.6s
[sympy_graph_f5e96594] index timing: load=1.3s tok_ast=2.5s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[cab3c1cb] disk cache hit → /kaggle/working/sympy_graph_cab3c1cb.json

[sympy_graph_cab3c1cb] tokenize AST:   0%|          | 0/29273 [00:00<?, ?node/s]

[sympy_graph_cab3c1cb] tokenize doc:   0%|          | 0/1687 [00:00<?, ?chunk/s]

[sympy_graph_cab3c1cb] indices: ast=29273 chunks=1687 (bridged=650) vec=(28561, 384) | 5.3s
[sympy_graph_cab3c1cb] index timing: load=1.3s tok_ast=1.2s bm25_ast=0.6s vec=0.5s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[70381f28] disk cache hit → /kaggle/working/sympy_graph_70381f28.json

[sympy_graph_70381f28] tokenize AST:   0%|          | 0/29272 [00:00<?, ?node/s]

[sympy_graph_70381f28] tokenize doc:   0%|          | 0/1690 [00:00<?, ?chunk/s]

[sympy_graph_70381f28] indices: ast=29272 chunks=1690 (bridged=650) vec=(28561, 384) | 6.6s
[sympy_graph_70381f28] index timing: load=1.3s tok_ast=2.5s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[fcefd30c] disk cache hit → /kaggle/working/sympy_graph_fcefd30c.json

[sympy_graph_fcefd30c] tokenize AST:   0%|          | 0/29559 [00:00<?, ?node/s]

[sympy_graph_fcefd30c] tokenize doc:   0%|          | 0/1692 [00:00<?, ?chunk/s]

[sympy_graph_fcefd30c] indices: ast=29559 chunks=1692 (bridged=649) vec=(28829, 384) | 5.4s
[sympy_graph_fcefd30c] index timing: load=1.3s tok_ast=1.3s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[46921d28] disk cache hit → /kaggle/working/sympy_graph_46921d28.json

[sympy_graph_46921d28] tokenize AST:   0%|          | 0/29827 [00:00<?, ?node/s]

[sympy_graph_46921d28] tokenize doc:   0%|          | 0/1691 [00:00<?, ?chunk/s]

[sympy_graph_46921d28] indices: ast=29827 chunks=1691 (bridged=647) vec=(29090, 384) | 6.7s
[sympy_graph_46921d28] index timing: load=1.3s tok_ast=2.5s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[e0ef1da1] disk cache hit → /kaggle/working/sympy_graph_e0ef1da1.json

[sympy_graph_e0ef1da1] tokenize AST:   0%|          | 0/29845 [00:00<?, ?node/s]

[sympy_graph_e0ef1da1] tokenize doc:   0%|          | 0/1669 [00:00<?, ?chunk/s]

[sympy_graph_e0ef1da1] indices: ast=29845 chunks=1669 (bridged=647) vec=(29108, 384) | 5.4s
[sympy_graph_e0ef1da1] index timing: load=1.3s tok_ast=1.3s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[b1078cd0] disk cache hit → /kaggle/working/sympy_graph_b1078cd0.json

[sympy_graph_b1078cd0] tokenize AST:   0%|          | 0/30117 [00:00<?, ?node/s]

[sympy_graph_b1078cd0] tokenize doc:   0%|          | 0/1673 [00:00<?, ?chunk/s]

[sympy_graph_b1078cd0] indices: ast=30117 chunks=1673 (bridged=538) vec=(29370, 384) | 6.6s
[sympy_graph_b1078cd0] index timing: load=1.4s tok_ast=2.4s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[d57aaf06] disk cache hit → /kaggle/working/sympy_graph_d57aaf06.json

[sympy_graph_d57aaf06] tokenize AST:   0%|          | 0/30473 [00:00<?, ?node/s]

[sympy_graph_d57aaf06] tokenize doc:   0%|          | 0/1687 [00:00<?, ?chunk/s]

[sympy_graph_d57aaf06] indices: ast=30473 chunks=1687 (bridged=546) vec=(29713, 384) | 5.5s
[sympy_graph_d57aaf06] index timing: load=1.3s tok_ast=1.3s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[d5571e8b] disk cache hit → /kaggle/working/sympy_graph_d5571e8b.json

[sympy_graph_d5571e8b] tokenize AST:   0%|          | 0/30541 [00:00<?, ?node/s]

[sympy_graph_d5571e8b] tokenize doc:   0%|          | 0/1687 [00:00<?, ?chunk/s]

[sympy_graph_d5571e8b] indices: ast=30541 chunks=1687 (bridged=546) vec=(29781, 384) | 6.9s
[sympy_graph_d5571e8b] index timing: load=1.4s tok_ast=2.7s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[cffd4e0f] disk cache hit → /kaggle/working/sympy_graph_cffd4e0f.json

[sympy_graph_cffd4e0f] tokenize AST:   0%|          | 0/30611 [00:00<?, ?node/s]

[sympy_graph_cffd4e0f] tokenize doc:   0%|          | 0/1688 [00:00<?, ?chunk/s]

[sympy_graph_cffd4e0f] indices: ast=30611 chunks=1688 (bridged=547) vec=(29840, 384) | 5.5s
[sympy_graph_cffd4e0f] index timing: load=1.3s tok_ast=1.3s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[eb926a1d] disk cache hit → /kaggle/working/sympy_graph_eb926a1d.json

[sympy_graph_eb926a1d] tokenize AST:   0%|          | 0/30673 [00:00<?, ?node/s]

[sympy_graph_eb926a1d] tokenize doc:   0%|          | 0/1689 [00:00<?, ?chunk/s]

[sympy_graph_eb926a1d] indices: ast=30673 chunks=1689 (bridged=549) vec=(29901, 384) | 6.8s
[sympy_graph_eb926a1d] index timing: load=1.3s tok_ast=2.6s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.7s adj=0.3s
[748ce734] disk cache hit → /kaggle/working/sympy_graph_748ce734.json

[sympy_graph_748ce734] tokenize AST:   0%|          | 0/30849 [00:00<?, ?node/s]

[sympy_graph_748ce734] tokenize doc:   0%|          | 0/1812 [00:00<?, ?chunk/s]

[sympy_graph_748ce734] indices: ast=30849 chunks=1812 (bridged=660) vec=(30050, 384) | 5.6s
[sympy_graph_748ce734] index timing: load=1.4s tok_ast=1.4s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[546e1079] disk cache hit → /kaggle/working/sympy_graph_546e1079.json

[sympy_graph_546e1079] tokenize AST:   0%|          | 0/30953 [00:00<?, ?node/s]

[sympy_graph_546e1079] tokenize doc:   0%|          | 0/1818 [00:00<?, ?chunk/s]

[sympy_graph_546e1079] indices: ast=30953 chunks=1818 (bridged=664) vec=(30151, 384) | 7.0s
[sympy_graph_546e1079] index timing: load=1.4s tok_ast=2.6s bm25_ast=0.6s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[b4777fdc] disk cache hit → /kaggle/working/sympy_graph_b4777fdc.json

[sympy_graph_b4777fdc] tokenize AST:   0%|          | 0/31141 [00:00<?, ?node/s]

[sympy_graph_b4777fdc] tokenize doc:   0%|          | 0/1881 [00:00<?, ?chunk/s]

[sympy_graph_b4777fdc] indices: ast=31141 chunks=1881 (bridged=689) vec=(30335, 384) | 5.8s
[sympy_graph_b4777fdc] index timing: load=1.5s tok_ast=1.4s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.6s vec_full=0.6s adj=0.3s
[ec0fe8c5] disk cache hit → /kaggle/working/sympy_graph_ec0fe8c5.json

[sympy_graph_ec0fe8c5] tokenize AST:   0%|          | 0/31435 [00:00<?, ?node/s]

[sympy_graph_ec0fe8c5] tokenize doc:   0%|          | 0/1908 [00:00<?, ?chunk/s]

[sympy_graph_ec0fe8c5] indices: ast=31435 chunks=1908 (bridged=693) vec=(30620, 384) | 7.2s
[sympy_graph_ec0fe8c5] index timing: load=1.4s tok_ast=2.7s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.4s
[3f8c8c23] disk cache hit → /kaggle/working/sympy_graph_3f8c8c23.json

[sympy_graph_3f8c8c23] tokenize AST:   0%|          | 0/31480 [00:00<?, ?node/s]

[sympy_graph_3f8c8c23] tokenize doc:   0%|          | 0/1933 [00:00<?, ?chunk/s]

[sympy_graph_3f8c8c23] indices: ast=31480 chunks=1933 (bridged=698) vec=(30662, 384) | 5.8s
[sympy_graph_3f8c8c23] index timing: load=1.4s tok_ast=1.4s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[a3475b3f] disk cache hit → /kaggle/working/sympy_graph_a3475b3f.json

[sympy_graph_a3475b3f] tokenize AST:   0%|          | 0/31614 [00:00<?, ?node/s]

[sympy_graph_a3475b3f] tokenize doc:   0%|          | 0/1932 [00:00<?, ?chunk/s]

[sympy_graph_a3475b3f] indices: ast=31614 chunks=1932 (bridged=701) vec=(30784, 384) | 7.2s
[sympy_graph_a3475b3f] index timing: load=1.5s tok_ast=2.8s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[c4e836cd] disk cache hit → /kaggle/working/sympy_graph_c4e836cd.json

[sympy_graph_c4e836cd] tokenize AST:   0%|          | 0/31880 [00:00<?, ?node/s]

[sympy_graph_c4e836cd] tokenize doc:   0%|          | 0/1964 [00:00<?, ?chunk/s]

[sympy_graph_c4e836cd] indices: ast=31880 chunks=1964 (bridged=713) vec=(31043, 384) | 5.9s
[sympy_graph_c4e836cd] index timing: load=1.5s tok_ast=1.4s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.7s adj=0.3s
[d7bddf4f] disk cache hit → /kaggle/working/sympy_graph_d7bddf4f.json

[sympy_graph_d7bddf4f] tokenize AST:   0%|          | 0/31856 [00:00<?, ?node/s]

[sympy_graph_d7bddf4f] tokenize doc:   0%|          | 0/1965 [00:00<?, ?chunk/s]

[sympy_graph_d7bddf4f] indices: ast=31856 chunks=1965 (bridged=713) vec=(31023, 384) | 7.2s
[sympy_graph_d7bddf4f] index timing: load=1.4s tok_ast=2.8s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[96c9c40b] disk cache hit → /kaggle/working/sympy_graph_96c9c40b.json

[sympy_graph_96c9c40b] tokenize AST:   0%|          | 0/31950 [00:00<?, ?node/s]

[sympy_graph_96c9c40b] tokenize doc:   0%|          | 0/1984 [00:00<?, ?chunk/s]

[sympy_graph_96c9c40b] indices: ast=31950 chunks=1984 (bridged=726) vec=(31116, 384) | 5.9s
[sympy_graph_96c9c40b] index timing: load=1.5s tok_ast=1.4s bm25_ast=0.7s vec=0.7s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[9a6104ea] disk cache hit → /kaggle/working/sympy_graph_9a6104ea.json

[sympy_graph_9a6104ea] tokenize AST:   0%|          | 0/31988 [00:00<?, ?node/s]

[sympy_graph_9a6104ea] tokenize doc:   0%|          | 0/1976 [00:00<?, ?chunk/s]

[sympy_graph_9a6104ea] indices: ast=31988 chunks=1976 (bridged=727) vec=(31156, 384) | 7.3s
[sympy_graph_9a6104ea] index timing: load=1.4s tok_ast=2.8s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[68bd3627] disk cache hit → /kaggle/working/sympy_graph_68bd3627.json

[sympy_graph_68bd3627] tokenize AST:   0%|          | 0/31998 [00:00<?, ?node/s]

[sympy_graph_68bd3627] tokenize doc:   0%|          | 0/1990 [00:00<?, ?chunk/s]

[sympy_graph_68bd3627] indices: ast=31998 chunks=1990 (bridged=733) vec=(31167, 384) | 5.9s
[sympy_graph_68bd3627] index timing: load=1.4s tok_ast=1.4s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[514579c6] disk cache hit → /kaggle/working/sympy_graph_514579c6.json

[sympy_graph_514579c6] tokenize AST:   0%|          | 0/32149 [00:00<?, ?node/s]

[sympy_graph_514579c6] tokenize doc:   0%|          | 0/2005 [00:00<?, ?chunk/s]

[sympy_graph_514579c6] indices: ast=32149 chunks=2005 (bridged=739) vec=(31311, 384) | 7.2s
[sympy_graph_514579c6] index timing: load=1.5s tok_ast=2.6s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.6s adj=0.3s
[cdef6fcb] disk cache hit → /kaggle/working/sympy_graph_cdef6fcb.json

[sympy_graph_cdef6fcb] tokenize AST:   0%|          | 0/32271 [00:00<?, ?node/s]

[sympy_graph_cdef6fcb] tokenize doc:   0%|          | 0/1536 [00:00<?, ?chunk/s]

[sympy_graph_cdef6fcb] indices: ast=32271 chunks=1536 (bridged=420) vec=(31433, 384) | 6.0s
[sympy_graph_cdef6fcb] index timing: load=1.5s tok_ast=1.4s bm25_ast=0.7s vec=0.6s tok_doc=0.1s bm25_full=0.7s vec_full=0.7s adj=0.4s
[c4d6b3eb] disk cache hit → /kaggle/working/sympy_graph_c4d6b3eb.json

[sympy_graph_c4d6b3eb] tokenize AST:   0%|          | 0/22264 [00:00<?, ?node/s]

[sympy_graph_c4d6b3eb] tokenize doc:   0%|          | 0/1540 [00:00<?, ?chunk/s]

[sympy_graph_c4d6b3eb] indices: ast=22264 chunks=1540 (bridged=420) vec=(21453, 384) | 5.8s
[sympy_graph_c4d6b3eb] index timing: load=1.1s tok_ast=2.5s bm25_ast=0.6s vec=0.4s tok_doc=0.1s bm25_full=0.6s vec_full=0.4s adj=0.1s
[d3b4158d] disk cache hit → /kaggle/working/sympy_graph_d3b4158d.json

[sympy_graph_d3b4158d] tokenize AST:   0%|          | 0/22382 [00:00<?, ?node/s]

[sympy_graph_d3b4158d] tokenize doc:   0%|          | 0/1552 [00:00<?, ?chunk/s]

[sympy_graph_d3b4158d] indices: ast=22382 chunks=1552 (bridged=425) vec=(21566, 384) | 4.5s
[sympy_graph_d3b4158d] index timing: load=0.9s tok_ast=1.2s bm25_ast=0.6s vec=0.4s tok_doc=0.1s bm25_full=0.6s vec_full=0.5s adj=0.1s
Xong 1236 instance trong 3288s → /kaggle/working/v4/scale_rows_v4.jsonl

In [36]:
# ── Section v4: nguồn HIST theo Locus (Wen, Wu, Cheung, ASE 2016), ở mức hàm/lớp ─────────────────────────────────
# Tài liệu = 1 hunk (dòng đổi, 3 dòng ngữ cảnh, commit message) của đơn vị history là tổ tiên của snapshot.
#   score(b, f) = max_{h ∈ H(f)} {NL(b, h) + α·CE(b, h)} + β1·Fix(f)             Locus (7), file s → hàm/lớp f
#   NL, CE      = cosine trong VSM, trọng số w_td = (log f_td + 1)·log(N / n_t)   Locus (1)–(4)
#   α           = min(1, λ·#tên code / #token đã tách của issue), λ = 5          Locus (9)
#   Fix(f)      = Σ 1 / (1 + e^(−12·t_i + 12)) trên commit sửa lỗi đã sửa f      Locus (5), β1 = 0,1
# Chỗ chuyển đổi (planning.md mục 6.4): A1 file → hàm/lớp, H(f) theo oracle mới; A2 commit sửa lỗi = message khớp
# fix|bug (AmaLgam, quy tắc 1); A3 t: 0 = đơn vị cũ nhất của file history, 1 = created_at của instance; A4 tài liệu =
# hunk của đơn vị là tổ tiên của snapshot, IDF riêng từng snapshot; A5 file .py có trong graph, git diff -U3 -w, bỏ hunk
# chỉ đổi comment; A6 query = problem_statement; A7 từ giống code: có _ hoặc ., có chữ hoa sau ký tự đầu, nằm trong
# backtick, hoặc đứng ngay trước "(".
# Cần chạy sau hist-build (HIST, HIST_DIR) và v4-run (V4_RESULTS có ast_ids, gold_ids).
import functools
import keyword
import math
import re
import shutil
import scipy.sparse as sp
import unidiff
from collections import Counter
from itertools import groupby
from datasets import load_dataset
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS

LOCUS_LAMBDA = 5          # Locus: λ tốt trong 3..7, bài đặt 5
LOCUS_BETA1  = 0.1        # Locus: β1 tốt trong 0,05..0,15 ở mức file, bài đặt 0,1
LOCUS_TOPN   = 500        # số hàm/lớp đầu được lưu, bằng độ sâu xếp hạng AST (EXP_DEEP)
LOCUS_EVID   = 10         # số hàm/lớp đầu được ghi hunk tốt nhất, để judge chấm
LOCUS_SRC    = "hist_locus"
_BUGFIX_RE   = re.compile(r"fix|bug", re.I)                                       # AmaLgam, quy tắc 1
_NL_STOP     = set(ENGLISH_STOP_WORDS) | {k.lower() for k in keyword.kwlist}      # stop word + từ khóa Python
_stem        = functools.lru_cache(maxsize=None)(PorterStemmer().stem)
_IDENT_RE    = re.compile(r"`[^`\n]+`|[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*\(?")
_NAME_RE     = re.compile(r"[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)*")

def _nl_terms(txt):
    """Token NL: tách định danh (camelCase, snake_case), bỏ stop word và từ khóa, đưa về gốc bằng Porter."""
    return [_stem(t) for t in _tokenize_code(txt) if t not in _NL_STOP]

def _code_terms(txt):
    """Từ giống code (A7), giữ nguyên không tách. Từ có dấu chấm cho thêm từng phần: 'QuerySet.filter' →
    'QuerySet.filter', 'QuerySet', 'filter'. Việc giữ từ nào khớp tên trong graph làm ở bước dựng chỉ mục."""
    out = []
    for m in _IDENT_RE.finditer(txt):
        t = m.group(0)
        if t.startswith("`"):
            toks = _NAME_RE.findall(t)
        else:
            call, t = t.endswith("("), t.rstrip("(")
            toks = [t] if call or "_" in t or "." in t or any(c.isupper() for c in t[1:]) else []
        for x in toks:
            out.append(x)
            if "." in x:
                out.extend(x.split("."))
    return out

def _hunk_body(text):
    """Nội dung hunk (dòng ngữ cảnh, dòng xóa, dòng thêm), bỏ dòng tiêu đề @@ và ký tự đầu dòng."""
    return "\n".join(l[1:] for l in text.split("\n")[1:])

def _comment_only(h):
    return all(not t or t.startswith("#") for t in (ln.value.strip() for ln in h if ln.is_added or ln.is_removed))

def _hunks_path(repo):
    return HIST_DIR / f"{repo.split('/')[1]}_hunks_v2.jsonl"

def build_hunks(repo):
    """1 dòng / hunk: u = sha của đơn vị, f = file (tên sau đổi tên), k = thứ tự hunk trong file, ids = hàm/lớp mà
    hunk đổi (oracle mới, id theo tên file mới như touch; rỗng nếu chỉ đổi ở cấp module), text = hunk dạng diff.
    Chỉ duyệt đơn vị có touch khác rỗng: đơn vị khác không đổi hàm/lớp nào trong file có ở graph."""
    rp, n = repo_path_of(repo), 0
    units = [u for u in HIST[repo]["units"] if u["touch"]]
    with open(_hunks_path(repo), "w", encoding="utf-8") as f:
        for u in tqdm(units, desc=f"hunk {repo}", unit="commit"):
            diff = _git(rp, "diff", "-U3", "-w", u["p"], u["h"], "--", "*.py")
            if not diff:
                continue
            for pf in unidiff.PatchSet(diff):
                src = _src_path(pf)
                if pf.is_added_file or not src.endswith(".py") or _skip_rel(src):
                    continue
                nodes = _file_nodes_at(rp, u["p"], src)          # node của file tại commit cha, như khi tính touch
                if not nodes:
                    continue
                lab = {x["id"]: x["label"] for x in nodes}
                for k, h in enumerate(pf):
                    if _comment_only(h):
                        continue
                    one = f"--- a/{src}\n+++ b/{pf.path}\n{h}"
                    ids = sorted(pf.path + x[len(src):] for x in get_oracle(one, nodes)["nodes"] if lab.get(x) in _FC)
                    f.write(json.dumps({"u": u["h"], "f": pf.path, "k": k, "ids": ids, "text": str(h)},
                                       ensure_ascii=False) + "\n")
                    n += 1
    return n

def load_hunks(repo):
    p = _hunks_path(repo)
    if not p.exists() and HIST_INPUT and (Path(HIST_INPUT) / p.name).exists():
        shutil.copy(Path(HIST_INPUT) / p.name, p)
    if not p.exists():
        build_hunks(repo)
    return [json.loads(l) for l in open(p, encoding="utf-8") if l.strip()]

def _counts(docs, fn):
    """Ma trận đếm (hàng = tài liệu, cột = từ) và từ điển cột."""
    vocab, r, c, v = {}, [], [], []
    for i, d in enumerate(docs):
        for t, k in Counter(fn(d)).items():
            r.append(i); c.append(vocab.setdefault(t, len(vocab))); v.append(k)
    return sp.csr_matrix((v, (r, c)), shape=(len(docs), len(vocab)), dtype=np.float64), vocab

def locus_corpus(repo):
    """Chỉ mục của 1 repo, dùng chung cho mọi snapshot: đếm NL và CE của từng hunk, ma trận hunk × hàm/lớp (H(f)),
    ma trận đơn vị sửa lỗi × hàm/lớp (cho Fix) cùng thời điểm của chúng."""
    H = HIST[repo]
    msg = {u["h"]: u["msg"] for u in H["units"]}
    hunks = load_hunks(repo)
    docs = [_hunk_body(x["text"]) + "\n" + msg[x["u"]] for x in tqdm(hunks, desc=f"văn bản {repo}", unit="hunk")]
    Xnl, nl_vocab = _counts(docs, _nl_terms)
    Xce, ce_vocab = _counts(docs, _code_terms)
    fn_vocab, r, c = {}, [], []
    for i, x in enumerate(hunks):
        for k in x["ids"]:
            r.append(i); c.append(fn_vocab.setdefault(k, len(fn_vocab)))
    bf = [u for u in H["units"] if u["touch"] and _BUGFIX_RE.search(u["msg"])]
    fr, fc = [], []
    for i, u in enumerate(bf):
        for k in u["touch"]:
            fr.append(i); fc.append(fn_vocab.setdefault(k, len(fn_vocab)))
    nf = len(fn_vocab)
    return {"hunks": hunks, "unit": np.array([x["u"] for x in hunks]), "Xnl": Xnl, "nl_vocab": nl_vocab,
            "Xce": Xce, "ce_vocab": ce_vocab, "fn_vocab": fn_vocab, "fn_keys": sorted(fn_vocab, key=fn_vocab.get),
            "M": sp.csr_matrix((np.ones(len(r)), (r, c)), shape=(len(hunks), nf)),
            "bf_unit": np.array([u["h"] for u in bf]), "bf_t": np.array([u["t"] for u in bf], dtype=np.float64),
            "F": sp.csr_matrix((np.ones(len(fr)), (fr, fc)), shape=(len(bf), nf)),
            "t0": float(min(u["t"] for u in H["units"]))}

def _tfidf(X):
    """Locus (2): w = (log f + 1)·log(N / n_t), N và n_t tính trên đúng các tài liệu đưa vào; hàng chuẩn hóa L2."""
    X = X.tocsr().copy(); X.eliminate_zeros()           # bỏ ô 0 do che cột CE
    N = X.shape[0]
    df = np.bincount(X.indices, minlength=X.shape[1])
    idf = np.zeros(X.shape[1]); nz = df > 0; idf[nz] = np.log(N / df[nz])
    W = X.copy(); W.data = np.log(W.data) + 1.0
    W = (W @ sp.diags(idf)).tocsr()
    norm = np.sqrt(np.asarray(W.power(2).sum(axis=1)).ravel()); norm[norm == 0] = 1.0
    return sp.diags(1.0 / norm) @ W, idf

def _qvec(terms, vocab, idf):
    v = np.zeros(len(idf))
    for t, k in Counter(terms).items():
        j = vocab.get(t)
        if j is not None:
            v[j] = (math.log(k) + 1.0) * idf[j]
    n = np.linalg.norm(v)
    return v / n if n else v

def locus_snapshot(C, repo, snapshot, names):
    """Phần của 1 snapshot (A4): hunk và đơn vị sửa lỗi là tổ tiên của snapshot; IDF tính trên các hunk đó; CE chỉ
    giữ từ khớp tên module, lớp, hàm trong graph của snapshot (names)."""
    anc = set(_git(repo_path_of(repo), "rev-list", snapshot).split())
    rows = np.flatnonzero([u in anc for u in C["unit"]])
    Wnl, idf_nl = _tfidf(C["Xnl"][rows])
    mask = np.zeros(len(C["ce_vocab"])); mask[[j for t, j in C["ce_vocab"].items() if t in names]] = 1.0
    Wce, idf_ce = _tfidf((C["Xce"][rows] @ sp.diags(mask)).tocsr())
    bfr = np.flatnonzero([u in anc for u in C["bf_unit"]])
    return {"rows": rows, "Wnl": Wnl, "idf_nl": idf_nl, "Wce": Wce, "idf_ce": idf_ce, "names": names,
            "M": C["M"][rows].tocsc(), "F": C["F"][bfr], "bf_t": C["bf_t"][bfr]}

def locus_rank(C, S, q, t_issue):
    """Điểm Locus của mọi hàm/lớp cho 1 issue, ở ba cấu hình của phân tích thành phần (Locus, RQ4): chỉ NL, NL + α·CE,
    và đủ NL + α·CE + β1·Fix. Trả (dict cấu hình → điểm theo cột hàm/lớp, điểm từng hunk của NL + α·CE, α)."""
    ce_q = [t for t in _code_terms(q) if t in S["names"]]
    alpha = min(1.0, LOCUS_LAMBDA * len(ce_q) / max(1, len(_tokenize_code(q))))
    nl = S["Wnl"] @ _qvec(_nl_terms(q), C["nl_vocab"], S["idf_nl"])
    s = nl + alpha * (S["Wce"] @ _qvec(ce_q, C["ce_vocab"], S["idf_ce"]))
    best = lambda v: (sp.diags(v) @ S["M"]).max(axis=0).toarray().ravel()   # max trên các hunk của từng hàm/lớp
    t = np.clip((S["bf_t"] - C["t0"]) / max(1.0, t_issue - C["t0"]), 0.0, 1.0)
    fix = S["F"].T @ (1.0 / (1.0 + np.exp(-12.0 * t + 12.0)))
    b = best(s)
    return {"nl": best(nl), "nlce": b, "full": b + LOCUS_BETA1 * fix}, s, alpha

def _put(row, src, sc, keep, keys, rk):
    """Ghi danh sách của 1 cấu hình vào dòng kết quả, theo dạng mà fused_multi đọc. Trả thứ tự cột đã chọn."""
    sc = np.where(keep, sc, 0.0)
    order = [j for j in np.lexsort((keys, -sc)) if sc[j] > 0][:LOCUS_TOPN]
    ids = [keys[j] for j in order]
    pos = {x: i + 1 for i, x in enumerate(ids)}
    row[f"doc_ids_{src}"] = ids
    row[f"doc_score_{src}"] = [round(float(sc[j]), 6) for j in order]
    row[f"doc_r_{src}"] = [rk.get(x, 0) for x in ids]
    row[f"doc_gold_{src}"] = [pos.get(g) for g in row["gold_ids"]]
    return order

def _graph_names(nodes):
    """Tên dùng cho CE: tên lớp và hàm, cùng tên module dạng chấm (django/db/models/query.py → django.db.models.query)."""
    out = {n["name"] for n in nodes if n["label"] in _FC and n.get("name")}
    for n in nodes:
        if n["label"] == "Module" and n.get("name", "").endswith(".py"):
            out.add(n["name"][:-3].replace("/", ".").removesuffix(".__init__"))
    return out

_created = {r["instance_id"]: pd.Timestamp(r["created_at"]).timestamp()
            for r in load_dataset("princeton-nlp/SWE-bench", split="test") if r["repo"] in SCALE_REPOS}
_inst = {i["id"]: i for i in SCALE_INSTANCES}
_rows = [json.loads(l) for l in open(V4_RESULTS, encoding="utf-8") if l.strip()]
_todo = [r for r in _rows if "skip" not in r and f"doc_ids_{LOCUS_SRC}" not in r]
print(f"{V4_RESULTS}: {len(_rows)} dòng | cần tính HIST (Locus): {len(_todo)}")
_LC = {}
for (_repo, _snap), _grp in groupby(sorted(_todo, key=lambda r: (r["Repo"], _inst[r["Instance"]]["snap_ct"], _inst[r["Instance"]]["snapshot"])),
                                    key=lambda r: (r["Repo"], _inst[r["Instance"]]["snapshot"])):
    if _repo not in _LC:
        _LC[_repo] = locus_corpus(_repo)
    C, s8 = _LC[_repo], _snap[:8]
    _of = build_graph(_snap, repo_path=repo_path_of(_repo))
    _nodes = json.load(open(graph_summary_path(_of), encoding="utf-8"))["nodes"]
    _fc = {n["id"] for n in _nodes if n["label"] in _FC}
    S = locus_snapshot(C, _repo, _snap, _graph_names(_nodes))
    keep = np.array([f"{s8}:{k}" in _fc for k in C["fn_keys"]])
    keys = np.array(C["fn_keys"])
    for row in _grp:
        inst = _inst[row["Instance"]]
        scs, s, alpha = locus_rank(C, S, inst["text"], _created[row["Instance"]])
        rk = {x: i + 1 for i, x in enumerate(row["ast_ids"])}
        _put(row, f"{LOCUS_SRC}_nl", scs["nl"], keep, keys, rk)          # phân tích thành phần: chỉ NL
        _put(row, f"{LOCUS_SRC}_nlce", scs["nlce"], keep, keys, rk)      # phân tích thành phần: NL + α·CE
        order = _put(row, LOCUS_SRC, scs["full"], keep, keys, rk)        # nguồn HIST: NL + α·CE + β1·Fix
        row["hist_locus_alpha"] = round(alpha, 4)
        ev = []
        for j in order[:LOCUS_EVID]:                     # hunk tốt nhất của mỗi hàm/lớp đầu (bằng chứng cho judge)
            loc = S["M"].indices[S["M"].indptr[j]:S["M"].indptr[j + 1]]
            if len(loc):
                hk = C["hunks"][S["rows"][loc[np.argmax(s[loc])]]]
                ev.append([C["fn_keys"][j], hk["u"][:8], hk["f"], hk["k"]])
        row["hist_locus_best"] = ev
_tmp = Path(str(V4_RESULTS) + ".tmp")
with open(_tmp, "w", encoding="utf-8") as f:
    for r in _rows:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
_tmp.replace(V4_RESULTS)

_top10 = lambda r, src: int(any(p and p <= 10 for p in r[f"doc_gold_{src}"]))
_d = pd.DataFrame([{"Repo": r["Repo"], "Độ dài": len(r[f"doc_ids_{LOCUS_SRC}"]), "α": r["hist_locus_alpha"],
                    "Gold trong top 10, chỉ NL": _top10(r, f"{LOCUS_SRC}_nl"),
                    "Gold trong top 10, NL+CE": _top10(r, f"{LOCUS_SRC}_nlce"),
                    "Gold trong top 10, đủ": _top10(r, LOCUS_SRC),
                    "Gold trong top 100, đủ": int(any(p and p <= 100 for p in r[f"doc_gold_{LOCUS_SRC}"]))}
                   for r in _rows if "skip" not in r and f"doc_ids_{LOCUS_SRC}" in r])
print("Danh sách HIST riêng (chưa trộn với AST), để kiểm tra nhanh:")
display(_d.groupby("Repo").agg(**{"Instance": ("α", "size"), "Độ dài trung vị": ("Độ dài", "median"),
                                   "α trung vị": ("α", "median"),
                                   **{k: (k, "mean") for k in _d.columns if k.startswith("Gold")}}).round(3))

/kaggle/working/v4/scale_rows_v4.jsonl: 1236 dòng | cần tính HIST (Locus): 1187

hunk django/django:   0%|          | 0/10736 [00:00<?, ?commit/s]

văn bản django/django:   0%|          | 0/53365 [00:00<?, ?hunk/s]

[f9de1972] disk cache hit → /kaggle/working/django_graph_f9de1972.json
[9dcfecb7] disk cache hit → /kaggle/working/django_graph_9dcfecb7.json
[0368d63a] disk cache hit → /kaggle/working/django_graph_0368d63a.json
[af1fa5e7] disk cache hit → /kaggle/working/django_graph_af1fa5e7.json
[a8bb4935] disk cache hit → /kaggle/working/django_graph_a8bb4935.json
[511dfb33] disk cache hit → /kaggle/working/django_graph_511dfb33.json
[6f0b8c1c] disk cache hit → /kaggle/working/django_graph_6f0b8c1c.json
[02cd16a7] disk cache hit → /kaggle/working/django_graph_02cd16a7.json
[76dfa834] disk cache hit → /kaggle/working/django_graph_76dfa834.json
[838e432e] disk cache hit → /kaggle/working/django_graph_838e432e.json
[2aaabe20] disk cache hit → /kaggle/working/django_graph_2aaabe20.json
[df28ebd6] disk cache hit → /kaggle/working/django_graph_df28ebd6.json
[60dc957a] disk cache hit → /kaggle/working/django_graph_60dc957a.json
[44077985] disk cache hit → /kaggle/working/django_graph_44077985.json
[cbe4d620] disk cache hit → /kaggle/working/django_graph_cbe4d620.json
[b423873c] disk cache hit → /kaggle/working/django_graph_b423873c.json
[895f28f9] disk cache hit → /kaggle/working/django_graph_895f28f9.json
[49ae7ce5] disk cache hit → /kaggle/working/django_graph_49ae7ce5.json
[d08e6f55] disk cache hit → /kaggle/working/django_graph_d08e6f55.json
[419a7830] disk cache hit → /kaggle/working/django_graph_419a7830.json
[71ae1ab0] disk cache hit → /kaggle/working/django_graph_71ae1ab0.json
[464a4c0c] disk cache hit → /kaggle/working/django_graph_464a4c0c.json
[7072bff1] disk cache hit → /kaggle/working/django_graph_7072bff1.json
[bef6f758] disk cache hit → /kaggle/working/django_graph_bef6f758.json
[41e6b2a3] disk cache hit → /kaggle/working/django_graph_41e6b2a3.json
[65dfb06a] disk cache hit → /kaggle/working/django_graph_65dfb06a.json
[fa4e963e] disk cache hit → /kaggle/working/django_graph_fa4e963e.json
[59942a66] disk cache hit → /kaggle/working/django_graph_59942a66.json
[475cffd1] disk cache hit → /kaggle/working/django_graph_475cffd1.json
[32b7ffc2] disk cache hit → /kaggle/working/django_graph_32b7ffc2.json
[dd528cb2] disk cache hit → /kaggle/working/django_graph_dd528cb2.json
[7c4f3965] disk cache hit → /kaggle/working/django_graph_7c4f3965.json
[1d9d082a] disk cache hit → /kaggle/working/django_graph_1d9d082a.json
[1a78ef2b] disk cache hit → /kaggle/working/django_graph_1a78ef2b.json
[2fac0a18] disk cache hit → /kaggle/working/django_graph_2fac0a18.json
[d938b3b2] disk cache hit → /kaggle/working/django_graph_d938b3b2.json
[60a7bd89] disk cache hit → /kaggle/working/django_graph_60a7bd89.json
[39f83765] disk cache hit → /kaggle/working/django_graph_39f83765.json
[051d5944] disk cache hit → /kaggle/working/django_graph_051d5944.json
[98f6ada0] disk cache hit → /kaggle/working/django_graph_98f6ada0.json

hunk sympy/sympy:   0%|          | 0/6224 [00:00<?, ?commit/s]

văn bản sympy/sympy:   0%|          | 0/67202 [00:00<?, ?hunk/s]

[496e7761] disk cache hit → /kaggle/working/sympy_graph_496e7761.json
[360290c4] disk cache hit → /kaggle/working/sympy_graph_360290c4.json
[0410a6aa] disk cache hit → /kaggle/working/sympy_graph_0410a6aa.json
[a53c4ad9] disk cache hit → /kaggle/working/sympy_graph_a53c4ad9.json
[479939f8] disk cache hit → /kaggle/working/sympy_graph_479939f8.json
[0cd4f13a] disk cache hit → /kaggle/working/sympy_graph_0cd4f13a.json
[d250ff08] disk cache hit → /kaggle/working/sympy_graph_d250ff08.json
[ae3d62ab] disk cache hit → /kaggle/working/sympy_graph_ae3d62ab.json
[b3934e41] disk cache hit → /kaggle/working/sympy_graph_b3934e41.json
[9bf73cc2] disk cache hit → /kaggle/working/sympy_graph_9bf73cc2.json
[205da797] disk cache hit → /kaggle/working/sympy_graph_205da797.json
[8fc63c2d] disk cache hit → /kaggle/working/sympy_graph_8fc63c2d.json
[9cbea134] disk cache hit → /kaggle/working/sympy_graph_9cbea134.json
[678217d5] disk cache hit → /kaggle/working/sympy_graph_678217d5.json
[6399a809] disk cache hit → /kaggle/working/sympy_graph_6399a809.json
[28d913d3] disk cache hit → /kaggle/working/sympy_graph_28d913d3.json
[356a73cd] disk cache hit → /kaggle/working/sympy_graph_356a73cd.json
[0469e038] disk cache hit → /kaggle/working/sympy_graph_0469e038.json
[c50643a4] disk cache hit → /kaggle/working/sympy_graph_c50643a4.json
[8ca4a683] disk cache hit → /kaggle/working/sympy_graph_8ca4a683.json
[f5e96594] disk cache hit → /kaggle/working/sympy_graph_f5e96594.json
[cab3c1cb] disk cache hit → /kaggle/working/sympy_graph_cab3c1cb.json
[70381f28] disk cache hit → /kaggle/working/sympy_graph_70381f28.json
[fcefd30c] disk cache hit → /kaggle/working/sympy_graph_fcefd30c.json
[46921d28] disk cache hit → /kaggle/working/sympy_graph_46921d28.json
[e0ef1da1] disk cache hit → /kaggle/working/sympy_graph_e0ef1da1.json
[b1078cd0] disk cache hit → /kaggle/working/sympy_graph_b1078cd0.json
[d57aaf06] disk cache hit → /kaggle/working/sympy_graph_d57aaf06.json
[d5571e8b] disk cache hit → /kaggle/working/sympy_graph_d5571e8b.json
[cffd4e0f] disk cache hit → /kaggle/working/sympy_graph_cffd4e0f.json
[eb926a1d] disk cache hit → /kaggle/working/sympy_graph_eb926a1d.json
[748ce734] disk cache hit → /kaggle/working/sympy_graph_748ce734.json
[546e1079] disk cache hit → /kaggle/working/sympy_graph_546e1079.json
[b4777fdc] disk cache hit → /kaggle/working/sympy_graph_b4777fdc.json
[ec0fe8c5] disk cache hit → /kaggle/working/sympy_graph_ec0fe8c5.json
[3f8c8c23] disk cache hit → /kaggle/working/sympy_graph_3f8c8c23.json
[a3475b3f] disk cache hit → /kaggle/working/sympy_graph_a3475b3f.json
[d7bddf4f] disk cache hit → /kaggle/working/sympy_graph_d7bddf4f.json
[96c9c40b] disk cache hit → /kaggle/working/sympy_graph_96c9c40b.json
[9a6104ea] disk cache hit → /kaggle/working/sympy_graph_9a6104ea.json
[68bd3627] disk cache hit → /kaggle/working/sympy_graph_68bd3627.json
[514579c6] disk cache hit → /kaggle/working/sympy_graph_514579c6.json
[cdef6fcb] disk cache hit → /kaggle/working/sympy_graph_cdef6fcb.json
[c4d6b3eb] disk cache hit → /kaggle/working/sympy_graph_c4d6b3eb.json
[d3b4158d] disk cache hit → /kaggle/working/sympy_graph_d3b4158d.json
Danh sách HIST riêng (chưa trộn với AST), để kiểm tra nhanh:

,Instance,Độ dài trung vị,α trung vị,"Gold trong top 10, chỉ NL","Gold trong top 10, NL+CE","Gold trong top 10, đủ","Gold trong top 100, đủ"
Repo,,,,,,,
django/django,821,500.0,0.248,0.532,0.577,0.431,0.797
sympy/sympy,366,500.0,0.491,0.445,0.503,0.489,0.708

In [37]:
# ── Section 8 (v4): tính lại v3 với oracle mới (việc 1.2), trình bày theo mục 6.8 của planning.md ───────────────
# Bốn hệ thống của v3 giữ đúng cấu hình trộn mà v3 đã chọn trên Kaggle: DOC (p = 0,1, h = 1), HIST (10 commit, p = 0,25,
# h = 3), DOC+HIST (DOC p = 0,1 cùng HIST 10 commit p = 0,25, h = 3). Chỉ gold (oracle mới) và độ sâu xếp hạng (500 thay
# vì 100) thay đổi. Đề tài không tách dev và test, nên số liệu tính trên mọi instance có kết quả trong V4_RESULTS.
# Bảng 1: Top@1, Top@5, Top@10, MRR, MAP, Acc@10. Bảng 2: thay đổi theo từng instance so với hệ thống được so, tách theo
# độ khó của AST, kèm McNemar cho Top@10 (bản chính xác: kiểm định nhị thức trên các instance hai hệ thống bất đồng).
# Phân tích bổ sung 2: tách theo việc issue có nêu sẵn tên gold hay không. Điểm dừng: Top@10 của DOC+HIST phải cao hơn AST.
from scipy.stats import binomtest

LIST_K = V4_TOPK                     # danh sách sau khi trộn dài tới 500 → MRR và MAP tính tới hạng 500
V3_SYSTEMS = {                       # tên → (các nguồn kèm trọng số p, h)
    "AST":      ([], 0),
    "DOC":      ([("vote_ast", 0.1)], 1),
    "HIST":     ([("vote_hist10_ast", 0.25)], 3),
    "DOC+HIST": ([("vote_ast", 0.1), ("vote_hist10_ast", 0.25)], 3),
}
V3_PAIRS = [("DOC", "AST"), ("HIST", "AST"), ("DOC+HIST", "AST"), ("DOC+HIST", "DOC"), ("DOC+HIST", "HIST")]
_MET = ["Top@1", "Top@5", "Top@10", "MRR", "MAP", "Acc@10"]

def fused_multi(row, terms, h=0):
    """Chép nguyên từ cell scale-fusion, vì cell đó bị chặn khi RUN_V3 = False.
    RRF của xếp hạng AST với nhiều tập: điểm = 1/(k + hạng AST) + Σ p_s/(k + vị trí trong tập s)."""
    ast = row["ast_ids"]
    ra = {x: i + 1 for i, x in enumerate(ast)}
    score, extra = defaultdict(float), set()
    for x, r in ra.items():
        score[x] += 1.0 / (FUSE_K + r)
    for s, p in terms:
        for j, (x, r) in enumerate(zip(row[f"doc_ids_{s}"], row[f"doc_r_{s}"]), 1):
            if x not in ra and r and x not in extra:
                score[x] += 1.0 / (FUSE_K + r)             # hạng AST ngoài top SCALE_TOPK chỉ tính 1 lần
                extra.add(x)
            score[x] += p / (FUSE_K + j)
    order = sorted(score, key=lambda x: (-score[x], ra.get(x, 10 ** 6), x))
    if h:
        head = ast[:h]
        order = head + [x for x in order if x not in set(head)]
    return order[:LIST_K]

def _metrics(order, gold):
    """Độ đo của 1 instance. ranks = hạng của các gold có trong danh sách, tăng dần. MAP: độ chính xác tại hạng của
    từng gold, gold ngoài danh sách góp 0, chia cho số gold."""
    pos = {x: i + 1 for i, x in enumerate(order)}
    ranks = sorted(pos[g] for g in gold if g in pos)
    best = ranks[0] if ranks else None
    return {"Top@1": int(best is not None and best <= 1), "Top@5": int(best is not None and best <= 5),
            "Top@10": int(best is not None and best <= 10), "MRR": 1.0 / best if best else 0.0,
            "MAP": sum((i + 1) / r for i, r in enumerate(ranks)) / len(gold),
            "Acc@10": int(sum(r <= 10 for r in ranks) == len(gold)), "best": best or LIST_K + 1}

_v3rows = [json.loads(l) for l in open(V4_RESULTS, encoding="utf-8") if l.strip()]
_v3rows = [r for r in _v3rows if "skip" not in r and r.get("gold_ids")]
_V3M = pd.DataFrame([{"Instance": r["Instance"], "Repo": r["Repo"].split("/")[1], "lite": bool(r["lite"]),
                      "nêu tên gold": bool(r.get("issue_names_gold")), "Hệ thống": name,
                      **_metrics(fused_multi(r, terms, h), r["gold_ids"])}
                     for r in _v3rows for name, (terms, h) in V3_SYSTEMS.items()])
_order = list(V3_SYSTEMS)

def _table1(M):
    """Bảng 1: mỗi hệ thống một hàng; Top@k và Acc@10 theo %, MRR và MAP từ 0 đến 1."""
    t = M.groupby("Hệ thống")[_MET].mean().reindex(_order)
    t[["Top@1", "Top@5", "Top@10", "Acc@10"]] *= 100
    return t.round({"Top@1": 1, "Top@5": 1, "Top@10": 1, "Acc@10": 1, "MRR": 3, "MAP": 3})

def _table2(M):
    """Bảng 2: với mỗi cặp, số instance tốt hơn / kém hơn / không đổi theo hạng gold tốt nhất, tách theo độ khó của AST,
    kèm McNemar cho Top@10 (b = chỉ hệ thống thứ nhất trúng, c = chỉ hệ thống thứ hai trúng)."""
    W = M.pivot(index="Instance", columns="Hệ thống", values=["best", "Top@10"])
    diff = pd.cut(W[("best", "AST")], [0, 10, 100, np.inf], labels=["AST: gold trong top 10", "AST: hạng 11 đến 100",
                                                                     "AST: ngoài hạng 100"])
    out = []
    for a, b in V3_PAIRS:
        d = np.sign(W[("best", b)] - W[("best", a)])                # 1 = a tốt hơn b, −1 = a kém hơn
        for grp, idx in [("Tất cả", W.index)] + [(g, W.index[diff == g]) for g in diff.cat.categories]:
            dd = d.loc[idx]
            out.append({"So sánh": f"{a} so với {b}", "Nhóm": grp, "Số instance": len(dd),
                        "Tốt hơn": int((dd > 0).sum()), "Kém hơn": int((dd < 0).sum()), "Không đổi": int((dd == 0).sum())})
        hb = int(((W[("Top@10", a)] == 1) & (W[("Top@10", b)] == 0)).sum())
        hc = int(((W[("Top@10", a)] == 0) & (W[("Top@10", b)] == 1)).sum())
        out[-4].update({"McNemar Top@10 (b / c)": f"{hb} / {hc}",
                        "p": round(binomtest(hb, hb + hc, 0.5).pvalue, 4) if hb + hc else 1.0})
    t = pd.DataFrame(out)
    for k in ("Tốt hơn", "Kém hơn", "Không đổi"):
        t[k] = [f"{v} ({100 * v / n:.1f}%)" if n else "0" for v, n in zip(t[k], t["Số instance"])]
    return t.fillna("")

print(f"Tính lại v3 với oracle mới: {_V3M.Instance.nunique()} instance | LIST_K = {LIST_K}")
for scope, M in [("Gộp hai repo", _V3M)] + [(f"Riêng {rp}", _V3M[_V3M.Repo == rp]) for rp in sorted(_V3M.Repo.unique())]:
    print(f"\nBảng 1. {scope} ({M.Instance.nunique()} instance)")
    display(_table1(M))
print("\nBảng 2. Thay đổi theo từng instance, gộp hai repo")
display(_table2(_V3M))
for flag, name in [(True, "issue nêu sẵn tên gold"), (False, "issue không nêu tên gold")]:
    M = _V3M[_V3M["nêu tên gold"] == flag]
    if len(M):
        print(f"\nPhân tích bổ sung 2, nhóm {name} ({M.Instance.nunique()} instance)")
        display(_table1(M))
        display(_table2(M))

# Điểm dừng của việc 1.2: kết luận hẹp là Top@10 của DOC+HIST cao hơn AST. Kết luận này được nêu trên 1.006 instance
# không thuộc Lite (tập test của v3), nên kiểm tra trên cả tập đó lẫn trên mọi instance.
for scope, M in [("mọi instance", _V3M), ("1.006 instance không thuộc Lite (tập test của v3)", _V3M[~_V3M.lite])]:
    t = M.groupby("Hệ thống")["Top@10"].mean() * 100
    a, b = t.get("AST", float("nan")), t.get("DOC+HIST", float("nan"))
    msg = ("kết luận hẹp giữ nguyên" if b > a else
           "DOC+HIST KHÔNG CÒN CAO HƠN AST: dừng lại để tìm nguyên nhân" if b == a else
           "KẾT LUẬN HẸP ĐỔI CHIỀU: dừng lại để tìm nguyên nhân")
    print(f"Điểm dừng, {scope}: Top@10 AST {a:.1f}% | DOC+HIST {b:.1f}% → {msg}")

Tính lại v3 với oracle mới: 1187 instance | LIST_K = 500

Bảng 1. Gộp hai repo (1187 instance)

          Top@1  Top@5  Top@10    MRR    MAP  Acc@10
Hệ thống
AST        23.9   45.6    55.5  0.345  0.266    33.6
DOC        23.9   46.7    57.4  0.349  0.268    35.8
HIST       23.9   50.7    59.7  0.354  0.274    36.9
DOC+HIST   23.9   51.2    61.2  0.356  0.276    38.4

Bảng 1. Riêng django (821 instance)

          Top@1  Top@5  Top@10    MRR    MAP  Acc@10
Hệ thống
AST        23.4   46.0    56.6  0.344  0.277    36.1
DOC        23.4   46.9    58.7  0.349  0.280    38.2
HIST       23.4   51.9    61.4  0.354  0.287    39.7
DOC+HIST   23.4   52.3    62.6  0.355  0.289    41.3

Bảng 1. Riêng sympy (366 instance)

          Top@1  Top@5  Top@10    MRR    MAP  Acc@10
Hệ thống
AST        25.1   44.5    53.0  0.347  0.240    28.1
DOC        25.1   46.2    54.4  0.348  0.240    30.3
HIST       25.1   48.1    56.0  0.354  0.245    30.6
DOC+HIST   25.1   48.9    58.2  0.356  0.247    32.0

Bảng 2. Thay đổi theo từng instance, gộp hai repo

,So sánh,Nhóm,Số instance,Tốt hơn,Kém hơn,Không đổi,McNemar Top@10 (b / c),p
0,DOC so với AST,Tất cả,1187,171 (14.4%),282 (23.8%),734 (61.8%),26 / 4,0.0001
1,DOC so với AST,AST: gold trong top 10,659,77 (11.7%),118 (17.9%),464 (70.4%),,
2,DOC so với AST,AST: hạng 11 đến 100,308,80 (26.0%),99 (32.1%),129 (41.9%),,
3,DOC so với AST,AST: ngoài hạng 100,220,14 (6.4%),65 (29.5%),141 (64.1%),,
4,HIST so với AST,Tất cả,1187,206 (17.4%),333 (28.1%),648 (54.6%),71 / 21,0.0
5,HIST so với AST,AST: gold trong top 10,659,67 (10.2%),78 (11.8%),514 (78.0%),,
6,HIST so với AST,AST: hạng 11 đến 100,308,105 (34.1%),161 (52.3%),42 (13.6%),,
7,HIST so với AST,AST: ngoài hạng 100,220,34 (15.5%),94 (42.7%),92 (41.8%),,
8,DOC+HIST so với AST,Tất cả,1187,268 (22.6%),297 (25.0%),622 (52.4%),87 / 19,0.0
9,DOC+HIST so với AST,AST: gold trong top 10,659,77 (11.7%),77 (11.7%),505 (76.6%),,
10,DOC+HIST so với AST,AST: hạng 11 đến 100,308,148 (48.1%),135 (43.8%),25 (8.1%),,
11,DOC+HIST so với AST,AST: ngoài hạng 100,220,43 (19.5%),85 (38.6%),92 (41.8%),,
12,DOC+HIST so với DOC,Tất cả,1187,256 (21.6%),374 (31.5%),557 (46.9%),67 / 21,0.0
13,DOC+HIST so với DOC,AST: gold trong top 10,659,120 (18.2%),118 (17.9%),421 (63.9%),,
14,DOC+HIST so với DOC,AST: hạng 11 đến 100,308,102 (33.1%),163 (52.9%),43 (14.0%),,
15,DOC+HIST so với DOC,AST: ngoài hạng 100,220,34 (15.5%),93 (42.3%),93 (42.3%),,
16,DOC+HIST so với HIST,Tất cả,1187,116 (9.8%),195 (16.4%),876 (73.8%),21 / 3,0.0003
17,DOC+HIST so với HIST,AST: gold trong top 10,659,30 (4.6%),35 (5.3%),594 (90.1%),,
18,DOC+HIST so với HIST,AST: hạng 11 đến 100,308,69 (22.4%),87 (28.2%),152 (49.4%),,
19,DOC+HIST so với HIST,AST: ngoài hạng 100,220,17 (7.7%),73 (33.2%),130 (59.1%),,

Phân tích bổ sung 2, nhóm issue nêu sẵn tên gold (572 instance)

          Top@1  Top@5  Top@10    MRR    MAP  Acc@10
Hệ thống
AST        37.4   62.6    72.4  0.495  0.371    42.8
DOC        37.4   64.3    74.7  0.498  0.373    45.6
HIST       37.4   67.0    74.7  0.501  0.375    44.9
DOC+HIST   37.4   68.0    76.7  0.503  0.379    47.0

,So sánh,Nhóm,Số instance,Tốt hơn,Kém hơn,Không đổi,McNemar Top@10 (b / c),p
0,DOC so với AST,Tất cả,572,92 (16.1%),98 (17.1%),382 (66.8%),14 / 1,0.001
1,DOC so với AST,AST: gold trong top 10,414,45 (10.9%),58 (14.0%),311 (75.1%),,
2,DOC so với AST,AST: hạng 11 đến 100,116,42 (36.2%),32 (27.6%),42 (36.2%),,
3,DOC so với AST,AST: ngoài hạng 100,42,5 (11.9%),8 (19.0%),29 (69.0%),,
4,HIST so với AST,Tất cả,572,71 (12.4%),117 (20.5%),384 (67.1%),24 / 11,0.041
5,HIST so với AST,AST: gold trong top 10,414,27 (6.5%),39 (9.4%),348 (84.1%),,
6,HIST so với AST,AST: hạng 11 đến 100,116,37 (31.9%),58 (50.0%),21 (18.1%),,
7,HIST so với AST,AST: ngoài hạng 100,42,7 (16.7%),20 (47.6%),15 (35.7%),,
8,DOC+HIST so với AST,Tất cả,572,105 (18.4%),92 (16.1%),375 (65.6%),34 / 9,0.0002
9,DOC+HIST so với AST,AST: gold trong top 10,414,35 (8.5%),32 (7.7%),347 (83.8%),,
10,DOC+HIST so với AST,AST: hạng 11 đến 100,116,60 (51.7%),43 (37.1%),13 (11.2%),,
11,DOC+HIST so với AST,AST: ngoài hạng 100,42,10 (23.8%),17 (40.5%),15 (35.7%),,
12,DOC+HIST so với DOC,Tất cả,572,102 (17.8%),141 (24.7%),329 (57.5%),22 / 10,0.0501
13,DOC+HIST so với DOC,AST: gold trong top 10,414,59 (14.3%),63 (15.2%),292 (70.5%),,
14,DOC+HIST so với DOC,AST: hạng 11 đến 100,116,36 (31.0%),58 (50.0%),22 (19.0%),,
15,DOC+HIST so với DOC,AST: ngoài hạng 100,42,7 (16.7%),20 (47.6%),15 (35.7%),,
16,DOC+HIST so với HIST,Tất cả,572,57 (10.0%),48 (8.4%),467 (81.6%),14 / 2,0.0042
17,DOC+HIST so với HIST,AST: gold trong top 10,414,16 (3.9%),10 (2.4%),388 (93.7%),,
18,DOC+HIST so với HIST,AST: hạng 11 đến 100,116,36 (31.0%),26 (22.4%),54 (46.6%),,
19,DOC+HIST so với HIST,AST: ngoài hạng 100,42,5 (11.9%),12 (28.6%),25 (59.5%),,

Phân tích bổ sung 2, nhóm issue không nêu tên gold (615 instance)

          Top@1  Top@5  Top@10    MRR    MAP  Acc@10
Hệ thống
AST        11.4   29.8    39.8  0.206  0.169    25.0
DOC        11.4   30.2    41.3  0.210  0.170    26.7
HIST       11.4   35.6    45.9  0.217  0.179    29.4
DOC+HIST   11.4   35.6    46.8  0.218  0.180    30.4

,So sánh,Nhóm,Số instance,Tốt hơn,Kém hơn,Không đổi,McNemar Top@10 (b / c),p
0,DOC so với AST,Tất cả,615,79 (12.8%),184 (29.9%),352 (57.2%),12 / 3,0.0352
1,DOC so với AST,AST: gold trong top 10,245,32 (13.1%),60 (24.5%),153 (62.4%),,
2,DOC so với AST,AST: hạng 11 đến 100,192,38 (19.8%),67 (34.9%),87 (45.3%),,
3,DOC so với AST,AST: ngoài hạng 100,178,9 (5.1%),57 (32.0%),112 (62.9%),,
4,HIST so với AST,Tất cả,615,135 (22.0%),216 (35.1%),264 (42.9%),47 / 10,0.0
5,HIST so với AST,AST: gold trong top 10,245,40 (16.3%),39 (15.9%),166 (67.8%),,
6,HIST so với AST,AST: hạng 11 đến 100,192,68 (35.4%),103 (53.6%),21 (10.9%),,
7,HIST so với AST,AST: ngoài hạng 100,178,27 (15.2%),74 (41.6%),77 (43.3%),,
8,DOC+HIST so với AST,Tất cả,615,163 (26.5%),205 (33.3%),247 (40.2%),53 / 10,0.0
9,DOC+HIST so với AST,AST: gold trong top 10,245,42 (17.1%),45 (18.4%),158 (64.5%),,
10,DOC+HIST so với AST,AST: hạng 11 đến 100,192,88 (45.8%),92 (47.9%),12 (6.2%),,
11,DOC+HIST so với AST,AST: ngoài hạng 100,178,33 (18.5%),68 (38.2%),77 (43.3%),,
12,DOC+HIST so với DOC,Tất cả,615,154 (25.0%),233 (37.9%),228 (37.1%),45 / 11,0.0
13,DOC+HIST so với DOC,AST: gold trong top 10,245,61 (24.9%),55 (22.4%),129 (52.7%),,
14,DOC+HIST so với DOC,AST: hạng 11 đến 100,192,66 (34.4%),105 (54.7%),21 (10.9%),,
15,DOC+HIST so với DOC,AST: ngoài hạng 100,178,27 (15.2%),73 (41.0%),78 (43.8%),,
16,DOC+HIST so với HIST,Tất cả,615,59 (9.6%),147 (23.9%),409 (66.5%),7 / 1,0.0703
17,DOC+HIST so với HIST,AST: gold trong top 10,245,14 (5.7%),25 (10.2%),206 (84.1%),,
18,DOC+HIST so với HIST,AST: hạng 11 đến 100,192,33 (17.2%),61 (31.8%),98 (51.0%),,
19,DOC+HIST so với HIST,AST: ngoài hạng 100,178,12 (6.7%),61 (34.3%),105 (59.0%),,

Điểm dừng, mọi instance: Top@10 AST 55.5% | DOC+HIST 61.2% → kết luận hẹp giữ nguyên
Điểm dừng, 1.006 instance không thuộc Lite (tập test của v3): Top@10 AST 57.6% | DOC+HIST 63.2% → kết luận hẹp giữ nguyên